### ISSUE TITLE
Adjust the scheduled amount of Ravencoin exchanged based on a USD price

### ISSUE THREAD

**Issue by hizzvizz** [RavenProject/Ravencoin#10]
### Description

I would like Ravencoin to be able to adjust to market fluctuations so if I send a specific USD or other currency to someone, they get the exact amount of Ravencoin that equals said USD. There can be controls in place so that a person doesn't send more than they are able to send or more than they are comfortable with. If the exchange rate falls outside of the predetermined bands, the scheduled transaction is cancelled.

### Use case

Jimmy tells Sally he will pay her rent in Ravencoin or some other equivalent token in one month. Jimmy promises to pay even if the market value goes up or down by 10%. Jimmy schedules the transaction and Sally sees a message saying their is a future transaction pending.

Market stays within +- 10%  -> Transaction goes through after one month and the actual Ravencoin or token transmitted is adjusted so the amount sent is at the correct USD or other currency value.

Market goes outside of +- 10% -> Transaction is paused and Jimmy has to agree to continue the transaction. If Jimmy continues the transmission the Ravencoin or token amount is adjusted to match the initial USD or other currency value. If the transaction is rejected, Sally receives a notification that the transaction was cancelled.

**Comment by bouguerra12** [comment]
i think its too early to evaluate the usd price of ravencoin

**Comment by burlaroni** [comment]
How about now?

**Comment by hizzvizz** [comment]
Steem does it with SBD (Steem Backed Dollar)

They describe the process here: https://steem.io/SteemWhitePaper.pdf

**Comment by RavenCoinDev** [comment]
Ravencoin, if it has a value, will fluctuate based on supply and demand.  We have no plans to link it to any fiat currency.  RVN is global in nature and belongs to the world.   It will likely be added to exchanges someday which will give it a market price denominated in a number of crypto and fiat currencies.
