### ISSUE TITLE
 error: libdb_cxx headers missing for mac osx builds

### ISSUE THREAD

**Issue by abridgel** [RavenProject/Ravencoin#1001]
On Mac OS machines after the initial fork and clone you may hit the following error after step 2 (https://github.com/abridgel/Ravencoin/blob/master/doc/build-osx.md)

configure: error: libdb_cxx headers missing

To get around it you can run the following

> brew link berkeley-db4 --force

**Comment by Brock-Wood** [comment]
I ran into this problem too.

OSX Version: 11.4 (Big Sur)
Xcode Version: 12.5.1

Related to #1006, bitcoin/bitcoin#7970, bitcoin/bitcoin#19411

When running the recommended install script for Berkeley DB 4.8, I get the following errors:

'''bash
./contrib/install_db4.sh .

configure: WARNING: NO SHARED LATCH IMPLEMENTATION FOUND FOR THIS PLATFORM.
configure: error: Unable to find a mutex implementation
'''

Potential Solution: 
bitcoin/bitcoin#20195

**Comment by fdoving** [comment]
Fixed in develop branch
