### ISSUE TITLE
Cannot running cli after change

### ISSUE THREAD

**Issue by FndNur1Labs** [RavenProject/Ravencoin#1037]
i running the cli and got problem after config files

![image](https://user-images.githubusercontent.com/11433397/120079087-9cbe7e00-c0dc-11eb-9f60-b41ad54614c3.png)
![image](https://user-images.githubusercontent.com/11433397/120079101-ab0c9a00-c0dc-11eb-8afe-48f59b67a2e3.png)

**Comment by hans-schmidt** [comment]
You need to run:
./raven-cli rpcuser=P6EPzTb6K1 rpcpassword=13eMnw05wMNuE985p1rf2v getinfo

**Comment by FndNur1Labs** [comment]
> You need to run:
> ./raven-cli rpcuser=P6EPzTb6K1 rpcpassword=13eMnw05wMNuE985p1rf2v getinfo

Thank fixed already on conf. I look need sync header first then block.
