### ISSUE TITLE
no payments when block sits pending over three hours

### ISSUE THREAD

**Issue by bforemanl** [RavenProject/Ravencoin#1044]
Hello the payment processor seems to not be working. I restated the server and it left from pending to not confirmed of pending.  I have waited over three hours and the pool hasn't paid the workers but has paid myself for the  0.50 percent. Does anyeone know the fix?

**Comment by bforemanl** [comment]
i'm using https://github.com/bforemanl/nomp-kawpow-pool

**Comment by fdoving** [comment]
I doubt this is related to Ravencoin-core. I would double check the pool setup.

**Comment by hans-schmidt** [comment]
I agree- this is unlikely to be a problem with Ravencoin-core.
I am closing this Issue.

**Comment by hans-schmidt** [comment]
Closed

**Comment by hans-schmidt** [comment]
I agree- this is unlikely to be a problem with Ravencoin-core.
I am closing this Issue.

**Comment by hans-schmidt** [comment]
I agree- this is unlikely to be a problem with Ravencoin-core.

**Comment by hans-schmidt** [comment]
.
