### ISSUE TITLE
Restricted Asset: Can't be re-issued until the wallet was closed and re-opened

### ISSUE THREAD

**Issue by HyperPeek** [RavenProject/Ravencoin#1059]
After creating a restricted asset, it does appear in the asset list of the wallet after some time. When trying to re-issue it under "Manage Assets" it will not appear in the list.
After closing / re-opening the wallet, the asset can be managed as usual.

**Comment by fdoving** [comment]
Confirmed.

Try to click the "clear" button, it should force an update of the asset-list.
I will make a PR.

**Comment by fdoving** [comment]
Please test PR #1060

**Comment by fdoving** [comment]
merged to develop
