### ISSUE TITLE
Testing: Wallet -> Get my words

### ISSUE THREAD

**Issue by fdoving** [RavenProject/Ravencoin#1065]
Post your test results as comments to this issue.

Please include release version or commit-hash used when testing.

Reference links:
https://github.com/RavenProject/Ravencoin/issues/975#issuecomment-833009926

https://github.com/RavenProject/Ravencoin/commit/6b4b69db944e36cc6595149ec49bdeb2ed92fe65

https://github.com/RavenProject/Ravencoin/issues/975

**Comment by lsji07** [comment]
Tested and working correctly on windows 10 and  Raven Core version v4.7.0.0-b5010492c (64-bit)

Wallet requests passphrase to unlock, if not already unlocked and locks the wallet once seed word window is closed. 

I would like to see this dialogue window timeout similar to how  the wallet passphrase works. Perhaps a timeout around 300 seconds initially. Users can always reset the clock by reopening the menu and getting their words and entering the wallet passphrase, if required.

**Comment by soullesscomputerboy** [comment]
Seems to work correctly on linux mint and v4.7.0.0-b5010492c (64-bit)

**Comment by m4r1m0** [comment]
Tested and works correctly on Ubuntu 20.04 using raven-4.7.0test3-b5010492c (64 bit)

Window took a few seconds to load up during which the QT was frozen but this only lasted 4-5seconds.

**Comment by fdoving** [comment]
3x Confirmed working as expected. Closing as finished.
