### ISSUE TITLE
Make Fail Arch Linux

### ISSUE THREAD

**Issue by Fractalguise** [RavenProject/Ravencoin#107]
### Describe the issue
Make fails when compiling on arch linux.

### Can you reliably reproduce the issue?
Yes
#### If so, please list the steps to reproduce below:
1. git clone (master branch)
2. ./autogen.sh
3. ./configure --disable-tests --disable-bench --without-miniupnpc CXXFLAGS="-fPIC" CFLAGS="-fPIC"
4. make
#
## Expected behaviour
It should compile without problems

### Actual behaviour
After CXXLD raven-tx compiling process stops

### Screenshots.
  CXXLD    raven-tx
libraven_common.a(libraven_common_a-coins.o): In function `AddCoins(CCoinsViewCache&, CTransaction const&, int, bool, CAssetsCache*, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >*)':
coins.cpp:(.text+0xc53): undefined reference to `AreAssetsDeployed()'
coins.cpp:(.text+0xc78): undefined reference to `CTransaction::IsNewAsset() const'
coins.cpp:(.text+0xcbe): undefined reference to `AssetFromTransaction(CTransaction const&, CNewAsset&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)'
coins.cpp:(.text+0xcfc): undefined reference to `OwnerFromTransaction(CTransaction const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)'
coins.cpp:(.text+0xd35): undefined reference to `CAssetsCache::AddNewAsset(CNewAsset const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
coins.cpp:(.text+0xda3): undefined reference to `CAssetsCache::AddOwnerAsset(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
coins.cpp:(.text+0xeae): undefined reference to `CAssetsCache::AddPossibleOutPoint(CAssetCachePossibleMine const&)'
coins.cpp:(.text+0xf7d): undefined reference to `CAssetsCache::AddPossibleOutPoint(CAssetCachePossibleMine const&)'
coins.cpp:(.text+0x100f): undefined reference to `CTransaction::IsReissueAsset() const'
coins.cpp:(.text+0x1055): undefined reference to `ReissueAssetFromTransaction(CTransaction const&, CReissueAsset&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)'
coins.cpp:(.text+0x1084): undefined reference to `CAssetsCache::GetAssetIfExists(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, CNewAsset&)'
coins.cpp:(.text+0x1120): undefined reference to `CAssetsCache::AddReissueAsset(CReissueAsset const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, COutPoint const&)'
coins.cpp:(.text+0x128b): undefined reference to `CAssetsCache::AddPossibleOutPoint(CAssetCachePossibleMine const&)'
coins.cpp:(.text+0x1418): undefined reference to `AreAssetsDeployed()'
coins.cpp:(.text+0x14f7): undefined reference to `TransferAssetFromScript(CScript const&, CAssetTransfer&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)'
coins.cpp:(.text+0x1628): undefined reference to `CAssetsCache::AddTransferAsset(CAssetTransfer const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, COutPoint const&, CTxOut const&)'
libraven_common.a(libraven_common_a-coins.o): In function `CCoinsViewCache::SpendCoin(COutPoint const&, Coin*, CAssetsCache*)':
coins.cpp:(.text+0x1f11): undefined reference to `AreAssetsDeployed()'
coins.cpp:(.text+0x1f3c): undefined reference to `CAssetsCache::TrySpendCoin(COutPoint const&, CTxOut const&)'
libraven_common.a(libraven_common_a-coins.o): In function `AccessByTxid(CCoinsViewCache const&, uint256 const&)':
coins.cpp:(.text+0x2a96): undefined reference to `GetMaxBlockWeight()'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:3894: raven-tx] Error 1
make[2]: Leaving directory '/home/fractalsguise/RVN/Ravencoin/src'
make[1]: *** [Makefile:10170: all-recursive] Error 1
make[1]: Leaving directory '/home/fractalsguise/RVN/Ravencoin/src'
make: *** [Makefile:746: all-recursive] Error 1

### Machine specs:
- OS: Arch Linux

### Any extra information that might be useful in the debugging process.
Boost was updated to version 1.67.  Not sure if that is the issue, bitcoin fork wallets i have used in the past needed boost 1.66

**Comment by underdarkskies** [comment]
run 
`git checkout master `
before compile

**Comment by underdarkskies** [comment]
side note devs, maybe change default branch back to master @cfox @cfrogjump @wolfsokta
