### ISSUE TITLE
French Translation 

### ISSUE THREAD

**Issue by gaetan29** [RavenProject/Ravencoin#1071]
Translation spelling error
"Evoyer" instead of "Envoyer"

![RVN01](https://user-images.githubusercontent.com/788375/121891200-74a95e80-cd1b-11eb-97ca-3f0f74aa738a.png)

**Comment by gaetan29** [comment]
Windows 10

**Comment by fdoving** [comment]
Thanks. I think it is fixed in the current translation.

I will update from Transifex before next test-release.

https://www.transifex.com/ravencoin/
