### ISSUE TITLE
Wrong amount in transaction

### ISSUE THREAD

**Issue by Philippe56380** [RavenProject/Ravencoin#1089]
1. I did transfer a 1 RVN amount yesterday to binance for testing purpose.
The account has been well credited.

![52vnkf8u64e71](https://user-images.githubusercontent.com/44290004/128234345-80fc6023-7d6a-4a7b-a82b-e4046a1bd42e.png)

2. The transaction appears correctly in the Ravencoin wallet:

![8o7ej7vy64e71](https://user-images.githubusercontent.com/44290004/128234362-17634e48-f813-43df-8ae1-801ace9acc23.png)

However the total amount of the raven wallet is not correct:

![jm2iqcv274e71](https://user-images.githubusercontent.com/44290004/128234437-4fb7ea1d-5d66-4e70-a986-a6270bc5bec3.png)

If I compare with the Wallet amount as known by the network:

![y76q5mp774e71](https://user-images.githubusercontent.com/44290004/128234493-0dc3270f-9856-492a-a5e8-8b39c52d8996.png)

3.Also I can see that the transaction of 1 RVN to binance contains another anormal amount:

![9r6gknic74e71](https://user-images.githubusercontent.com/44290004/128234543-e7964f25-fa55-4208-8a38-7c525b65d6db.png)

I am using Ravencoin version v4.3.2.1-25a2dbf41 (64-bit)

- OS: Windows 10
- CPU: i7 3300
- RAM: 32Go
- Disk size: 2To
- Disk Type (HD/SDD): HD

Transaction Details: ea5dc3eb76fa6b42512a770b3fca2e10bd30e609a47e12cd188288afab23e24f

Did it a second Time: same thing happens !

Second transaction details: f08a6876cccdc2850a4f3107945e8b9af9872ea65edd571a48dde59733942a20

**Comment by Philippe56380** [comment]
This does not happen when transaction >= 10 RVN

**Comment by jeroz1** [comment]
> If I compare with the Wallet amount as known by the network
Your wallet contains 1000 addresses and displays the sum of all holdings. This screenshot only shows 1 out of all your addresses. 

> Also I can see that the transaction of 1 RVN to binance contains another anormal amount
This is normal wallet behavior. It's making use of a change address. An input transaction of 10.05 RVN was used and broken into 1 RVN for Binance, and 9.05 RVN that went into your change address. You also own this change address in your wallet. This is how bitcoin (and thus RVN) works. 

Also see: https://support.bitpay.com/hc/en-us/articles/115003063823-What-is-a-bitcoin-change-address-

**Comment by Philippe56380** [comment]
Ok thanks, I understand now.
