### ISSUE TITLE
RVN wallet

### ISSUE THREAD

**Issue by R0yaLTy1** [RavenProject/Ravencoin#1092]
Hi. I have a question. Which RVN wallet you use to mine? Why you picked this wallet? Thanks for all.

**Comment by Oloxx** [comment]
I use Trust wallet for HODL and Binance to trade

**Comment by TronBlack** [comment]
Ballet Wallet (for offline)
Exodus Wallet for RVN (Desktop or Mobile)

**Comment by TronBlack** [comment]
Ballet Wallet - https://store.balletcrypto.com/products/assorted-cryptocurrency?variant=37826034499747&utm_source=OfficialWebsite&utm_medium=referral&utm_campaign=buypage

Exodus Wallet
https://www.exodus.com/

**Comment by HyperPeek** [comment]
I did a lot of testing with mining on testnet to electrum and node wallet and as long as you do not use hardware backed addresses (Ledger, Trezor) you are fine.
You can transfer every few days (or whatever is suitable) to a hardware wallet address though.

**Comment by fdoving** [comment]
Question answered, closing.
