### ISSUE TITLE
Broken download link on https://ravencoin.org/wcc/  

### ISSUE THREAD

**Issue by Nonprophete** [RavenProject/Ravencoin#1096]
This issue tracker is only for technical issues related to Ravencoin.

General Ravencoin questions and/or support requests and are best directed to the [Ravencoin Discord](https://discord.gg/jn6uhur)).

For reporting security issues, please direct message one of the core developers in discord.

This link is broken on: https://ravencoin.org/wcc/

Download Ravencoin Daemon / Qt
https://raven-nightly-builds.ravencoin.org/

**Comment by fdoving** [comment]
Confirmed.

**Comment by fdoving** [comment]
Wrong issue-tracker: use https://github.com/RavenProject/ravenproject.github.io/issues
