### ISSUE TITLE
Raven ppa doesnt exist

### ISSUE THREAD

**Issue by cgarnier** [RavenProject/Ravencoin#11]
### Describe the issue
In unix-build.md, it recommand to add this ppa ppa:raven/raven, but it doesnt exists.

### Can you reliably reproduce the issue?
add-apt-repository ppa:raven/raven
#### If so, please list the steps to reproduce below:
1.
2.
3.

### Actual behaviour
ppa not found

**Comment by cgarnier** [comment]
the ppa is bitcoin/bitcoin.
Bad search and replace -_-

**Comment by RavenCoinDev** [comment]
Pretty much, I've corrected it. Thanks.

**Comment by cgarnier** [comment]
Change build steps with
```bash
./configure CXXFLAGS="-fPIC" CFLAGS="-fPIC" --enable-cxx
```
Make fail without. (on ubuntu 17.10)
