### ISSUE TITLE
Connecting to peers...

### ISSUE THREAD

**Issue by wolfsden3** [RavenProject/Ravencoin#1101]
Issue:

1. I got some error message about corrupted blocks or something and would I like to rebuild.  I said yes.  This is on Windows 10, the "Raven Core - Wallet".  It's been rebuilding for weeks then I noticed it really hasn't moved from 2 years and 48 weeks behind.
2. I've tried reinstalling over the top (I have the same current version 4.3.2.1), I tried removing the peers.dat file in "C:\Users\%username%\AppData\Roaming\Raven".
3. Nothing seems to work, I've even used tcp view to see if it was getting out and it seems to be.  If I click, help > debug window > I got to "Peers" I see nothing.  Once in a while I'll see something blink in then it disappears.

### Expected behaviour
It was working great for weeks, months even...now I get these errors in my debug log:

2021-10-12 21:35:01 ERROR: invalid header received
2021-10-12 21:35:01 ProcessMessages(headers, 162003 bytes) FAILED peer=80
2021-10-12 21:35:01 receive version message: /Ravencoin:4.3.2.1/: version 70028, blocks=1970227, us=xxx.xxx.xxx.xxx:40226, peer=81

* Note the "us=xxx.xxx.xxx.xxx" is my public IP.  I'm behind a router / firewall with a private 10.0.0.0/24 address

### Actual behaviour
"Connecting to peers..." > errors in the log about invalid header received continually from any number of peers keeps happening.

### Screenshots.
![image](https://user-images.githubusercontent.com/18604147/137032811-fea2eb3b-440a-4fdd-8995-28afc6026184.png)

### What version of Ravencoin are you using?
Version 4.3.2.1

### Machine specs:
- OS: Win 10 pro
- CPU: Intel i5
- RAM: 16 GB
- Disk size: 500 GB
- Disk Type (HD/SDD): HD

### Any extra information that might be useful in the debugging process.

Similar logs:

2021-10-12 21:40:55 receive version message: /Ravencoin:4.3.2.1/: version 70028, blocks=1970232, us=xxx.xxx.xxx.xxx:22310, peer=137
2021-10-12 21:40:56 ERROR: AcceptBlockHeader: block 00000000000048f3a8a70663e44a71f032e847ed2082fb3792c45089888c699f is marked invalid
2021-10-12 21:40:56 ERROR: invalid header received
2021-10-12 21:40:56 ProcessMessages(headers, 162003 bytes) FAILED peer=136
2021-10-12 21:40:56 ERROR: AcceptBlockHeader: block 00000000000048f3a8a70663e44a71f032e847ed2082fb3792c45089888c699f is marked invalid
2021-10-12 21:40:56 ERROR: invalid header received
2021-10-12 21:40:56 ProcessMessages(headers, 162003 bytes) FAILED peer=137

Any help would be appreciated!

Thanks.

**Comment by lsji07** [comment]
Sounds like you have a corrupt block. 

Write down the current stuck block number your node is on and subtract about 1000 from it. Invalidate that block as below. 

Go to help -> debug -> console and run these few commands:

1. getblockhash BLOCKNUMBER - returns stuck block hash for step 2 & 3.
2. invalidateblock stuck-block-hash-from-1 - marks the block as invalid.
3. reconsiderblock stuck-block-hash-from-1 - remove block from your database.
4. clearbanned - clears banned nodes as these probably have the proper chain

Your wallet should start resyncing at that point.

**Comment by wolfsden3** [comment]
Oh!  This was a bit more clear!

https://www.reddit.com/r/Ravencoin/comments/b6z6u3/rvn_qt_wallet_sync_stuck/

I had the right block I just wasn't doing it right.  The system had already invalidated the block.  I needed to do:

invalidateblock 00000000000048f3a8a70663e44a71f032e847ed2082fb3792c45089888c699f
reconsiderblock 00000000000048f3a8a70663e44a71f032e847ed2082fb3792c45089888c699f
clearbanned

...after that it started humming again!

Thanks for the pointers.
