### ISSUE TITLE
No way to use createrawtransaction transferwithmessage RPC. 

### ISSUE THREAD

**Issue by Tylerlhess** [RavenProject/Ravencoin#1102]
https://github.com/RavenProject/Ravencoin/blob/9def8ed6b5aa6f8d6aa3a53436197233941d7e17/src/rpc/rawtransaction.cpp#L983

To enter this block of code you need to have an invalid asset name. I think there is a missing "}" and an indentation error for the remainder of this code block.

**Comment by hans-schmidt** [comment]
Fixed in PR#1113
