### ISSUE TITLE
Fedora 28 x64 Support - compilation parameters ...

### ISSUE THREAD

**Issue by chrysophylax69** [RavenProject/Ravencoin#114]
Hi All ...

RVN Project has provided up to Fedora 27 x64 compiled binaries, but the changes in Fedora 28 x64 are such that the compilation errors out on various areas, depending on the parameters used to compile.

Does anyone have a working parameter list for Fedora 28 x64 so that it can compile successfully?

Thanks.

#crysx

**Comment by TronBlack** [comment]
What are the errors?  Are they compile errors, or linker errors?

**Comment by chrysophylax69** [comment]
Yes Tron ...

There are many - but they are mainly due to the openssl and gcc updates in Fedora 28 x64 - as this OS is bleeding edge and therefore has the latest in these compilation binaries.

I am not at the machine at the moment, but will be later this evening.

Would you like the output, or can you setup a VPS for compilation testing yourself?

For you, I assume it is an easy fix, though this is merely an assumption :)

#crysx

**Comment by underdarkskies** [comment]
@chrysophylax69 can you please test `raven-2.0.1-x86_64-linux-gnu.tar.gz` to see if its compatible with fedora 28, from:
https://github.com/underdarkskies/Ravencoin/releases/tag/v2.0.1

**Comment by fokep** [comment]
This runs on Fedora 28 (syncing blockchain at the moment), did not try older versions. 

`raven-2.0.4-x86_64-linux-gnu.tar.gz`

Using dependencies as described in [/doc/README.md](https://github.com/RavenProject/Ravencoin/blob/master/doc/README.md)

**Comment by blondfrogs** [comment]
Closing this as it seems a solution was found
