### ISSUE TITLE
pool: Original testnet 

### ISSUE THREAD

**Issue by Konstantin35** [RavenProject/Ravencoin#1151]
Will the testnet ever work?
I need to develop a pool,
i used this fork https://github.com/fdoving/Ravencoin in his testnet everything works 100%
but when working with mainnet
An error has occurred
```
2021/12/08 18:58:27 Valid share at height 2051558 349703.7370/105259.4603 from MINER_WALLET:NH@35.***.***.**
2021/12/08 18:58:27 Failed to insert block candidate into backend: unexpected-witness <nil>
```
which was not detected on the testnet 
if the network does not work, is there an alternative check.

**Comment by fdoving** [comment]
This does not look like error messages from Ravencoin.
I suspect your errors are from the mining pool software.

Need more information to be able to help you.

**Comment by Konstantin35** [comment]
yes this is a problem in the pool, I know it in the current case ravend issues when sending blockHex  
`unexpected-witness`
I tried to check on a test and the block is accepted, but in the mainnet it is not accepted

**Comment by Konstantin35** [comment]
there may be a problem with build Coinbase Tx 
I am trying to understand the chronology is there a detailed description

**Comment by fdoving** [comment]
The `unexpected-witness` error is here: 

https://github.com/RavenProject/Ravencoin/blob/3fee4bbf102c5ccbb4040746c94a038b897dcf1c/src/validation.cpp#L4273

**Comment by Konstantin35** [comment]
> 
yes I saw it what is it connected with?

**Comment by Konstantin35** [comment]
Problem solved not enough  `default_witness_commitment`
```
if reply.DefaultWitnessCommitment != "" {
	witnessCommitmentBuf, _ := hex.DecodeString(reply.DefaultWitnessCommitment)
	binary.Write(outBuf, binary.LittleEndian, int64(0))
	outBuf.Write(util.EncodeVarInt(uint64(len(witnessCommitmentBuf))))
	outBuf.Write(witnessCommitmentBuf)
	txOutCount = uint64(2)
}
```
