### ISSUE TITLE
Issue with trezor

### ISSUE THREAD

**Issue by chk777** [RavenProject/Ravencoin#1177]
#### If so, please list the steps to reproduce below:
1. I including the mobile version of the wallet, confirm this process with a trezor (successfully)
2. I'm trying to send coins to another address, the wallet offers to confirm the principal amount and commission with the  trezor (issue) and trezor frozen
3. coins do not go away, but also how to get them out of the wallet, I don’t know 

### Expected behaviour
Tell us what should happen
- coins must go to the desired wallet 

### Actual behaviour
Tell us what happens instead
an error appears (the error code is different every time), the coins do not go out and the trezor freezes 

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.
![Screenshot_1](https://user-images.githubusercontent.com/93346990/148270359-8278b225-08ae-486b-b59a-4b18638d8ee2.png)

### What version of Ravencoin are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.
Electrum Ravencoin 0.4.4

### Machine specs:
- OS:win7
- CPU:i3-3217u
- RAM:4
- Disk size:20gb
- Disk Type (HD/SDD):hdd

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by fdoving** [comment]
Issue reported in the wrong issue-tracker, try this: 
https://github.com/Electrum-RVN-SIG/electrum-ravencoin
