### ISSUE TITLE
Creating new Wallet.dat

### ISSUE THREAD

**Issue by Abderrahman-byte** [RavenProject/Ravencoin#1190]
I am a beginner in the blockchain world, and I just started to understand some basics.
As I understand now ravend and raven-qt are multiwallet softwares.
Is there any rpc method to create new wallet file?

**Comment by jeroz1** [comment]
I recommend reaching out on community forums such as Ravencoin telegram, reddit, or discord to get user help. This section is intended for Ravencoin core code related issues.

**Comment by TronBlack** [comment]
wallet.dat is automatically created by the core software.  Make sure you back it up.

There is an rpc call to get the 12 word backup seed from the command line.  The graphical ui will give it to you to write down.

The community forums are the best place to ask these types of questions.

Discord: https://discord.com/invite/jn6uhur
Telegram: https://t.me/RavencoinDev
https://www.reddit.com/r/Ravencoin/

Closing request.
