### ISSUE TITLE
MonkeVerse NFT

### ISSUE THREAD

**Issue by MonkeVerse** [RavenProject/Ravencoin#1191]
Hi Raven team,

It would be great if we could add RVN as a payment method on Opensea as a trading currency. Is this something we could raise with the platform?

https://opensea.io/collection/monkeverse
https://monkeverse.io/

The launch of Coinbase NFT this year would also be an opportunity to have our currency listed as a option as a payment currency.

Best, Titian

**Comment by jeroz1** [comment]
I do not see how this is an issue for Ravencoin core code.

**Comment by DNS** [comment]
@MonkeVerse  This have nothing to do with Ravencoin core. 
You should ask Opensea guys to add Ravencoin as a new payment method instead.
