### ISSUE TITLE
IPV4 only peers

### ISSUE THREAD

**Issue by edcomrocha** [RavenProject/Ravencoin#1199]
Is there a possibility to have the daemon only connect to IPV4 addresses?

I get many logs saying that it was not possible to connect to an IPV6 peer, due to my machine not having IPV6 addresses available.

`connect() to [2001:9e8:131:1e00:c484:ee6f:298a:99e4]:8767 failed: Network is unreachable (101)`

Thanks!!

Hugs

**Comment by dicklarsson** [comment]
Add the following line to your raven.conf
`onlynet=ipv4`
Or, when starting ravend, add argument `-onlynet=ipv4`

**Comment by edcomrocha** [comment]
> Add the following line to your raven.conf `onlynet=ipv4` Or, when starting ravend, add argument `-onlynet=ipv4`

OK thank you !!
