### ISSUE TITLE
testnet cannot sync

### ISSUE THREAD

**Issue by soql** [RavenProject/Ravencoin#1200]
It stops at 1289761 block :-( I found this site https://testnet.ravencoin.network/network and there is small amount of node - what can I do ?

**Comment by soql** [comment]
Sorry - find that I should use 4.7.0..

**Comment by m4r1m0** [comment]
There is a new testnet version 4.9 here: [](https://github.com/hans-schmidt/Ravencoin/releases/tag/v4.9.0test1)

This includes the bug fix for P2SH on restricted assets/qualifiers.
