### ISSUE TITLE
Ravencoin testnet Status

### ISSUE THREAD

**Issue by kylehagin** [RavenProject/Ravencoin#1208]
### Describe the issue

Testnet stuck at 57% on block 713630.  I loaded the last two releases and was unable to fully sync.  I am sure I am missing something.  What is the best way to use the testnet? Is the testnet still supported?

### Can you reliably reproduce the issue?
Yes
#### If so, please list the steps to reproduce below:
1. Download binaries
2. execute ./raven-qt -testnet
3. takes several days to get to block 713630 and stops.

### Expected behaviour
Tell us what should happen

I am assuming it should load to completion and allow transaction on the test network.

### Actual behaviour
Tell us what happens instead

Stops syncing and loading blocks at 713630

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of Ravencoin are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.

4.6.1
4.3.2.1
forked 4.7

**Comment by kylehagin** [comment]
I am currently trying [v4.9.0test1](https://github.com/hans-schmidt/Ravencoin/releases/tag/v4.9.0test1) It does seem to be loading much quicker. Is this the best testnet to use?  

Also, as a side note this version says it is for the testnet only. I tried running ./ravencoin-qt and it did not work well. It still requires ./ravencoin-qt -testnet to run properly.

**Comment by lsji07** [comment]
Hi @kylehagin 

Testnet is a bit of a mess at the moment with testing different aspects of P2SH and software versions.

As per the dev meeting last night, testnet is changing.

This is to get everyone using the same code again. 

Ideally switch to using v4.6.1 on testnet and let things stabilize. In the short term this will be unstable. 

The previous higher versioned numbers (above 4.6.1) have been useful to test out features of P2SH for assets. 

A new binary (with p2sh related code) can be released onto testnet first and mainnet second at a later date. Whenever the community feels a mainnet fork is warranted.

The adjustment longer term is to also allow us to test the complete future longer BIP9 progress on testnet 4.6.1 along with P2SH. A dry run if you will.
