### ISSUE TITLE
Issue with getaddressbalance

### ISSUE THREAD

**Issue by lsji07** [RavenProject/Ravencoin#1233]
Found this issue on testnet.

![image](https://github.com/RavenProject/Ravencoin/assets/39772657/31384548-6688-4257-977a-349a7e9f0936)

```
16:01:38
￼
getaddressbalance muYAnkJef4CbHRst1uf1ybh5AQmAa875hN


16:01:38
￼
Error: Error parsing JSON:muYAnkJef4CbHRst1uf1ybh5AQmAa875hN
```

### Expected behaviour
Ideally the address balances should show. Including asset balances if possible.

I found this on Raven Core version v4.6.1 (64-bit) on a windows install.

**Comment by dicklarsson** [comment]
Wrong syntax.
The first parameter should be an object with property addresses, like this
`raven-cli getaddressbalance '{"addresses": ["mo9tHyULPSiJV9xbYUQSRmU1yEqKWjbdkJ"]}' `

**Comment by lsji07** [comment]
Thank you! Issue closed.
