### ISSUE TITLE
Should Main Assets be able to start with #?

### ISSUE THREAD

**Issue by lsji07** [RavenProject/Ravencoin#1234]
I found the below asset names as a sample. Is this acceptable? 

```#7B97529B8BBA575B
#BAFEKYC
#CLUB/#SUANLI.IO
#PAALFUNDINVESTCYCLE
#PUB.UK
#RPG/#PIONEER
#SYSTEM/#GALAXY
```
I would have thought that the # symbol is not allowed as it is used to represent unique assets under main or sub assets? Using it to start main asset names and unique assets can lead to confusion.

### Expected behaviour
```#``` should not be allowed to start a main asset name.

### Actual behaviour
Main assets can start with ```#```.

**Comment by kralverde** [comment]
Those are qualifier assets

**Comment by lsji07** [comment]
I forgot because I do not use qualifier assets that much. Thanks for the reminder! Closed.
