### ISSUE TITLE
Ravend Header / Block data doesn't persist between restarts

### ISSUE THREAD

**Issue by crypto-billy** [RavenProject/Ravencoin#1237]
### Describe the issue
I've started `ravend` and it took roughly 6 hours to download all headers and blocks, after which the server is perfectly functional giving me latest blocks and transactions upon my API requests. However every time I restart the process ravend resyncs from the beginning all over again, and it takes roughly the same amount of time to finish re-downloading headers and blocks before catching up to block tip.

Is this expected behavior or did I miss some configuration that alters this behavior?

I'm starting the node with these flags:

```bash
/raven/src/ravend \
  -printtoconsole \
  -debug=1 \
  -persistmempool \
  -conf=/opt/blockchain/ravencoin/raven.conf
```

And here's the `raven.conf` I'm using:
```conf
testnet=0
regtest=0

txindex=1
reindex=1

externalip=***

server=1
apiport=37223
apiuri=http://0.0.0.0
rpcallowip=0.0.0.0/0
rpcbind=0.0.0.0
rpccontenttype=application/json; charset=utf-8
rpcuser=***
rpcpassword=***
```

### Can you reliably reproduce the issue?
Yes, simply by restarting the node with above configuration and flags.

### Expected behaviour
I expect the header and block data to persist between restart of the process.

### Actual behaviour
Header and block data does NOT persist between restarts.

### What version of Ravencoin are you using?
Self compiled built off of tag `v4.6.1` (` 7864c39`)

### Machine specs:
- OS: ubuntu

### Any extra information that might be useful in the debugging process.
Please let me know if this helps, I can provide this as needed.

**Comment by dicklarsson** [comment]
Never ever seen that behaviour on Ubuntu or any other OS.
After restart, it can do some re-syncing/checking some blocks, but that should take seconds.

**Comment by corviato1** [comment]
@crypto-billy once you have ravend open, and it's at full sync, go into the config and comment out reindex=1

**Comment by crypto-billy** [comment]
@corviato1 Works like a charm, with `reindex=1` commented out it no longer resync the entire chain on restarts.
Thanks for the help 😄
