### ISSUE TITLE
What kind of death are you?

### ISSUE THREAD

**Issue by ShadoWhite369** [RavenProject/Ravencoin#1249]
Yes, I know that I have to go to the middle of the Discord community to say these things, so I see a problem in the inactive community of developers..
With all the hard work you developers put in, I really wonder why we are so far behind other projects.
Unfortunately, I don't know how to code, but I was so interested in this project since the fork and the separation of Raven from Bit, that in the same year, I spent all my assets on buying a graphic card and building a rig miner, despite the ban in my country.
My words may not be valuable to any of your community members, but they were so important to me that despite a thousand and one problems, I became a member here just to bring Saddam to you.
You live in countries with minimal economic inflation, but I fully supported my favorite RVN coin in a country that has more inflation than Venezuela, but it is not officially announced..
I just want you to know that people like me who buy equipment to set up a complete node in such countries with 4-digit inflation are not crazy, nor are they looking for such returns.
If I wasn't a true fan and I wasn't looking to increase Raven's security, I certainly wouldn't have spent the money to buy equipment 5 years ago.
Instead, I would directly buy the same few thousand dollars from the Raven Coin exchange and hodl.
But I didn't do it because I thought that the RavenCoin community would indirectly support me with the progress of the project.
Why after all these years I suffered and the police confiscated all the mine equipment I had done

But newer projects in this field are better known! Why?
Why, when I enter the rvn website, after all these years, it still does not have a list of powerful partners؟
Why should unknown currencies come out of nowhere and be seen in the (rwa) domain, while RVN years ago was capable of doing what these projects claim to do today, but today it is still unknown.!
I lost my whole life because everyone around me says that even if the police didn't catch you and confiscate your equipment, the currency you chose wouldn't have brought you any results.🤐
I mentioned at the beginning that I don't have expertise in coding, but why don't you go along with Bitcoin like Ethereum layer 2, which is also famous for helping Ethereum, and fill up btc.
Now that you have a common core, why don't you proceed with btc instead of that ridiculous network (Ordinals) in the direction of NFT or tokenizing real estate around the world and selling it both collectively and individually under the flag of BTC🤯💯💲
Why not seek strategic benefits with the BTC community!
btc is like money, you can use it to buy a private plane, a private ship, a private property, a private car and any other goods(high acceptance in addition to being anti-inflation).
Now, with all definitions, Bitcoin has limitations, unlike Ravencoin،Why shouldn't this capacity of Raven Coin (RWA NFT operating system) be used next to Bitcoin to eliminate all competitors in the future?🤔
I may not be an expert in the field of programming, but because of my difficult lifestyle, I know what awaits us in 2025-2042( The most unprecedented international economic inflation since World War until today ).
This is the best opportunity for the crypto market to be notified if a rally happens before the downturn becomes official.I'm sorry if the verbs were difficult, unfortunately, I don't speak English well, so I got help from Google
That's why even though I have a lot of bad ideas in my head, I can't convey them...
I am afraid that there will be a wrong impression about my speech, otherwise I really badly needed help and gifts from the Raven Coin community.Although the Raven community may not be here, from my point of view, everyone who has somehow participated in the survival of Raven Coin is considered the Raven Coin family.
I don't leave any address from my digital wallet( So that there is no wrong judgment about my speech).
Yes, although I really need the help of each member of the Raven Coin family, I do not leave an address from my digital wallet.So that I can tell the truth without being accused.
You know that every country has its own currency and the value of the currency of all countries is measured against the dollar..
A few years ago, in my country, every 1 US dollar was worth about eighteen thousand tomans in my country's money

At that time, not too long ago, I spent $6,666 on mining equipment and Full Node under Gamement( Yes, you could connect all the graphics cards together and start extracting،But the high electricity consumption must have an explanation because at that time mining was considered illegal ،The solution was Gamenet coverage, which required a PC with graphics).
Now, let's skip the details, we paid a lot of money for electricity, we had a lot of side costs, while we didn't know that we weren't going to see the fruits of our labor،Because we took everything we had and didn't have, and finally we were sent to court, and since we were accused, we paid a fine of 6666 dollars for many years of mining.
Because the court assumed that we have a lot of history of mining and so called our own burden, so we have to pay for the wealth we earned( But the truth was that I was mining for no more than six months).

The painful point of this trend is that in my country the growth of inflation is high, which means that I have to spend a hundred times more just to get the same things that I lost( Because I am publishing this text today, every 1 dollar is 60,000 thousand tomans in our money, while I lost my life at the price of 18,000 thousand tomans for every 1 dollar ).
I wish you could help me.
I don't know, maybe if I had given an address from my wallet, people would have helped me, the truth is that I don't even have an active wallet anymore because I lost everything I had, so if I wanted to give the address of my wallet, I would have to start building it again...
So instead of downloading a wallet application today and activating a personal address from myself and waiting for someone to help, I leave everything to time🙏

**Comment by dicklarsson** [comment]
Sir, many people believe in the potential of Ravencoin and invest considerable effort into developing its ecosystem. 
We hope to see more core development in the future.

**Comment by corviato1** [comment]
That is a long comment with many points.  Going to close as it is not relative to GitHub code issues.  Maybe best to share your frustrations on a social media site.  Here is a link: https://ravencoin.org/community/
