### ISSUE TITLE
Version v0.15.99.0 not working on MacOS  High Sierra 10.13.5

### ISSUE THREAD

**Issue by yrrv1980** [RavenProject/Ravencoin#129]
Hi, 

   When I try to instal the wallet I get the message "image data corrupted"  

<img width="386" alt="screen shot 2018-07-14 at 10 07 19 am" src="https://user-images.githubusercontent.com/17753975/42725708-f1d2dc22-874d-11e8-9a61-82c1e3324279.png">

I'm trying with a Macbook

3.3 GHz Intel Core i7
16 GB 
1TB HDD

Thanks!

**Comment by TronBlack** [comment]
Download dmg from: 
https://github.com/RavenProject/Ravencoin/releases/tag/v0.15.99.0

Make sure you've downloaded the entire 23.2 MB.
