### ISSUE TITLE
What is the best Ravecoin wallet and where do I download it?

### ISSUE THREAD

**Issue by joe1950** [RavenProject/Ravencoin#130]
This issue tracker is only for technical issues related to bitcoin-core.

General bitcoin questions and/or support requests and are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).

For reporting security issues, please read instructions at [https://bitcoincore.org/en/contact/](https://bitcoincore.org/en/contact/).

#### If so, please list the steps to reproduce below:
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of bitcoin-core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.

### Machine specs:
- OS:
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SDD):

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by russkidooski** [comment]
There is only 2 wallets that i know of: https://github.com/RavenProject/Ravencoin/releases and under's extended rpc wallet: https://github.com/underdarkskies/Ravencoin-extended

**Comment by TronBlack** [comment]
"Best" is subjective.  We're working on the reference client which is "pretty good"

Download here for your platform:
https://github.com/RavenProject/Ravencoin/releases

Public Service Announcement:
Always make sure you're downloading wallets from a safe and trusted source!

We will move develop to master and make the new asset-aware binaries available on July 30th.
