### ISSUE TITLE
Can't run Windows client on testnet.

### ISSUE THREAD

**Issue by Thread7** [RavenProject/Ravencoin#15]
I get an error when trying raven-qt.exe -testnet on Windows 10 64-bit.  Says "Error: A fatal internal error occurred....."
 It says "...see debug.log for details."  Yet nothing gets written to debug.log.

**Comment by Thread7** [comment]
Anyone out there?  This is certainly a bug.

**Comment by MSFTserver** [comment]
testnet should be up and running now

**Comment by RavenCoinDev** [comment]
Testnet is live.
