### ISSUE TITLE
Daemon Runs at too High CPU Utilization

### ISSUE THREAD

**Issue by aaron907m** [RavenProject/Ravencoin#16]
I compiled and now run the daemon on my Ubuntu server.  But it is always running at near 99% CPU utilization.  Meanwhile my litecoin daemon averages maybe 7%.  Please fix or tell me what is wrong.

**Comment by Thread7** [comment]
Yes, mine runs super high also.  I had to dedicate a machine just for Raven.  Not very practical for the general public however.

**Comment by MSFTserver** [comment]
psssst open the console and try `setgenerate true 0` to disable the built in miner

**Comment by aaron907m** [comment]
Thanks.  I seems like someone from the dev team could have answered that 8 days ago.  Do they even check the issues in their own repo?

**Comment by MSFTserver** [comment]
they've been pretty busy getting all This core stuff together and in order...ill probably be jumping into helping around the issues section more often since I noticed they aren't super active here yet

**Comment by aaron907m** [comment]
Are you part of the dev team?  If so, that is great that they have designated someone to interact with the development community.  But if not, it doesn't give me confidence in this coin that they don't even take the time to become aware of the external development problems we face.

**Comment by MSFTserver** [comment]
unfortunately no I'm not apart of the core but i am apart of the community team we are slowly putting together as the community grows

**Comment by MSFTserver** [comment]
I'm sure they look over stuff they usually post updates in the discord and telegram of the issues they are working on...ill definatly bring it up that we need to be more proactive here even though we just launched

**Comment by RavenCoinDev** [comment]
ravend and raven-qt will mine with a single core.  CPU mining has largely been replaced by GPU mining.  We will default the CPU mining to off after the network consistently exceeds 200 GH/s

**Comment by RavenCoinDev** [comment]
To turn off mining for cli:
raven-cli setgenerate false

To turn off mining for qt, go to the Debug console and type:
setgenerate false

**Comment by BarneyChambers** [comment]
I tried raven-cli setgenerate false AND raven-cli setgenerate true 0 and still I am running at 100% CPU capacity... what gives?

**Comment by bedri** [comment]
Try
```

setgenerate false 0

```

**Comment by BarneyChambers** [comment]
For me it was because it was resyncing to the blockchain after I restarted my server. Really annoying that it uses ALL of your cpu, I had to throttle it manually.
