### ISSUE TITLE
New Ravencore Wallet MacOS issue

### ISSUE THREAD

**Issue by cimpro** [RavenProject/Ravencoin#174]
// Problem: the wallet crashes directly after launch.

﻿// This is a copy paste of the MacOS problem report:

Process:               Raven-Qt [3221]
Path:                  /Applications/Raven-Qt.app/Contents/MacOS/Raven-Qt
Identifier:            org.ravenfoundation.Raven-Qt
Version:               2.0.1 (2.0.1)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Raven-Qt [3221]
User ID:               501

Date/Time:             2018-08-01 01:19:40.677 +0100
OS Version:            Mac OS X 10.13.6 (17G65)
Report Version:        12
Bridge OS Version:     3.0 (14Y664)
Anonymous UUID:        -----

Sleep/Wake UUID:       -----

Time Awake Since Boot: 44000 seconds
Time Since Wake:       12000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @loader_path/libboost_system-mt.dylib
  Referenced from: /Applications/Raven-Qt.app/Contents/Frameworks/libboost_thread-mt.dylib
  Reason: image not found

Binary Images:
       0x105917000 -        0x107003ff7 +org.ravenfoundation.Raven-Qt (2.0.1 - 2.0.1) <AC02E2CA-2F7B-3725-9017-A2DB8AC12A76> /Applications/Raven-Qt.app/Contents/MacOS/Raven-Qt
       0x107746000 -        0x10779dff7 +libzmq.5.dylib (0) <177948E4-6B87-3FB4-8E9F-2501F466E7B7> /Applications/Raven-Qt.app/Contents/Frameworks/libzmq.5.dylib
       0x1077b2000 -        0x1077b4ff7 +libboost_system.dylib (0) <6D4202B3-758D-3014-A208-8577024B9BB3> /Applications/Raven-Qt.app/Contents/Frameworks/libboost_system.dylib
       0x1077bb000 -        0x1077caff7 +libboost_filesystem.dylib (0) <BDEC6C74-6778-342E-AFF0-62ABA7D03E43> /Applications/Raven-Qt.app/Contents/Frameworks/libboost_filesystem.dylib
       0x1077d9000 -        0x10780bfff +libboost_program_options-mt.dylib (0) <AEDAEFBB-E939-3404-BD07-2313425473FA> /Applications/Raven-Qt.app/Contents/Frameworks/libboost_program_options-mt.dylib
       0x10782d000 -        0x10783afff +libboost_thread-mt.dylib (0) <CE22F73C-D5EA-32D9-A732-D824D54D622C> /Applications/Raven-Qt.app/Contents/Frameworks/libboost_thread-mt.dylib
       0x107847000 -        0x10784aff7 +libboost_chrono-mt.dylib (0) <19312DE7-D906-321B-9A48-5822E962A2EB> /Applications/Raven-Qt.app/Contents/Frameworks/libboost_chrono-mt.dylib
       0x10784f000 -        0x107955ffb +QtNetwork (0) <57397F00-822E-3CDA-8AEC-8AC9A76A54A3> /Applications/Raven-Qt.app/Contents/Frameworks/QtNetwork.framework/Versions/5/QtNetwork
       0x10799f000 -        0x107de2ff3 +QtWidgets (0) <BBDD05ED-151D-3EA8-81E2-221E50E3A62E> /Applications/Raven-Qt.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets
       0x107f49000 -        0x10837efef +QtGui (0) <1136D8AD-19A9-3CF8-935F-6B2C0023112C> /Applications/Raven-Qt.app/Contents/Frameworks/QtGui.framework/Versions/5/QtGui
       0x10847b000 -        0x10896eff7 +QtCore (0) <4F05320A-6BB4-3F3E-898E-2C61ACB9BC56> /Applications/Raven-Qt.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore
       0x108a2a000 -        0x108a8affb +QtDBus (0) <B27BC835-E3F9-3AB7-8D6B-338765BC2698> /Applications/Raven-Qt.app/Contents/Frameworks/QtDBus.framework/Versions/5/QtDBus
       0x108aa8000 -        0x108aaeffb +libqrencode.4.dylib (0) <F220D5C1-55B9-325F-B753-ED3FF956F439> /Applications/Raven-Qt.app/Contents/Frameworks/libqrencode.4.dylib
       0x108ab8000 -        0x108be2ff3 +libprotobuf.16.dylib (0) <430E7C4E-08C7-351B-9392-823C2791C091> /Applications/Raven-Qt.app/Contents/Frameworks/libprotobuf.16.dylib
       0x108c99000 -        0x108dbdff7 +libdb_cxx-4.8.dylib (0) <1A33B5EB-E9B6-369B-9999-F1187ABFFE2F> /Applications/Raven-Qt.app/Contents/Frameworks/libdb_cxx-4.8.dylib
       0x108df8000 -        0x108e37fff +libssl.1.0.0.dylib (0) <4D343D8E-B72A-38BD-9204-CC0354C0B7F8> /Applications/Raven-Qt.app/Contents/Frameworks/libssl.1.0.0.dylib
       0x108e5a000 -        0x108fcad67 +libcrypto.1.0.0.dylib (0) <4A0A66FE-A6B9-387F-B265-512C91DF46F9> /Applications/Raven-Qt.app/Contents/Frameworks/libcrypto.1.0.0.dylib
       0x109039000 -        0x109041ffb +libminiupnpc.17.dylib (0) <D83B2C71-0CFC-3324-92DC-ACD64DF63142> /Applications/Raven-Qt.app/Contents/Frameworks/libminiupnpc.17.dylib
       0x10904a000 -        0x10904bfff +libevent_pthreads-2.1.6.dylib (0) <6F618640-46F3-3B56-A22C-26941B4D8790> /Applications/Raven-Qt.app/Contents/Frameworks/libevent_pthreads-2.1.6.dylib
       0x109055000 -        0x109082fff +libevent-2.1.6.dylib (0) <891F379E-D5F9-39EB-BECA-2E24F943B7B3> /Applications/Raven-Qt.app/Contents/Frameworks/libevent-2.1.6.dylib
       0x114580000 -        0x1145caacf  dyld (551.4) <8A72DE9C-A136-3506-AA02-4BA2B82DCAF3> /usr/lib/dyld
    0x7fff35817000 -     0x7fff36675fff  com.apple.AppKit (6.9 - 1561.60.100) <3C27CF6F-E640-3411-A87D-CCB2222CC754> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff366c7000 -     0x7fff366c7fff  com.apple.ApplicationServices (48 - 50) <AFFBD94A-AF76-336E-B53E-57524EAE8EF3> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices
    0x7fff38238000 -     0x7fff386d9fef  com.apple.CoreFoundation (6.9 - 1454.90) <E5D594BF-9142-3325-A62D-CF4AAF472642> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff393b1000 -     0x7fff393b1fff  com.apple.CoreServices (822.36 - 822.36) <C8368F17-1589-3BA5-A0E7-89CB8DF2454F> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
    0x7fff3a399000 -     0x7fff3a75ffff  com.apple.Foundation (6.9 - 1454.90) <8EA924F3-ADAE-3F4B-8482-8B11C027D9A5> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff5d8d9000 -     0x7fff5d90cff7  libclosured.dylib (551.4) <3FB6B209-51F4-38DA-B1D8-2EE29D5BDD83> /usr/lib/closure/libclosured.dylib
    0x7fff5de13000 -     0x7fff5de14ffb  libSystem.B.dylib (1252.50.4) <CD555F3B-FDDB-35E5-A2FB-FBBF3D62031A> /usr/lib/libSystem.B.dylib
    0x7fff5e048000 -     0x7fff5e09efff  libc++.1.dylib (400.9) <7D3DACCC-3804-393C-ABC1-1A580FD00CB6> /usr/lib/libc++.1.dylib
    0x7fff5e09f000 -     0x7fff5e0c3ff7  libc++abi.dylib (400.8.2) <EF5E37D7-11D9-3530-BE45-B986612D13E2> /usr/lib/libc++abi.dylib
    0x7fff5f4cc000 -     0x7fff5f8ba7e7  libobjc.A.dylib (723) <DD9E5EC5-B507-3249-B700-93433E2D5EDF> /usr/lib/libobjc.A.dylib
    0x7fff5ff90000 -     0x7fff5ff94ff7  libcache.dylib (80) <092479CB-1008-3A83-BECF-E115F24D13C1> /usr/lib/system/libcache.dylib
    0x7fff5ff95000 -     0x7fff5ff9fff3  libcommonCrypto.dylib (60118.50.1) <029F5985-9B6E-3DCB-9B96-FD007678C6A7> /usr/lib/system/libcommonCrypto.dylib
    0x7fff5ffa0000 -     0x7fff5ffa7fff  libcompiler_rt.dylib (62) <968B8E3F-3681-3230-9D78-BB8732024F6E> /usr/lib/system/libcompiler_rt.dylib
    0x7fff5ffa8000 -     0x7fff5ffb1ffb  libcopyfile.dylib (146.50.5) <3885083D-50D8-3EEC-B481-B2E605180D7F> /usr/lib/system/libcopyfile.dylib
    0x7fff5ffb2000 -     0x7fff60037fff  libcorecrypto.dylib (562.70.1) <5C26364F-2269-31EC-84AF-0FED2C902E38> /usr/lib/system/libcorecrypto.dylib
    0x7fff600bf000 -     0x7fff600f8ff7  libdispatch.dylib (913.60.2) <232C69BD-022E-3AB9-8807-79F9FA7CB5EC> /usr/lib/system/libdispatch.dylib
    0x7fff600f9000 -     0x7fff60116ff7  libdyld.dylib (551.4) <81BF3A82-5719-3B54-ABA9-76C82D932CAC> /usr/lib/system/libdyld.dylib
    0x7fff60117000 -     0x7fff60117ffb  libkeymgr.dylib (28) <E34E283E-90FA-3C59-B48E-1277CDB9CDCE> /usr/lib/system/libkeymgr.dylib
    0x7fff60125000 -     0x7fff60125ff7  liblaunch.dylib (1205.70.9) <B184B521-FF24-3142-AFAF-23D170CF918C> /usr/lib/system/liblaunch.dylib
    0x7fff60126000 -     0x7fff6012affb  libmacho.dylib (906) <1902A611-081A-3452-B11E-EBD1B166E831> /usr/lib/system/libmacho.dylib
    0x7fff6012b000 -     0x7fff6012dff3  libquarantine.dylib (86) <26C0BA22-8F93-3A07-9A4E-C8D53D2CE42E> /usr/lib/system/libquarantine.dylib
    0x7fff6012e000 -     0x7fff6012fff3  libremovefile.dylib (45) <711E18B2-5BBE-3211-A916-56740C27D17A> /usr/lib/system/libremovefile.dylib
    0x7fff60130000 -     0x7fff60147fff  libsystem_asl.dylib (356.70.1) <39E46A6F-B228-3E78-B83E-1779F9707A39> /usr/lib/system/libsystem_asl.dylib
    0x7fff60148000 -     0x7fff60148fff  libsystem_blocks.dylib (67) <17303FDF-0D2D-3963-B05E-B4DF63052D47> /usr/lib/system/libsystem_blocks.dylib
    0x7fff60149000 -     0x7fff601d2ff7  libsystem_c.dylib (1244.50.9) <1187BFE8-4576-3247-8177-481554E1F9E7> /usr/lib/system/libsystem_c.dylib
    0x7fff601d3000 -     0x7fff601d6ffb  libsystem_configuration.dylib (963.50.8) <DF6B5287-203E-30CB-9947-78DF446C72B8> /usr/lib/system/libsystem_configuration.dylib
    0x7fff601d7000 -     0x7fff601daffb  libsystem_coreservices.dylib (51) <486000D3-D8CB-3BE7-8EE5-8BF380DE6DF7> /usr/lib/system/libsystem_coreservices.dylib
    0x7fff601db000 -     0x7fff601dcfff  libsystem_darwin.dylib (1244.50.9) <09C21A4A-9EE0-388B-A9D9-DFF8F6758791> /usr/lib/system/libsystem_darwin.dylib
    0x7fff601dd000 -     0x7fff601e3ff7  libsystem_dnssd.dylib (878.70.2) <3290768B-54DE-3AB6-B155-AC0950AC5564> /usr/lib/system/libsystem_dnssd.dylib
    0x7fff601e4000 -     0x7fff6022dff7  libsystem_info.dylib (517.30.1) <AB634A98-B8AA-3804-8436-38261FC8EC4D> /usr/lib/system/libsystem_info.dylib
    0x7fff6022e000 -     0x7fff60254ff7  libsystem_kernel.dylib (4570.71.2) <F22B8D73-69D8-36D7-BF66-7F9AC70C08C2> /usr/lib/system/libsystem_kernel.dylib
    0x7fff60255000 -     0x7fff602a0fcb  libsystem_m.dylib (3147.50.1) <8CFB51C9-B422-3379-8552-064C63943A23> /usr/lib/system/libsystem_m.dylib
    0x7fff602a1000 -     0x7fff602c0fff  libsystem_malloc.dylib (140.50.6) <7FD43735-9DDD-300E-8C4A-F909A74BDF49> /usr/lib/system/libsystem_malloc.dylib
    0x7fff602c1000 -     0x7fff603f1ff7  libsystem_network.dylib (1229.70.2) <5E86B2DE-9E15-3354-8714-4094ED5F698D> /usr/lib/system/libsystem_network.dylib
    0x7fff603f2000 -     0x7fff603fcffb  libsystem_networkextension.dylib (767.70.1) <D23EAFC1-E8BD-34D5-969C-6E45A1C3B4E4> /usr/lib/system/libsystem_networkextension.dylib
    0x7fff603fd000 -     0x7fff60406ff3  libsystem_notify.dylib (172) <08012EC0-2CD2-34BE-BF93-E7F56491299A> /usr/lib/system/libsystem_notify.dylib
    0x7fff60407000 -     0x7fff6040eff7  libsystem_platform.dylib (161.50.1) <6355EE2D-5456-3CA8-A227-B96E8F1E2AF8> /usr/lib/system/libsystem_platform.dylib
    0x7fff6040f000 -     0x7fff6041afff  libsystem_pthread.dylib (301.50.1) <0E51CCBA-91F2-34E1-BF2A-FEEFD3D321E4> /usr/lib/system/libsystem_pthread.dylib
    0x7fff6041b000 -     0x7fff6041efff  libsystem_sandbox.dylib (765.70.1) <553DFCC6-9D31-3B9C-AB7C-30F6F265786D> /usr/lib/system/libsystem_sandbox.dylib
    0x7fff6041f000 -     0x7fff60420ff3  libsystem_secinit.dylib (30) <DE8D14E8-A276-3FF8-AE13-77F7040F33C1> /usr/lib/system/libsystem_secinit.dylib
    0x7fff60421000 -     0x7fff60428ff7  libsystem_symptoms.dylib (820.60.2) <585BDFA2-D54D-39D0-8046-44E824DABD43> /usr/lib/system/libsystem_symptoms.dylib
    0x7fff60429000 -     0x7fff6043cfff  libsystem_trace.dylib (829.70.1) <3A6CB706-8CA6-3616-8AFC-14AAD7FAF187> /usr/lib/system/libsystem_trace.dylib
    0x7fff6043e000 -     0x7fff60443ff7  libunwind.dylib (35.3) <BEF3FB49-5604-3B5F-82B5-332B80023AC3> /usr/lib/system/libunwind.dylib
    0x7fff60444000 -     0x7fff60471ff7  libxpc.dylib (1205.70.9) <0BC7AD67-671D-31D4-8B88-C317B8379598> /usr/lib/system/libxpc.dylib

Model: MacBookPro14,2, BootROM MBP142.0178.B00, 2 processors, Intel Core i5, 3,1 GHz, 8 GB, SMC 2.44f1
Graphics: Intel Iris Plus Graphics 650, Intel Iris Plus Graphics 650, Built-In
Memory Module: BANK 0/DIMM0, 4 GB, LPDDR3, 2133 MHz, 0x80CE, 0x4B3445364533303445422D45474347202020
Memory Module: BANK 1/DIMM0, 4 GB, LPDDR3, 2133 MHz, 0x80CE, 0x4B3445364533303445422D45474347202020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x171), Broadcom BCM43xx 1.0 (7.77.37.31.1a9)
Bluetooth: Version 6.0.7f10, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB 3.0 Bus
USB Device: Yubikey 4 OTP+U2F+CCID
USB Device: iBridge
Thunderbolt Bus: MacBook Pro, Apple Inc., 33.1
Thunderbolt Bus: MacBook Pro, Apple Inc., 33.1

**Comment by underdarkskies** [comment]
until core releases statically built dmg's from the new build process, you can test 
`raven-2.0.1-osx-unsigned.dmg` from

https://github.com/underdarkskies/Ravencoin/releases/tag/v2.0.1

I compiled these with a new build process which alleviates this issue.

**Comment by TronBlack** [comment]
Future binaries will use a derivative of Under's build process.   It should fix the problem.

Thank you Under!

Closing this issue.  Please re-open if it still happens after the v2.0.2 release.
