### ISSUE TITLE
gui client select asset to send missing after creating asset

### ISSUE THREAD

**Issue by underdarkskies** [RavenProject/Ravencoin#176]
after creating an asset, i had to restart qt gui clinet to be able to select it from the send assets drop down menu.
![image](https://user-images.githubusercontent.com/35243703/43541526-9fc3be34-9598-11e8-952a-48154b7c33e0.png)

**Comment by blondfrogs** [comment]
@underdarkskies 
After a new asset is created. You will need to click the refresh button on the GUI into to see it.

**Comment by blondfrogs** [comment]
@underdarkskies Let me know if this fixes the problem, and I can close this issue.

**Comment by blondfrogs** [comment]
@underdarkskies Can I close this issue?

**Comment by underdarkskies** [comment]
Ideally ui would not need a refresh button
