### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by underdarkskies** [RavenProject/Ravencoin#179]
expand coin control when on the assets tab to show addresses asset and asset balance

**Comment by russkidooski** [comment]
+1 its tiring after a while scrolling through a small box when you have 200+ assets.

**Comment by blondfrogs** [comment]
Yeah. This is planned in the future.

**Comment by blondfrogs** [comment]
@underdarkskies @russkidooski Fixed with #253 
The list of assets in the dropdowns will still be large if you have lots of different asset names.
