### ISSUE TITLE
libdb4.8 is old

### ISSUE THREAD

**Issue by whbdupree** [RavenProject/Ravencoin#18]
I am trying to build on Ubuntu 16.04, which is the current LTS. My built in libdb is 5.3, but RavenCoin wants version 4.8. Is 5.3 compatible? Is it possible to update this dependency, since most linux users are going to have a problem with it?

**Comment by Ondalf** [comment]
This will break wallet.dat portability. So to build on Ubuntu, use [bitcoin-ppa](https://launchpad.net/~bitcoin/+archive/ubuntu/bitcoin) and install libdb4.8-dev and libdb4.8++-dev from there.
