### ISSUE TITLE
Raven-QT cannot open because of a problem MAC High Sierra 10.13.6

### ISSUE THREAD

**Issue by yrrv1980** [RavenProject/Ravencoin#181]
Hi, here is the report I pulled from the issue: 

 
[RavenQt issue.pdf](https://github.com/RavenProject/Ravencoin/files/2253435/RavenQt.issue.pdf)
 
I hope this helps
thanks

**Comment by spyder46n2** [comment]
It looks like you might not have the 'boost' library installed on your machine.  
There are a couple of ways to resolve this.  If you have Homebrew installed you can open the terminal app and run the command:
`brew install boost`

If that command doesn't work, open a _Finder_ window and navigate to the _Applications_ directory.  Find the Raven app that was installed, right-click on it and choose _Show Package Contents_.  In the _Contents_ directory, open the _Frameworks_ directory.  Find a file called libboost_system.dylib, select the file and click the _command+C_ keys, then the _Command+V_ keys.  At the bottom of the _Contents_ directory, you should now have a copy of the libboost_system.dylib file.  Right click and rename the file to be _libboost_system-mt.dylib_.  Then simply drag and drop the new file into the _Frameworks_ directory.

Hopefully this is the issue.  Please post a new comment and let us know if this resolves the issue...

**Comment by spyder46n2** [comment]
It also looks like @underDarkSkies has compiled an installer for OSX that resolves this issue.  You can pull his DMG down and install it here:
https://github.com/underdarkskies/Ravencoin/releases/tag/v2.0.1

**Comment by yrrv1980** [comment]
Thanks ! really appreciate the help, I was able to make it work with the Installer.

**Comment by TronBlack** [comment]
I'm going to leave this here for now because it provides the solution.   We will be building new 2.0.2 binaries that should work on High Sierra.

**Comment by gaetan29** [comment]
Hi,
I have a similar issue with latest built Raven-2.0.3-osx.dmg ... running on OSX 10.13.6.


Error Report:
Process:               Raven-Qt [29746]
Path:                  /Applications/Coins/Raven-Qt.app/Contents/MacOS/Raven-Qt
Identifier:            org.ravenfoundation.Raven-Qt
Version:               2.0.3 (2.0.3)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Raven-Qt [29746]
User ID:               501

Date/Time:             2018-08-15 10:25:23.741 +0200
OS Version:            Mac OS X 10.13.6 (17G65)
Report Version:        12
Bridge OS Version:     3.0 (14Y664)
Anonymous UUID:        1A9D007D-4F90-6AEF-F3B2-8A96739E6014

Sleep/Wake UUID:       3B9AC087-552B-4F26-A1BD-7CD927188D9F

Time Awake Since Boot: 120000 seconds
Time Since Wake:       1600 seconds

System Integrity Protection: disabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @loader_path/libboost_system-mt.dylib
  Referenced from: /Applications/Coins/Raven-Qt.app/Contents/Frameworks/libboost_thread-mt.dylib
  Reason: image not found

Binary Images:
       0x1039ff000 -        0x10451bfff +org.ravenfoundation.Raven-Qt (2.0.3 - 2.0.3) <F12AAE7C-328D-3B8F-941F-46384EAE52E5> /Applications/Coins/Raven-Qt.app/Contents/MacOS/Raven-Qt
       0x104651000 -        0x104653ff7 +libboost_system.dylib (0) <6D4202B3-758D-3014-A208-8577024B9BB3> /Applications/Coins/Raven-Qt.app/Contents/Frameworks/libboost_system.dylib
       0x10465c000 -        0x10466bff7 +libboost_filesystem.dylib (0) <BDEC6C74-6778-342E-AFF0-62ABA7D03E43> /Applications/Coins/Raven-Qt.app/Contents/Frameworks/libboost_filesystem.dylib
       0x10467b000 -        0x1046adfff +libboost_program_options-mt.dylib (0) <AEDAEFBB-E939-3404-BD07-2313425473FA> /Applications/Coins/Raven-Qt.app/Contents/Frameworks/libboost_program_options-mt.dylib
       0x1046cc000 -        0x1046d9fff +libboost_thread-mt.dylib (0) <CE22F73C-D5EA-32D9-A732-D824D54D622C> /Applications/Coins/Raven-Qt.app/Contents/Frameworks/libboost_thread-mt.dylib
       0x1046e9000 -        0x1046ecff7 +libboost_chrono-mt.dylib (0) <19312DE7-D906-321B-9A48-5822E962A2EB> /Applications/Coins/Raven-Qt.app/Contents/Frameworks/libboost_chrono-mt.dylib
       0x1046f2000 -        0x1047f1ff7 +QtNetwork (0) <5257AB18-D1CB-37F2-AF42-C2CDD10DFA03> /Applications/Coins/Raven-Qt.app/Contents/Frameworks/QtNetwork.framework/Versions/5/QtNetwork
       0x10483b000 -        0x104c86fff +QtWidgets (0) <F20A9B73-EBF8-365F-9572-9F51B039A463> /Applications/Coins/Raven-Qt.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets
       0x104de7000 -        0x1051f3fff +QtGui (0) <E72E3A29-2517-354E-8F35-252FD61CD17E> /Applications/Coins/Raven-Qt.app/Contents/Frameworks/QtGui.framework/Versions/5/QtGui
       0x1052e8000 -        0x1057afff3 +QtCore (0) <783611A1-EDF8-381F-B30A-700D5BF1CA8E> /Applications/Coins/Raven-Qt.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore
       0x10585f000 -        0x1058b9ff7 +QtDBus (0) <2F2C2631-9C4E-33B2-93F7-768791CB6864> /Applications/Coins/Raven-Qt.app/Contents/Frameworks/QtDBus.framework/Versions/5/QtDBus
       0x1058d1000 -        0x105a03ffb +libprotobuf.15.dylib (0) <2C6A5B36-5066-362A-91D7-06C58D3480D8> /Applications/Coins/Raven-Qt.app/Contents/Frameworks/libprotobuf.15.dylib
       0x105ab9000 -        0x105bddff7 +libdb_cxx-4.8.dylib (0) <5EAB4A5B-9B72-3AFC-865E-016E1223F47F> /Applications/Coins/Raven-Qt.app/Contents/Frameworks/libdb_cxx-4.8.dylib
       0x105c1c000 -        0x105c5bfff +libssl.1.0.0.dylib (0) <4D343D8E-B72A-38BD-9204-CC0354C0B7F8> /Applications/Coins/Raven-Qt.app/Contents/Frameworks/libssl.1.0.0.dylib
       0x105c7e000 -        0x105deed67 +libcrypto.1.0.0.dylib (0) <4A0A66FE-A6B9-387F-B265-512C91DF46F9> /Applications/Coins/Raven-Qt.app/Contents/Frameworks/libcrypto.1.0.0.dylib
       0x105e5a000 -        0x105e62ff3 +libminiupnpc.16.dylib (0) <C0328337-BDDE-37CA-9D40-BA304D48EE87> /Applications/Coins/Raven-Qt.app/Contents/Frameworks/libminiupnpc.16.dylib
       0x105e6c000 -        0x105e6dfff +libevent_pthreads-2.1.6.dylib (0) <6F618640-46F3-3B56-A22C-26941B4D8790> /Applications/Coins/Raven-Qt.app/Contents/Frameworks/libevent_pthreads-2.1.6.dylib
       0x105e8d000 -        0x105ed7acf  dyld (551.4) <8A72DE9C-A136-3506-AA02-4BA2B82DCAF3> /usr/lib/dyld
       0x105f2b000 -        0x105f58fff +libevent-2.1.6.dylib (0) <891F379E-D5F9-39EB-BECA-2E24F943B7B3> /Applications/Coins/Raven-Qt.app/Contents/Frameworks/libevent-2.1.6.dylib
    0x7fff37a4b000 -     0x7fff388a9fff  com.apple.AppKit (6.9 - 1561.60.100) <3C27CF6F-E640-3411-A87D-CCB2222CC754> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff388fb000 -     0x7fff388fbfff  com.apple.ApplicationServices (48 - 50) <AFFBD94A-AF76-336E-B53E-57524EAE8EF3> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices
    0x7fff3a46c000 -     0x7fff3a90dfef  com.apple.CoreFoundation (6.9 - 1454.90) <E5D594BF-9142-3325-A62D-CF4AAF472642> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff3b5e5000 -     0x7fff3b5e5fff  com.apple.CoreServices (822.36 - 822.36) <C8368F17-1589-3BA5-A0E7-89CB8DF2454F> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
    0x7fff3c5cd000 -     0x7fff3c993fff  com.apple.Foundation (6.9 - 1454.90) <8EA924F3-ADAE-3F4B-8482-8B11C027D9A5> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff5fb0d000 -     0x7fff5fb40ff7  libclosured.dylib (551.4) <3FB6B209-51F4-38DA-B1D8-2EE29D5BDD83> /usr/lib/closure/libclosured.dylib
    0x7fff60047000 -     0x7fff60048ffb  libSystem.B.dylib (1252.50.4) <CD555F3B-FDDB-35E5-A2FB-FBBF3D62031A> /usr/lib/libSystem.B.dylib
    0x7fff6027c000 -     0x7fff602d2fff  libc++.1.dylib (400.9) <7D3DACCC-3804-393C-ABC1-1A580FD00CB6> /usr/lib/libc++.1.dylib
    0x7fff602d3000 -     0x7fff602f7ff7  libc++abi.dylib (400.8.2) <EF5E37D7-11D9-3530-BE45-B986612D13E2> /usr/lib/libc++abi.dylib
    0x7fff61700000 -     0x7fff61aee7e7  libobjc.A.dylib (723) <DD9E5EC5-B507-3249-B700-93433E2D5EDF> /usr/lib/libobjc.A.dylib
    0x7fff621c4000 -     0x7fff621c8ff7  libcache.dylib (80) <092479CB-1008-3A83-BECF-E115F24D13C1> /usr/lib/system/libcache.dylib
    0x7fff621c9000 -     0x7fff621d3ff3  libcommonCrypto.dylib (60118.50.1) <029F5985-9B6E-3DCB-9B96-FD007678C6A7> /usr/lib/system/libcommonCrypto.dylib
    0x7fff621d4000 -     0x7fff621dbfff  libcompiler_rt.dylib (62) <968B8E3F-3681-3230-9D78-BB8732024F6E> /usr/lib/system/libcompiler_rt.dylib
    0x7fff621dc000 -     0x7fff621e5ffb  libcopyfile.dylib (146.50.5) <3885083D-50D8-3EEC-B481-B2E605180D7F> /usr/lib/system/libcopyfile.dylib
    0x7fff621e6000 -     0x7fff6226bfff  libcorecrypto.dylib (562.70.1) <5C26364F-2269-31EC-84AF-0FED2C902E38> /usr/lib/system/libcorecrypto.dylib
    0x7fff622f3000 -     0x7fff6232cff7  libdispatch.dylib (913.60.2) <232C69BD-022E-3AB9-8807-79F9FA7CB5EC> /usr/lib/system/libdispatch.dylib
    0x7fff6232d000 -     0x7fff6234aff7  libdyld.dylib (551.4) <81BF3A82-5719-3B54-ABA9-76C82D932CAC> /usr/lib/system/libdyld.dylib
    0x7fff6234b000 -     0x7fff6234bffb  libkeymgr.dylib (28) <E34E283E-90FA-3C59-B48E-1277CDB9CDCE> /usr/lib/system/libkeymgr.dylib
    0x7fff62359000 -     0x7fff62359ff7  liblaunch.dylib (1205.70.9) <B184B521-FF24-3142-AFAF-23D170CF918C> /usr/lib/system/liblaunch.dylib
    0x7fff6235a000 -     0x7fff6235effb  libmacho.dylib (906) <1902A611-081A-3452-B11E-EBD1B166E831> /usr/lib/system/libmacho.dylib
    0x7fff6235f000 -     0x7fff62361ff3  libquarantine.dylib (86) <26C0BA22-8F93-3A07-9A4E-C8D53D2CE42E> /usr/lib/system/libquarantine.dylib
    0x7fff62362000 -     0x7fff62363ff3  libremovefile.dylib (45) <711E18B2-5BBE-3211-A916-56740C27D17A> /usr/lib/system/libremovefile.dylib
    0x7fff62364000 -     0x7fff6237bfff  libsystem_asl.dylib (356.70.1) <39E46A6F-B228-3E78-B83E-1779F9707A39> /usr/lib/system/libsystem_asl.dylib
    0x7fff6237c000 -     0x7fff6237cfff  libsystem_blocks.dylib (67) <17303FDF-0D2D-3963-B05E-B4DF63052D47> /usr/lib/system/libsystem_blocks.dylib
    0x7fff6237d000 -     0x7fff62406ff7  libsystem_c.dylib (1244.50.9) <1187BFE8-4576-3247-8177-481554E1F9E7> /usr/lib/system/libsystem_c.dylib
    0x7fff62407000 -     0x7fff6240affb  libsystem_configuration.dylib (963.50.8) <DF6B5287-203E-30CB-9947-78DF446C72B8> /usr/lib/system/libsystem_configuration.dylib
    0x7fff6240b000 -     0x7fff6240effb  libsystem_coreservices.dylib (51) <486000D3-D8CB-3BE7-8EE5-8BF380DE6DF7> /usr/lib/system/libsystem_coreservices.dylib
    0x7fff6240f000 -     0x7fff62410fff  libsystem_darwin.dylib (1244.50.9) <09C21A4A-9EE0-388B-A9D9-DFF8F6758791> /usr/lib/system/libsystem_darwin.dylib
    0x7fff62411000 -     0x7fff62417ff7  libsystem_dnssd.dylib (878.70.2) <3290768B-54DE-3AB6-B155-AC0950AC5564> /usr/lib/system/libsystem_dnssd.dylib
    0x7fff62418000 -     0x7fff62461ff7  libsystem_info.dylib (517.30.1) <AB634A98-B8AA-3804-8436-38261FC8EC4D> /usr/lib/system/libsystem_info.dylib
    0x7fff62462000 -     0x7fff62488ff7  libsystem_kernel.dylib (4570.71.2) <F22B8D73-69D8-36D7-BF66-7F9AC70C08C2> /usr/lib/system/libsystem_kernel.dylib
    0x7fff62489000 -     0x7fff624d4fcb  libsystem_m.dylib (3147.50.1) <8CFB51C9-B422-3379-8552-064C63943A23> /usr/lib/system/libsystem_m.dylib
    0x7fff624d5000 -     0x7fff624f4fff  libsystem_malloc.dylib (140.50.6) <7FD43735-9DDD-300E-8C4A-F909A74BDF49> /usr/lib/system/libsystem_malloc.dylib
    0x7fff624f5000 -     0x7fff62625ff7  libsystem_network.dylib (1229.70.2) <5E86B2DE-9E15-3354-8714-4094ED5F698D> /usr/lib/system/libsystem_network.dylib
    0x7fff62626000 -     0x7fff62630ffb  libsystem_networkextension.dylib (767.70.1) <D23EAFC1-E8BD-34D5-969C-6E45A1C3B4E4> /usr/lib/system/libsystem_networkextension.dylib
    0x7fff62631000 -     0x7fff6263aff3  libsystem_notify.dylib (172) <08012EC0-2CD2-34BE-BF93-E7F56491299A> /usr/lib/system/libsystem_notify.dylib
    0x7fff6263b000 -     0x7fff62642ff7  libsystem_platform.dylib (161.50.1) <6355EE2D-5456-3CA8-A227-B96E8F1E2AF8> /usr/lib/system/libsystem_platform.dylib
    0x7fff62643000 -     0x7fff6264efff  libsystem_pthread.dylib (301.50.1) <0E51CCBA-91F2-34E1-BF2A-FEEFD3D321E4> /usr/lib/system/libsystem_pthread.dylib
    0x7fff6264f000 -     0x7fff62652fff  libsystem_sandbox.dylib (765.70.1) <553DFCC6-9D31-3B9C-AB7C-30F6F265786D> /usr/lib/system/libsystem_sandbox.dylib
    0x7fff62653000 -     0x7fff62654ff3  libsystem_secinit.dylib (30) <DE8D14E8-A276-3FF8-AE13-77F7040F33C1> /usr/lib/system/libsystem_secinit.dylib
    0x7fff62655000 -     0x7fff6265cff7  libsystem_symptoms.dylib (820.60.2) <585BDFA2-D54D-39D0-8046-44E824DABD43> /usr/lib/system/libsystem_symptoms.dylib
    0x7fff6265d000 -     0x7fff62670fff  libsystem_trace.dylib (829.70.1) <3A6CB706-8CA6-3616-8AFC-14AAD7FAF187> /usr/lib/system/libsystem_trace.dylib
    0x7fff62672000 -     0x7fff62677ff7  libunwind.dylib (35.3) <BEF3FB49-5604-3B5F-82B5-332B80023AC3> /usr/lib/system/libunwind.dylib
    0x7fff62678000 -     0x7fff626a5ff7  libxpc.dylib (1205.70.9) <0BC7AD67-671D-31D4-8B88-C317B8379598> /usr/lib/system/libxpc.dylib

**Comment by gaetan29** [comment]
Hi,
The following did the trick:

=> In applications go to Raven app that was installed and rightclick on it and choose Show Package Contents. In the Contents directory open the Frameworks directory find the file called libboost_system.dylib now you have to copy this and paste it in the same frameworks directory now you should have a copy of libboost_system.dylib file and now rename the file to be libboost_system-mt.dylib

**Comment by TronBlack** [comment]
Related to:
https://github.com/litecoin-project/litecoin/issues/369
Working on a solution.

**Comment by TronBlack** [comment]
The inclusion of libboost_system-mt was removed in a PR.  Putting it back in.   Making new builds.
