### ISSUE TITLE
Passwords print on the screen for raven-cli

### ISSUE THREAD

**Issue by seanspotatobusiness** [RavenProject/Ravencoin#188]
Every CLI cryptocurrency wallet I've ever used has not printed the password out on the screen as you type it but the raven-cli does. This means the password is then stored in plaintext in the bash history. Could you update the wallet to hide this?

**Comment by seanspotatobusiness** [comment]
The CLI wallets provided by Monero, Alloy and Turtlecoin all hide the password as it's typed. In-fact, I've never encountered a CLI tool of any kind which doesn't hide the password and storing the password automatically in plain text in the bash history... I mean, I shouldn't have to explain this, right?

**Comment by russkidooski** [comment]
all the coins you listed are cryptonote/bytecoin forks, we are a bitcoin fork and as such we have most of bitcoins features.

**Comment by seanspotatobusiness** [comment]
It just makes no sense to me that someone hasn't fixed this in all the time that Bitcoin has been around. People go on about the security of cryptocurrencies and Bruce Fenton talks about people having control over their own assets but it hardly seems that way when raven-cli help gives encryption instructions which expose your password. It seems like assets are one hack away from not being under the owner's control. I think this should be added to the list of stuff to be fixed. Just because it was inherited from Bitcoin, doesn't mean it has to stay this way? The whole point of forking is to do some things differently and this thing in particular surely deserves some attention.

**Comment by underdarkskies** [comment]
All I'm saying is that 100% of coins are derived from bitcoin. Bitcoin's features and reasoning etc i can speak for, and I agree that having a password stored in plaintext isn't optimal for cli users. However, the method I specified using -stdin will allow you to enter your passwords in a safe manner.

**Comment by seanspotatobusiness** [comment]
At the very least, the instructions in the help file should be modified to tell users to use -stdin because some people might not know.

**Comment by blondfrogs** [comment]
This is not going to be fixed as it is expected functionality of the client
