### ISSUE TITLE
Won't compile Ubuntu 16.04

### ISSUE THREAD

**Issue by alstef** [RavenProject/Ravencoin#21]
### Describe the issue
Fails to compile on Ubuntu 16.04. Make error:
/usr/bin/ld: crypto/libraven_crypto.a(crypto_libraven_crypto_a-blake.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC

#### If so, please list the steps to reproduce below:
1. git clone 
2. ./autogen.sh
3. ./configure
4. make -j4

### Expected behaviour
Compilation succeeds 

### Actual behaviour
Compilation fails

### Machine specs:
- OS: Ubuntu 16.04
- CPU: 4 core
- RAM: 8 GB
- Disk size: 250 GB
- Disk Type (HD/SDD): HDD

**Comment by GreeneTech** [comment]
sudo apt-get update && sudo apt-get install -y software-properties-common

sudo add-apt-repository -y ppa:bitcoin/bitcoin
sudo apt-get update && sudo apt-get install -y automake autotools-dev bsdmainutils build-essential git libboost-all-dev libdb4.8-dev libdb4.8++-dev libevent-dev libminiupnpc-dev libprotobuf-dev libqrencode-dev libqt5gui5 libqt5core5a libqt5dbus5 libssl-dev libtool libzmq3-dev pkg-config protobuf-compiler python3 qttools5-dev qttools5-dev-tools

git clone https://github.com/RavenProject/Ravencoin.git

cd Ravencoin

./autogen.sh

./configure --enable-cxx --disable-shared --with-pic --prefix=$BDB_PREFIX CXXFLAGS="-fPIC" CPPFLAGS="-fPIC"

make

**Comment by alstef** [comment]
Works now. Thank you

**Comment by RavenCoinDev** [comment]
Solved - as per comment.
