### ISSUE TITLE
RPC asset balances reporting incorrectly

### ISSUE THREAD

**Issue by cryptelius** [RavenProject/Ravencoin#210]
### Describe the issue
RPC calls appear to return incorrect asset balances and/or different balances depending on which node I query.

#### If so, please list the steps to reproduce below:
1. `getassetdata HEREHAVEANOTHERASSET` reports `"amount": 2000000`
2. The sum of the balances returned by `listaddressesbyasset HEREHAVEANOTHERASSET` is greater than 2000000

(3). `listassetbalancesbyaddress mfXPP5WsJiDookRKTCTGb9SrChxJPK8q6o` returns `"HEREHAVEANOTHERASSET": 9667` from one node, empty list from another node.

### What version of bitcoin-core are you using?
v2.0.2.0-1a30524c4
Official binary on Kubuntu 16.04 system, self compiled on OS X 10.13.3 system

**Comment by underdarkskies** [comment]
testnetV2 has lots of chainsplits.
that would explain the different balances etc. the consensus should be smoother on testnetV4 when its launched

**Comment by RealBokito** [comment]
I saw the same issue with the total sum of all assets. I looked at my i3cn-code and found no issue. It seems the RPC cmd listaddressesbyasset returns both the holders of the asset (= total amount) AND the owner of the asset (= the issued amount of the asset). In most instances the public address of the latter seems to be the owner. However, there are some exceptions, such as the owner tokens split across multiple public addresses by the same private key.

It might be better to split the output into a listaddressesbyasset for all HOLDERS of the asset and listownerbyasset to retrieve the public address(es) of the actual ISSUER.

**Comment by RealBokito** [comment]
I found that the RPC command listaddressesbyasset returns both the HOLDERS of the asset  AND the ISSUER. The sum of all balances  is greater than the quantity defined for the asset.
In most instances the public address which equals to the defined quantity of the asset, seems to be the ISSUER. However, there are some exceptions, such as when the ISSUER split the asset across multiple public addresses (by sending "tokens" to a different address provided by the same private key).

It might be an idea to split the output: a listaddressesbyasset for all HOLDERS of the asset and listissuerbyasset to retrieve the public address(es) of the  ISSUER of the asset.

The reason for different results between nodes is of all the chainsplits. testnet4 should change this.

**Comment by underdarkskies** [comment]
@RealBokito 
1)there is only one public key corresponding to a private key. not sure what you are talking about
1a) token balances greater than the issued amount are due to the chainsplits. txs got reversed and then re applied.
2) listaddressesbyasset <assetname>! will give you the issuer

**Comment by RealBokito** [comment]
1) @underdarkskies Just for my understanding:
This one is OK: http://www.i3cn.com/rvn/?cmd=viewasset&id=RFVQUElFMi4w
But this one might be wrong due to the chainsplits: http://www.i3cn.com/rvn/?cmd=viewasset&id=QUZBUk0uQ09XLjg=

2) didn't know. Thnx!

**Comment by sull** [comment]
*listassetbalancesbyaddress* fails to reliably return data (apparently due to caching). 
Is this something worthy of a new issue or can discuss here?
