### ISSUE TITLE
Can't compile on FreeBSD 11

### ISSUE THREAD

**Issue by diafoirus** [RavenProject/Ravencoin#212]
## Describe the issue

When i try to compile v2.0.2 release ( https://github.com/RavenProject/Ravencoin/commit/1a30524c401469dec7c4c5b0fe5abaac7a0d4246 ) or *current* on FreeBSD 11.1 I got this output on ./configure : 

config.status: error: Something went wrong bootstrapping makefile fragments
    for automatic dependency tracking.  Try re-running configure with the
    '--disable-dependency-tracking' option to at least be able to build
    the package (albeit without support for automatic dependency tracking).
See `config.log' for more details

When i check 'config.log' file, the most relevant about the error is:

config.status:1662: executing depfiles commands
config.status:1737: cd src       && sed -e '/# am--include-marker/d' Makefile         | make -f - am--depfiles
make: exec(../build-aux/install-sh) failed (No such file or directory)
*** Error code 1

Stop.
make: stopped in /usr/home/astarte/Downloads/Ravencoin-2.0.2/src
config.status:1744: $? = 1
config.status:1748: error: in `/home/astarte/Downloads/Ravencoin-2.0.2':
config.status:1754: error: Something went wrong bootstrapping makefile fragments
    for automatic dependency tracking.  Try re-running configure with the
    '--disable-dependency-tracking' option to at least be able to build
    the package (albeit without support for automatic dependency tracking).
See `config.log' for more details

### Can you reliably reproduce the issue?

1. git clone https://github.com/RavenProject/Ravencoin.git && cd Ravencoin
2. ./autogen
3. ./configure --prefix=/usr/local/ravencoin --with-incompatible-bdb BDB_CFLAGS=-I/usr/local/include/db5 BDB_LIBS=-L/usr/local/lib -ldb_cxx-5

automake :  1.16.1
libtoolize:  2.4.6
Clang: 4.0.0  / LLVM 4.0.0
FreeBSD: 11.1-RELEASE 
DB: 5.3

config.log : https://hastebin.com/bifisaxowi.makefile

Thanks in advance any help!...

**Comment by underdarkskies** [comment]
the prefix flags are set for target directories of dependencies, not for the final ravencoin executables. dont use the prefix flag.

**Comment by underdarkskies** [comment]
also the correct flags to build with bdb5.3 and the correct process to compile are:
```
$ cd ~/
$ git clone https://github.com/ravenproject/ravencoin
$ cd ~/ravencoin
$ wget http://download.oracle.com/berkeley-db/db-5.3.28.NC.tar.gz
$ echo '76a25560d9e52a198d37a31440fd07632b5f1f8f9f2b6d5438f4bc3e7c9013ef  db-5.3.28.NC.tar.gz' | sha256sum -c
The last command should return a value of db-5.3.28.NC.tar.gz: OK.

Next, unpack the BerkeleyDB source and compile.

$ tar -xvf db-5.3.28.NC.tar.gz
$ cd db-5.3.28.NC/build_unix
$ mkdir -p build
$ BDB_PREFIX=$(pwd)/build
$ cd ~/ravencoin 
$ ./autogen.sh
$ ./configure --enable-cxx --disable-shared --with-pic --prefix=$BDB_PREFIX CXXFLAGS="-fPIC" CPPFLAGS="-fPIC" --with-incompatible-bdb
$ make install
```

**Comment by underdarkskies** [comment]
then use make install DESTDIR=/path/to/where/you/want/it/running/on/system

**Comment by underdarkskies** [comment]
side note( you may or may not need the fpic flagsand the enable-cxx depending on your version of gcc)

**Comment by diafoirus** [comment]
Hello, thanks for response!...

Still I have the same issue (I followed your instructions):

config.status: error: Something went wrong bootstrapping makefile fragments
    for automatic dependency tracking.  Try re-running configure with the
    '--disable-dependency-tracking' option to at least be able to build
    the package (albeit without support for automatic dependency tracking).
See `config.log' for more details

Configure line : 

./configure --enable-cxx --disable-shared --with-pic --prefix=$BDB_PREFIX CXXFLAGS="-fPIC" CPPFLAGS="-fPIC" --with-incompatible-bdb

BTW: Congrats for Bittrex listing!...

I'll test your instructions in a clean environment ,

**Comment by LongRail** [comment]
the problem point is here:
cd src && sed -e '/# am--include-marker/d' Makefile | make -f - am--depfiles
make: exec(../build-aux/install-sh) failed (No such file or directory)
*** Error code 1
but I don't know what actually wrong with FreeBSD. May be it has something to do with bash interpreter.

**Comment by blondfrogs** [comment]
@diafoirus Is this resolved?

**Comment by wtfix** [comment]
Were you able to compile under freebsd? I'm having issues too.
