### ISSUE TITLE
[testnet] Wrong "Amount" information on GUI wallet desktop notifications 

### ISSUE THREAD

**Issue by bedri** [RavenProject/Ravencoin#218]
### Describe the issue
GUI wallet desktop notifications shows wrong "Amount" information when a transaction is sent.
#### If so, please list the steps to reproduce below:
1. Open GUI wallet
2. Make a transaction to an address (either by sending only Ravencoins or transfering an asset)
3. Observe the desktop notification window appear and shows wrong "Amount" information

### Expected behaviour
Desktop notification window should show correct "Amount" information

### Actual behaviour
Desktop notification window shows wrong "Amount" information

### Screenshots.
1000 Ravencoin transaction:
![raven-2 0 3-asset-test-5](https://user-images.githubusercontent.com/765487/44086313-d0c88858-9fc4-11e8-96f5-99d1b3a4fbd5.png)
Wrong "Amount" information in desktop notification for 1000 Ravencoin transaction:
![raven-2 0 3-asset-test-4](https://user-images.githubusercontent.com/765487/44086385-04b4814e-9fc5-11e8-83a9-e691dc997fb4.png)

Sub asset creation payment amount desktop notification (this transaction is not accepted by network but notification "Amount" information is shown at the time of the creation of transaction/asset transfer so screenshot still applies for the problem):
![raven-2 0 3-asset-test-3](https://user-images.githubusercontent.com/765487/44086426-2bcda90e-9fc5-11e8-978f-146ede0d5d85.png)

### What version of bitcoin-core are you using?
Raven Core version v2.0.3.0-fc5d1a7c4 (64-bit)

**Comment by ksnell88** [comment]
I have the same issue but on the mainnet wallet -  Windows 10 Pro, Raven Core version v2.0.3.0-39d8745 (64-bit). Seems to skip the decimal point on notifications.

Unfortunately, I only received 71.65417460 RVN in this screecap, and not 7.2 billion :).

<img width="296" alt="rvn screecap" src="https://user-images.githubusercontent.com/34407093/44303060-6da83a80-a2fc-11e8-8187-4e1c445888b1.PNG">

**Comment by bedri** [comment]
This issue is duplicate of [#218](https://github.com/RavenProject/Ravencoin/issues/218)

**Comment by bedri** [comment]
Yes the issue exists on the mainnet. I forgot to mention it :)
