### ISSUE TITLE
Issue Wallet 

### ISSUE THREAD

**Issue by MOHAMEDVII** [RavenProject/Ravencoin#219]
This issue tracker is only for technical issues related to bitcoin-core.

General bitcoin questions and/or support requests and are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).

For reporting security issues, please read instructions at [https://bitcoincore.org/en/contact/](https://bitcoincore.org/en/contact/).

### Describe the issue
Hello,
I have a problem with my wallet.
After change my file in another folder OR after a download of an Emercoin wallet
the launch of my raven wallet restart since the beginning. and my balance at 0
#### If so, please list the steps to reproduce below:
1.No
2.
3.

### Expected behaviour
Tell us what should happen
Probably a files in the wrong place
### Actual behaviour
Tell us what happens instead
My wallet started since the beginning. a new installation
### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of bitcoin-core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.

### Machine specs:
- OS: win7
- CPU:intel core i5
- RAM:8G

- Disk size:300GB
- Disk Type (HD/SDD):HD
### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.
![raven_version](https://user-images.githubusercontent.com/32529236/44107639-59346cb0-9ff8-11e8-90b3-3fa938352954.PNG)
#
![raven_balance](https://user-images.githubusercontent.com/32529236/44107770-bc552c1c-9ff8-11e8-9b65-d1a5d594506d.PNG)
![old_version](https://user-images.githubusercontent.com/32529236/44108112-b5a37de6-9ff9-11e8-94b2-896e63d3d7e4.PNG)

**Comment by underdarkskies** [comment]
this isnt a problem with ravencoin. search you harddrive for a folder named "Raven" it should be in %appdata%
find your wallet.dat 
if another coin erased you wallet.dat or something happened with windows, restore from a backup

**Comment by blondfrogs** [comment]
Closing this issue as it doesn't require a fix
