### ISSUE TITLE
ERROR error -32601: method not found yiimp

### ISSUE THREAD

**Issue by crombiecrunch** [RavenProject/Ravencoin#23]
I am trying to set this coin in yiimp but i am getting a ERROR error -32601: method not found in the admin panel

I have removed the check mark "Has getinfo" but still no luck. can you please assist? I was told something about a patch but i can not find it.

**Comment by MSFTserver** [comment]
I believe this would be a ccminer issue? not related to our wallet?

**Comment by crombiecrunch** [comment]
no it has to do with the new bitcoin core removing the getinfo feature. i was told to look at https://github.com/bitcoin/bitcoin/pull/10871 but coin code is something i am still learning

**Comment by MSFTserver** [comment]
ahhh sorry I misunder stood

**Comment by mja1175** [comment]
This is fixed with the pull request:
https://github.com/RavenProject/Ravencoin/pull/24

**Comment by RavenCoinDev** [comment]
Pull request merged.
