### ISSUE TITLE
[Discussion] Only possible to re-issue integer values of asset - Should be float with $unit decimals?

### ISSUE THREAD

**Issue by fokep** [RavenProject/Ravencoin#234]
Testing v. 2.0.4 on Fedora 28 x86 (runs great btw), noticed it is only possible to re-issue whole numbers of existing asset.

I'm thinking it should be possible to re-issue quantity according to defined $unit.

**Comment by underdarkskies** [comment]
The help text for the rpc includes a typo. Technically both issue and reissue can accept non integer values for quantity via the console. Currently the qt interface does not support non integer values though

**Comment by blondfrogs** [comment]
In the Qt wallet, we are only allowing reissuing of whole numbers
