### ISSUE TITLE
[testnet][Visual Defect] While creating assets, the invalid asset name warning message is lost.

### ISSUE THREAD

**Issue by SubmarineMan** [RavenProject/Ravencoin#236]
The invalid asset name warning message is lost when you toggle the Add JSON Meta Data Hash checkbox.

Step 1: Enter invalid asset name 
![image](https://user-images.githubusercontent.com/30309226/44304809-76b10000-a32c-11e8-8137-4e1002a05023.png)

Step 2: Check Add JSON Meta Data Hash. The warning message disappears. Resizing the window doesn't show the message.
![image](https://user-images.githubusercontent.com/30309226/44304810-7e70a480-a32c-11e8-8a2e-9bf96bba6315.png)

Step 3: Uncheck Add JSON Meta Data Hash. The warning message doesn't show up.
![image](https://user-images.githubusercontent.com/30309226/44304814-84ff1c00-a32c-11e8-9a94-4e07793b53e8.png)

**Raven Core version** v2.0.4.0-e1a96a0bd-dirty (64-bit)

**Machine specs:**
- OS: Window 10
- CPU: i5 4690
- RAM: 12GB
- Disk size: 256GB
- Disk Type (HD/SDD): SSD

**Comment by blondfrogs** [comment]
Fixed with release #123
