### ISSUE TITLE
Raven-2.0.4.0-osx.dmg installs Raven-Qt but does not run on Mac OS High Sierra 10.13.6 

### ISSUE THREAD

**Issue by geoff-blockchainstrategygroup** [RavenProject/Ravencoin#238]
This issue tracker is only for technical issues related to bitcoin-core.

General bitcoin questions and/or support requests and are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).

For reporting security issues, please read instructions at [https://bitcoincore.org/en/contact/](https://bitcoincore.org/en/contact/).

### Describe the issue
Installed Raven-2.0.4.0-osx.dmg on Mac OS High Sierra 10.13.6 (17G65) and it fails to run.
![screenshot 2018-08-20 16 14 40](https://user-images.githubusercontent.com/25152573/44364445-05409100-a495-11e8-9ccb-981730ac288e.png)

### Can you reliably reproduce the issue?
Yes
#### If so, please list the steps to reproduce below:
1. Removed Raven QT from applications
2. Installed new dmg
3. Fails to run

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of bitcoin-core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.

### Machine specs:
- OS:Mac OS High Sierra 10.13.6 (17G65)
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SDD):

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by russkidooski** [comment]
duplicate of #181

**Comment by blondfrogs** [comment]
Closing because of Duplicate issue was solved #181
