### ISSUE TITLE
Spelling mistake (french)

### ISSUE THREAD

**Issue by gaetan29** [RavenProject/Ravencoin#246]
Hi,
There is a small spelling mistake under Tab "Envoyer" ("Send") ...
Bottom left button = "Evoyer" instead of "Envoyer"

See attached screen shot
![rvn-wallet-envoyer](https://user-images.githubusercontent.com/788375/44493778-9c5e4200-a669-11e8-98f4-8146f8746e4c.png)

**Comment by fokep** [comment]
That's weird, can't find "Evoyer" in either of the french locales. Could you 

[fr](https://github.com/RavenProject/Ravencoin/blob/master/src/qt/locale/raven_fr.ts)
[fr_CA](https://github.com/RavenProject/Ravencoin/blob/master/src/qt/locale/raven_fr_CA.ts)
[fr_FR](https://github.com/RavenProject/Ravencoin/blob/master/src/qt/locale/raven_fr_FR.ts)

**Comment by gaetan29** [comment]
Sorry, I cannot either .... This is on OSX ... Does it make a difference ?

That said, I cannot find either "Nettoyer Tout" ... So maybe we are looking at the wrong place ?

**Comment by medikent** [comment]
@gaetan29 Is this still an issue for you? If so, what version (ex: 2.0.4) did you see this with? Do you know how to check the version you are using?

**Comment by gaetan29** [comment]
Yes still an issue on Version 2.0.4.1 (OSX)

![rvn-01](https://user-images.githubusercontent.com/788375/45973523-05f1b780-c03f-11e8-92b2-7ebcd7b53541.png)
![rvn-02](https://user-images.githubusercontent.com/788375/45973524-05f1b780-c03f-11e8-821b-b663f620f2af.png)

**Comment by fdoving** [comment]
As far as I can tell, from searching transifex.com, this is now fixed.

If it is still a problem it can be fixed at: https://www.transifex.com/ravencoin/
