### ISSUE TITLE
ravend memory leak

### ISSUE THREAD

**Issue by seanspotatobusiness** [RavenProject/Ravencoin#251]
### Describe the issue

Memory used by ravend continually increases on Raspbian Stretch Linux until all RAM is consumed and then starts using swap.

#### If so, please list the steps to reproduce below:
1. Compile ravend per instructions on github.
2. Type ./ravend in console
3. Type top in another console and watch memory consumption increase over the course of several hours.

### Expected behaviour
I guess memory consumption should stop somewhere around 270 MB which it does for the Windows wallet.

### Actual behaviour
Memory consumption increases forever (420 MB consumed after running for 1 hr 20 min).

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of bitcoin-core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.
I compiled it yesterday using the instructions for Raspberry Pi on github. There is no command to get the version number so I can't provide one.

### Machine specs:
- OS: Raspbian Stretch
- CPU: Arm7
- RAM: 1 GB
- Disk size: 32 GB/1 TB
- Disk Type (HD/SDD): microSD/HDD

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by underdarkskies** [comment]
hey bud, can you tell me if this version has a memleak? its precompiled using a static build:

https://github.com/underdarkskies/Ravencoin/releases/download/2.0.4/raven-2.0.4-arm-linux-gnueabihf.tar.gz

**Comment by blondfrogs** [comment]
@seanspotatobusiness Where you able to test @underdarkskies build? Would be helpful to know if the build linked above fixes this problem.

**Comment by blondfrogs** [comment]
@seanspotatobusiness Any update?
