### ISSUE TITLE
New Wallet not syncing, stuck at block 338873 with message "syncing headers 100%"

### ISSUE THREAD

**Issue by reset77** [RavenProject/Ravencoin#256]
What is happening with new Wallet, why release something that doesnt work?

too bad to see Raven falling in this mistakes and problems

what to do to recover the wallet or make it work?

windows machine with latest version 2.0.4

**Comment by virtopiarvn** [comment]
I don't think this is a common issue. I have not seen anybody else with that issue and my wallets work fine. Close the wallet and try renaming or removing:
- Chainstate
- Database
- Blocks

Found in your "Roaming" folder.

**Comment by crackfoo** [comment]
Yes, if you don't delete the previous chain, you'll get stuck. 

rm the folders as suggested.

Cheers

www.zpool.ca

**Comment by reset77** [comment]
Ok man but the installation says to only upgrade, nothing about moving folders, more info will be ok when releasing new versions like this

i got help on discord, is now working

please dont let raven become another shitcoin full of problems and bad network, lets hope it gets better after fork, thanks!!
