### ISSUE TITLE
Raven 2.0.4.0 not working on Mac - Sierra 10.12.16

### ISSUE THREAD

**Issue by lonelyminer** [RavenProject/Ravencoin#259]
Hello,
Install on Mac - Sierra 10.12.16, but it can't run 2.04.
I reinstall old Ravencore Qt,  it looks slow to sync (30 min and still 92 %) ....  should this be ok?
When to expect version that works...?

Thanks....

### Machine specs:
- OS:Sierra 10.12.16,
- CPU:Intel 1.6 Intel core I5
- RAM: 8 GB
- Disk size:1TB
- Disk Type (HD/SDD):HD

**Comment by underdarkskies** [comment]
please run 2.0.4. i compiled this dmg from the source code. https://github.com/underdarkskies/Ravencoin/releases/download/2.0.4/raven-2.0.4-osx-unsigned.dmg it should work on sierra.

@TronBlack can we please re-release 2.0.4 with my build processes? to many users are needing to get redirected to my compiled binaries...

**Comment by lonelyminer** [comment]
Yes... this version works,  balance ok, sync looks  ok ..., 
message on overview:  Asset activation status - wait until 30.10.2018, I guess  it's  normal ?

**Comment by lonelyminer** [comment]
I unbanning banned peers and now Ravencore sync ok.

Thank you.
