### ISSUE TITLE
error when starting stratum 

### ISSUE THREAD

**Issue by bouguerra12** [RavenProject/Ravencoin#28]
### Describe the issue
i get an error when i start ravend -deamon 

2018-02-14 17:35:08 runCommand error: system(/var/stratum/blocknotify 137.74.**.69:3636 2044 0000000000104532dafff81e4482f1d02562789adb927f5b9c47ac41dcb5ea60) returned 256

### my raven coin conf file : 
rpcuser=y***
rpcpassword=ilDH6GKV****KayrNBA
rpcport=20440
rpcthreads=8
rpcallowip=127.0.0.1
onlynet=ipv4
algo=x16r
maxconnections=12
daemon=1
server=1
listen=1
#gen=0

alertnotify=echo %s | mail -s "raven alert!" bo**@gmail.com
blocknotify=/var/stratum/blocknotify 137.74.**.69:3636 2044 %s

### Machine specs:
- OS: ubuntu 16.4
- CPU: 1 core 
- RAM: 2 gb
- Disk size: 10 gb
- Disk Type (HD/SDD):

**Comment by bitliratoken** [comment]
+1


same setup buy with Polytimos coin.

**Comment by H45H-t4g** [comment]
this appears to be an issue with yiimp. I'm experiencing the same problem with all the coins I try to add... there must be something wrong with the syntax. I'm not sure. I'm looing for a solution as well.

**Comment by MovLab2** [comment]
Same Problem I have also blocknotify returns  -1

**Comment by olalawal** [comment]
I have the same issue has anyone resloved it ? really anoying its the last thing stopping my yiimp instance from working

**Comment by TronBlack** [comment]
Please re-submit if these issues still exist.

Closing issue.
