### ISSUE TITLE
[v2.0.5] Unique assets can be created with Quantity greater than 1 and Units greater than 0

### ISSUE THREAD

**Issue by Scotty0448** [RavenProject/Ravencoin#281]
When creating a unique asset using QT v2.0.5 for OSX, the interface allows setting the quantity greater than 1 and the units greater than 0. The actual creation process also presented no error and I was able to successfuly create a unique asset with quantity of 10 and units of 8.

I see a few similar unique assets created by Russ who I understand uses Windows, so I don't believe this is OSX specific.

**Comment by russkidooski** [comment]
i was also able to create unique assets with a higher quantity than 1, they are unable to be sent once created. running windows 10

**Comment by Scotty0448** [comment]
The error returned when attempting to transfer one of these unique assets is "bad-txns-transfer-unique-amount-was-not-1", even when the amount being transferred is set to 1.  I suspect it's because the remaining assets (more than 1) have to be transferred to a change address.

**Comment by blondfrogs** [comment]
@Scotty0448 This has been fixed, and is in v2.0.6
