### ISSUE TITLE
[v2.0.5] Unable to transfer amounts greater than 100 for any asset

### ISSUE THREAD

**Issue by Scotty0448** [RavenProject/Ravencoin#282]
When using QT v2.0.5 for OSX to transfer any type of asset, the interface is not allowing values greater than 100 into the Amount field.  The asset's wallet balance doesn't appear to affect this.

**Comment by russkidooski** [comment]
i was just about to create this as a new issue, i can also confirm this bug on windows 10

**Comment by blondfrogs** [comment]
@Scotty0448 This has been fixed, and will be in v2.0.6

**Comment by Neofito89** [comment]
In 2.1.0 linux 64 bits I wasnt able to send 9230, neither 8000, I had to split it in two, being the biggest 5000RVN.

Im a little bit newbie reporting bugs on github, I'm not sure if I should reopend this or open a new Issue, sorry.
