### ISSUE TITLE
asset_name only accepts uppercase characters

### ISSUE THREAD

**Issue by fedsten** [RavenProject/Ravencoin#283]
I wanted to try to issue some assets on Raven's testnet from the terminal using `raven-cli`, so the first thing I did was to look at the help message to understand how to properly launch the command. The help message provides the following examples:

```
Examples:
> raven-cli issue "myassetname" 1000
> raven-cli issue "myassetname" 1000 "myaddress"
> raven-cli issue "myassetname" 1000 "myaddress" "changeaddress" 4
> raven-cli issue "myassetname" 1000 "myaddress" "changeaddress" 2 true
> raven-cli issue "myassetname/mysubasset" 1000 "myaddress" "changeaddress" 2 true
```
I tried to replicate it, but I was keeping getting the following error message:

```
error code: -8
error message:
Invalid parameter: asset_name must only consist of valid characters and have a size between 3 and 30 characters. See help for more details.
```
Eventually I realised that my mistake was using lowercase characters in the `asset_name`, while the command seems to work only with uppercase characters. If that is actually a validity rule for the input of the `issue` command, I would suggest to change the examples provided in the help message as they are misleading.

**Comment by TronBlack** [comment]
Fixed.  Thank you for reporting the issue.  It may take a few cycles to make it from develop2 to the latest release.
