### ISSUE TITLE
Mac DMG missing or incorrectly named

### ISSUE THREAD

**Issue by muchobrento** [RavenProject/Ravencoin#29]
### Describe the issue

For Mac Download Instructions, the readme file says to download "Raven.dmg". However, there is no .dmg file with this name listed. The only DMG that I see is "Raven-Qt.dmg". 

Is the "Raven-Qt" file the correct .dmg file? Or is the file listed in the readme instructions missing?

### Machine specs:
- OS: MacOS Sierra
- CPU: 2.8 GHz Intel Core i5
- RAM: 8 GB 1867 MHz DDR3
- Disk size: 1 TB
- Disk Type (HD/SDD): HD

**Comment by MSFTserver** [comment]
read me is wrong

**Comment by MSFTserver** [comment]
wallet gui is the qt

**Comment by RavenCoinDev** [comment]
If this is still a problem, let us know which README or file, and we'll get it fixed.

**Comment by RavenCoinDev** [comment]
Unable to find this in the README.  Please re-submit issue if it is still a problem.
