### ISSUE TITLE
Unable to create asset using a multisig address.

### ISSUE THREAD

**Issue by russkidooski** [RavenProject/Ravencoin#292]
Trying to create an asset on testnetv5 with a multisig address gives this: Invalid: Error: The transaction was rejected! Reason given: bad-txns-bad-asset-script

**Comment by blondfrogs** [comment]
@russkidooski "pay to script hash" and "pay to multisig"  are not supported. It is a planned feature, but as of right now we only support "pay to pubkey hash" scripts
