### ISSUE TITLE
Make Check Tests Fail v2.0.4

### ISSUE THREAD

**Issue by KyleMcMaster** [RavenProject/Ravencoin#312]
### Describe the issue
Make check tests fail on Ubuntu 18.04, Raven core version v2.0.4. 

### Can you reliably reproduce the issue?
Yes, consistently fails tests.

#### If so, please list the steps to reproduce below:
1. open terminal
2. cd Ravencoin
3. make check
4. Tests fail

### Expected behaviour
Tests should pass (bitcoin core 0.16.2 tests pass fyi)

### Actual behaviour
Tests fail at:
Making check in src
make[1]: Entering directory '/home/kmc/Ravencoin/src'
make[2]: Entering directory '/home/kmc/Ravencoin/src'
make[3]: Entering directory '/home/kmc/Ravencoin'
make[3]: Leaving directory '/home/kmc/Ravencoin'
make[3]: Entering directory '/home/kmc/Ravencoin/src/secp256k1'
make[3]: Leaving directory '/home/kmc/Ravencoin/src/secp256k1'
make  check-TESTS check-local
make[3]: Entering directory '/home/kmc/Ravencoin/src'
make[4]: Entering directory '/home/kmc/Ravencoin/src'
make[5]: Entering directory '/home/kmc/Ravencoin'
make[5]: Leaving directory '/home/kmc/Ravencoin'
make[5]: Entering directory '/home/kmc/Ravencoin/src/secp256k1'
make[5]: Leaving directory '/home/kmc/Ravencoin/src/secp256k1'
FAIL: test/test_raven
FAIL: qt/test/test_raven-qt
============================================================================
Testsuite summary for Raven Core 2.0.4
============================================================================
# TOTAL: 2
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  2
# XPASS: 0
# ERROR: 0
============================================================================
See src/test-suite.log
Please report to https://github.com/RavenProject/Ravencoin/issues
============================================================================
Makefile:10506: recipe for target 'test-suite.log' failed
make[4]: *** [test-suite.log] Error 1
make[4]: Leaving directory '/home/kmc/Ravencoin/src'
Makefile:10612: recipe for target 'check-TESTS' failed
make[3]: *** [check-TESTS] Error 2
make[3]: Leaving directory '/home/kmc/Ravencoin/src'
Makefile:10718: recipe for target 'check-am' failed
make[2]: *** [check-am] Error 2
make[2]: Leaving directory '/home/kmc/Ravencoin/src'
Makefile:10399: recipe for target 'check-recursive' failed
make[1]: *** [check-recursive] Error 1
make[1]: Leaving directory '/home/kmc/Ravencoin/src'
Makefile:750: recipe for target 'check-recursive' failed
make: *** [check-recursive] Error 1

### What version of ravencoin-core are you using?
v2.0.4

### Machine specs:
- OS: Ubuntu 18.04
- CPU: Intel i7 7700K
- RAM: 16gb
- Disk size: 1TB
- Disk Type (HD/SDD): SSD

### Any extra information that might be useful in the debugging process.

==========================================
   Raven Core 2.0.4: src/test-suite.log
==========================================

# TOTAL: 2
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  2
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: test/test_raven
=====================

Running 286 test cases...
unknown location(0): fatal error: in "asset_tx_tests/asset_tx_valid": memory access violation at address: 0x000000a0: no mapping at fault address
test/assets/asset_tx_tests.cpp(60): last checkpoint

*** 1 failure is detected in the test module "Raven Test Suite"
FAIL test/test_raven (exit status: 201)

FAIL: qt/test/test_raven-qt
===========================

********* Start testing of URITests *********
Config: Using QtTest library 5.9.5, Qt 5.9.5 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 7.3.0)
PASS   : URITests::initTestCase()
FAIL!  : URITests::uriTests() 'rv.address == QString("175tWpb8K1S7NmH4Zx6rewF9WQrcZv245W")' returned FALSE. ()
   Loc: [qt/test/uritests.cpp(56)]
PASS   : URITests::cleanupTestCase()
Totals: 2 passed, 1 failed, 0 skipped, 0 blacklisted, 1ms
********* Finished testing of URITests *********
********* Start testing of PaymentServerTests *********
Config: Using QtTest library 5.9.5, Qt 5.9.5 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 7.3.0)
PASS   : PaymentServerTests::initTestCase()
QDEBUG : PaymentServerTests::paymentServerTests() PaymentServer::initNetManager: No active proxy server found.
QDEBUG : PaymentServerTests::paymentServerTests() PaymentServer::processPaymentRequest: Secure payment request from  "testmerchant.org"
QWARN  : PaymentServerTests::paymentServerTests() PaymentRequestPlus::getMerchant: Payment request: certificate expired or not yet active:  QSslCertificate("3", "03", "LxHILx+N3qwVoAcCmQ5cyw==", (), ("Expired Test Merchant"), QMap(), QDateTime(2013-02-23 21:26:43.000 UTC Qt::TimeSpec(UTC)), QDateTime(2013-02-24 21:26:43.000 UTC Qt::TimeSpec(UTC)))
QDEBUG : PaymentServerTests::paymentServerTests() PaymentServer::processPaymentRequest: Insecure payment request to  "RNu2QkiGVso7BTSbwHQTwoZc3GVewjssXE"
QWARN  : PaymentServerTests::paymentServerTests() PaymentRequestPlus::getMerchant: Payment request: certificate expired or not yet active:  QSslCertificate("3", "03", "LxHILx+N3qwVoAcCmQ5cyw==", (), ("Expired Test Merchant"), QMap(), QDateTime(2013-02-23 21:26:43.000 UTC Qt::TimeSpec(UTC)), QDateTime(2013-02-24 21:26:43.000 UTC Qt::TimeSpec(UTC)))
QDEBUG : PaymentServerTests::paymentServerTests() PaymentServer::processPaymentRequest: Secure payment request from  "testmerchant8.org"
QWARN  : PaymentServerTests::paymentServerTests() PaymentRequestPlus::getMerchant: Payment request: certificate expired or not yet active:  QSslCertificate("3", "06", "MiZaQ+g9lSHZGuHWkXZG+g==", (), ("Payment Request Intermediate 5"), QMap(), QDateTime(2013-02-23 22:59:51.000 UTC Qt::TimeSpec(UTC)), QDateTime(2013-02-24 22:59:51.000 UTC Qt::TimeSpec(UTC)))
QDEBUG : PaymentServerTests::paymentServerTests() PaymentServer::processPaymentRequest: Insecure payment request to  "RNu2QkiGVso7BTSbwHQTwoZc3GVewjssXE"
QWARN  : PaymentServerTests::paymentServerTests() PaymentRequestPlus::getMerchant: Payment request: certificate expired or not yet active:  QSslCertificate("3", "06", "MiZaQ+g9lSHZGuHWkXZG+g==", (), ("Payment Request Intermediate 5"), QMap(), QDateTime(2013-02-23 22:59:51.000 UTC Qt::TimeSpec(UTC)), QDateTime(2013-02-24 22:59:51.000 UTC Qt::TimeSpec(UTC)))
QWARN  : PaymentServerTests::paymentServerTests() PaymentRequestPlus::getMerchant: SSL error:  certificate signature failure
QDEBUG : PaymentServerTests::paymentServerTests() PaymentServer::processPaymentRequest: Insecure payment request to  "RNu2QkiGVso7BTSbwHQTwoZc3GVewjssXE"
QWARN  : PaymentServerTests::paymentServerTests() PaymentRequestPlus::getMerchant: SSL error:  certificate signature failure
QWARN  : PaymentServerTests::paymentServerTests() PaymentRequestPlus::getMerchant: SSL error:  unable to get local issuer certificate
QDEBUG : PaymentServerTests::paymentServerTests() PaymentServer::processPaymentRequest: Insecure payment request to  "RNu2QkiGVso7BTSbwHQTwoZc3GVewjssXE"
QWARN  : PaymentServerTests::paymentServerTests() PaymentRequestPlus::getMerchant: SSL error:  unable to get local issuer certificate
QWARN  : PaymentServerTests::paymentServerTests() "PaymentServer::verifyNetwork: Payment request network \"test\" doesn't match client network \"main\"."
QWARN  : PaymentServerTests::paymentServerTests() "PaymentServer::verifyExpired: Payment request expired \"1970-01-01 00:00:01\"."
QWARN  : PaymentServerTests::paymentServerTests() "PaymentServer::verifyExpired: Payment request expired \"1970-01-01 00:00:00\"."
QWARN  : PaymentServerTests::paymentServerTests() "PaymentServer::verifySize: Payment request too large (50001 bytes, allowed 50000 bytes)."
FAIL!  : PaymentServerTests::paymentServerTests() Compared values are not the same
   Actual   (PaymentServer::verifyAmount(sendingTo.second)): 1
   Expected (false)                                        : 0
   Loc: [qt/test/paymentservertests.cpp(203)]
PASS   : PaymentServerTests::cleanupTestCase()
Totals: 2 passed, 1 failed, 0 skipped, 0 blacklisted, 80ms
********* Finished testing of PaymentServerTests *********
********* Start testing of RPCNestedTests *********
Config: Using QtTest library 5.9.5, Qt 5.9.5 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 7.3.0)
PASS   : RPCNestedTests::initTestCase()
FAIL!  : RPCNestedTests::rpcNestedTests() 'result == "4a5e1e4baab89f3a32518a88c31bc87f618f76673e2cc77ab2127b7afdeda33b"' returned FALSE. ()
   Loc: [qt/test/rpcnestedtests.cpp(77)]
PASS   : RPCNestedTests::cleanupTestCase()
Totals: 2 passed, 1 failed, 0 skipped, 0 blacklisted, 46ms
********* Finished testing of RPCNestedTests *********
********* Start testing of CompatTests *********
Config: Using QtTest library 5.9.5, Qt 5.9.5 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 7.3.0)
PASS   : CompatTests::initTestCase()
PASS   : CompatTests::bswapTests()
PASS   : CompatTests::cleanupTestCase()
Totals: 3 passed, 0 failed, 0 skipped, 0 blacklisted, 1ms
********* Finished testing of CompatTests *********
********* Start testing of WalletTests *********
Config: Using QtTest library 5.9.5, Qt 5.9.5 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 7.3.0)
PASS   : WalletTests::initTestCase()
QDEBUG : WalletTests::walletTests() TransactionTablePriv::refreshWallet
QDEBUG : WalletTests::walletTests() AssetTableModel::AssetTableModel
QDEBUG : WalletTests::walletTests() AssetTablePriv::refreshWallet
QWARN  : WalletTests::walletTests() This plugin does not support propagateSizeHints()
QDEBUG : WalletTests::walletTests() AssetTableModel::CheckBalanceChanged
QDEBUG : WalletTests::walletTests() AssetTablePriv::refreshWallet
QDEBUG : WalletTests::walletTests() AssetTablePriv::size
QDEBUG : WalletTests::walletTests() AssetTableModel::index( 0 ,  1 ,  QModelIndex(-1,-1,0x0,QObject(0x0)) )
QDEBUG : WalletTests::walletTests() AssetTablePriv::index( 0 )
QDEBUG : WalletTests::walletTests() AssetTablePriv::index --> 0
QDEBUG : WalletTests::walletTests() AssetTableModel::index -->  QModelIndex(-1,-1,0x0,QObject(0x0))
QDEBUG : WalletTests::walletTests() AssetTableModel::index( 0 ,  0 ,  QModelIndex(-1,-1,0x0,QObject(0x0)) )
QDEBUG : WalletTests::walletTests() AssetTablePriv::index( 0 )
QDEBUG : WalletTests::walletTests() AssetTablePriv::index --> 0
QDEBUG : WalletTests::walletTests() AssetTableModel::index -->  QModelIndex(-1,-1,0x0,QObject(0x0))
QDEBUG : WalletTests::walletTests() "NotifyTransactionChanged: cc86cd4819cefbb18199c7c052b0dd71446c8ff607ab26b713e8aca98ac20c00 status= 0"
QDEBUG : WalletTests::walletTests() "NotifyTransactionChanged: 2c69836ab6f509b771dc2bfe8f3ef2b228c80eb935fc07dfe66fb11d54410b58 status= 1"
QDEBUG : WalletTests::walletTests() "NotifyAddressBookChanged: mfWxJ45yp2SFn7UciZyNpvDKrzbhyfKrY8  isMine=0 purpose=send status=0"
QDEBUG : WalletTests::walletTests() "TransactionTablePriv::updateWallet: cc86cd4819cefbb18199c7c052b0dd71446c8ff607ab26b713e8aca98ac20c00 0"
QDEBUG : WalletTests::walletTests() "    inModel=0 Index=0-0 showTransaction=1 derivedStatus=0"
QDEBUG : WalletTests::walletTests() "TransactionTablePriv::updateWallet: 2c69836ab6f509b771dc2bfe8f3ef2b228c80eb935fc07dfe66fb11d54410b58 1"
QDEBUG : WalletTests::walletTests() "    inModel=1 Index=36-37 showTransaction=1 derivedStatus=1"
QWARN  : WalletTests::walletTests() This plugin does not support propagateSizeHints()
QDEBUG : WalletTests::walletTests() "NotifyTransactionChanged: 2c555b6bad378a02b7ebf56176678219d79ad53839a49c255e517b6a118da859 status= 0"
QDEBUG : WalletTests::walletTests() "NotifyTransactionChanged: a0b3a2941ec0b0586de9bbab82839b2af75663cbf69a252ecd9d21570cee1968 status= 1"
QDEBUG : WalletTests::walletTests() "TransactionTablePriv::updateWallet: 2c555b6bad378a02b7ebf56176678219d79ad53839a49c255e517b6a118da859 0"
QDEBUG : WalletTests::walletTests() "    inModel=0 Index=38-38 showTransaction=1 derivedStatus=0"
QDEBUG : WalletTests::walletTests() "TransactionTablePriv::updateWallet: a0b3a2941ec0b0586de9bbab82839b2af75663cbf69a252ecd9d21570cee1968 1"
QDEBUG : WalletTests::walletTests() "    inModel=1 Index=43-44 showTransaction=1 derivedStatus=1"
QDEBUG : WalletTests::walletTests() AssetTableModel::CheckBalanceChanged
QDEBUG : WalletTests::walletTests() AssetTablePriv::refreshWallet
QDEBUG : WalletTests::walletTests() AssetTablePriv::size
QDEBUG : WalletTests::walletTests() AssetTableModel::index( 0 ,  1 ,  QModelIndex(-1,-1,0x0,QObject(0x0)) )
QDEBUG : WalletTests::walletTests() AssetTablePriv::index( 0 )
QDEBUG : WalletTests::walletTests() AssetTablePriv::index --> 0
QDEBUG : WalletTests::walletTests() AssetTableModel::index -->  QModelIndex(-1,-1,0x0,QObject(0x0))
QDEBUG : WalletTests::walletTests() AssetTableModel::index( 0 ,  0 ,  QModelIndex(-1,-1,0x0,QObject(0x0)) )
QDEBUG : WalletTests::walletTests() AssetTablePriv::index( 0 )
QDEBUG : WalletTests::walletTests() AssetTablePriv::index --> 0
QDEBUG : WalletTests::walletTests() AssetTableModel::index -->  QModelIndex(-1,-1,0x0,QObject(0x0))
QWARN  : WalletTests::walletTests() This plugin does not support raise()
QWARN  : WalletTests::walletTests() This plugin does not support grabbing the keyboard
QWARN  : WalletTests::walletTests() This plugin does not support propagateSizeHints()
QWARN  : WalletTests::walletTests() This plugin does not support raise()
QWARN  : WalletTests::walletTests() This plugin does not support grabbing the keyboard
QWARN  : WalletTests::walletTests() This plugin does not support propagateSizeHints()
QWARN  : WalletTests::walletTests() This plugin does not support raise()
QWARN  : WalletTests::walletTests() This plugin does not support grabbing the keyboard
QWARN  : WalletTests::walletTests() This plugin does not support propagateSizeHints()
QDEBUG : WalletTests::walletTests() "NotifyTransactionChanged: b802a4b9a3b1aeaf56a95fa53d084ece81b83173f927710126a2fcc200abf5e8 status= 0"
QDEBUG : WalletTests::walletTests() "NotifyTransactionChanged: a0b3a2941ec0b0586de9bbab82839b2af75663cbf69a252ecd9d21570cee1968 status= 1"
QDEBUG : WalletTests::walletTests() "NotifyTransactionChanged: 2c555b6bad378a02b7ebf56176678219d79ad53839a49c255e517b6a118da859 status= 1"
QDEBUG : WalletTests::walletTests() "TransactionTablePriv::updateWallet: 2c555b6bad378a02b7ebf56176678219d79ad53839a49c255e517b6a118da859 1"
QDEBUG : WalletTests::walletTests() "    inModel=1 Index=38-39 showTransaction=1 derivedStatus=1"
QWARN  : WalletTests::walletTests() This plugin does not support raise()
QWARN  : WalletTests::walletTests() This plugin does not support grabbing the keyboard
QWARN  : WalletTests::walletTests() This plugin does not support propagateSizeHints()
QDEBUG : WalletTests::walletTests() "TransactionTablePriv::updateWallet: b802a4b9a3b1aeaf56a95fa53d084ece81b83173f927710126a2fcc200abf5e8 0"
QDEBUG : WalletTests::walletTests() "    inModel=0 Index=96-96 showTransaction=1 derivedStatus=0"
QDEBUG : WalletTests::walletTests() "TransactionTablePriv::updateWallet: a0b3a2941ec0b0586de9bbab82839b2af75663cbf69a252ecd9d21570cee1968 1"
QDEBUG : WalletTests::walletTests() "    inModel=1 Index=43-44 showTransaction=1 derivedStatus=1"
QDEBUG : WalletTests::walletTests() "TransactionTablePriv::updateWallet: 2c555b6bad378a02b7ebf56176678219d79ad53839a49c255e517b6a118da859 1"
QDEBUG : WalletTests::walletTests() "    inModel=1 Index=38-39 showTransaction=1 derivedStatus=1"
QDEBUG : WalletTests::walletTests() AssetTableModel::rowCount
QDEBUG : WalletTests::walletTests() AssetTablePriv::size
QDEBUG : WalletTests::walletTests() AssetTableModel::columnCount
QDEBUG : WalletTests::walletTests() AssetTableModel::headerData
QDEBUG : WalletTests::walletTests() AssetTableModel::headerData
QDEBUG : WalletTests::walletTests() AssetTableModel::headerData
QDEBUG : WalletTests::walletTests() AssetTableModel::headerData
QDEBUG : WalletTests::walletTests() AssetTableModel::headerData
QDEBUG : WalletTests::walletTests() AssetTableModel::headerData
QDEBUG : WalletTests::walletTests() AssetTableModel::headerData
QDEBUG : WalletTests::walletTests() AssetTableModel::headerData
QDEBUG : WalletTests::walletTests() AssetTableModel::headerData
QDEBUG : WalletTests::walletTests() AssetTableModel::headerData
QDEBUG : WalletTests::walletTests() AssetTableModel::headerData
QDEBUG : WalletTests::walletTests() AssetTableModel::headerData
QDEBUG : WalletTests::walletTests() AssetTableModel::headerData
QDEBUG : WalletTests::walletTests() AssetTableModel::headerData
QDEBUG : WalletTests::walletTests() AssetTableModel::headerData
QDEBUG : WalletTests::walletTests() AssetTableModel::headerData
QDEBUG : WalletTests::walletTests() AssetTableModel::headerData
QDEBUG : WalletTests::walletTests() AssetTableModel::headerData
QDEBUG : WalletTests::walletTests() "NotifyAddressBookChanged: mpRJL8UpXHHhw3Xmnr7xS2dSrJX7YPnx8U TEST_LABEL_1 isMine=1 purpose=receive status=0"
QWARN  : WalletTests::walletTests() This plugin does not support propagateSizeHints()
QDEBUG : WalletTests::walletTests() AssetTableModel::~AssetTableModel
PASS   : WalletTests::walletTests()
PASS   : WalletTests::cleanupTestCase()
Totals: 3 passed, 0 failed, 0 skipped, 0 blacklisted, 995ms
********* Finished testing of WalletTests *********
FAIL qt/test/test_raven-qt (exit status: 1)

**Comment by spyder46n2** [comment]
Thanks for creating this issue.  This is something we are actively working on.  The core functional and unit tests should run clean, some of the other sub-tests haven't been changed from Bitcoin, or know how to handle some of the core Raven changes we've made. I'm actively working to get these all sorted and hope to have a PR for this soon.

**Comment by KyleMcMaster** [comment]
@spyder46n2 Thanks! Glad to hear this issue will be resolved in the future. I am going to try to contribute to fixing some of these tests soonish as well. PM if you have any direction or would like me to review specific issues.

**Comment by spyder46n2** [comment]
This should be resolved on the develop branch as of my latest PR. Let me know if you see any issues...
