### ISSUE TITLE
Ravend on ubuntu1604 ravend: chainparams.cpp:549 Abandon (core dumped)

### ISSUE THREAD

**Issue by VeilleurTrytoFix** [RavenProject/Ravencoin#313]
Hello i got an error on Ubuntu 16.04 for list ravend available parameters

#### If so, please list the steps to reproduce below:
1. wget https://github.com/RavenProject/Ravencoin/releases/download/v2.0.4/raven-2.0.4-x86_64-linux-gnu.tar.gz
2. tar -xvzf raven-2.0.4-x86_64-linux-gnu.tar.gz
3. cd raven-2.0.4/bin
4. ./ravend -h

### Expected behaviour
List of commands available on ravend

### Actual behaviour
myuservm@UBUNTUVM:~/PROJECT/raven-2.0.4/bin$ ./ravend -h
ravend: chainparams.cpp:549: const CChainParams& Params(): Assertion `globalChainParams' failed.
Abandon (core dumped)

### Screenshots.
no gui

### What version of bitcoin-core are you using?
ravend-2.0.4

### Machine specs:
- OS:ubuntu 16.04
- CPU:1
- RAM:1Go
- Disk size:50Go
- Disk Type (HD/SDD):hd

### Any extra information that might be useful in the debugging process.
no logs

maybe i forgot install pre-requisite?

**Comment by spyder46n2** [comment]
Thanks for finding this!  #366 This will be resolved in the soon to come 2.0.1 release.  Once https://github.com/RavenProject/Ravencoin/pull/366 has been merged to develop2 this can be verified.
