### ISSUE TITLE
No info about sender in transaction details (GUI wallet)

### ISSUE THREAD

**Issue by gapeman** [RavenProject/Ravencoin#329]
I noticed that there's no sender info in transaction details. Right now, it just says "_unknown_". Could you fix that? I'm using Windows GUI wallet, v 2.0.4.1.

I think it would also be helpful if you could include block index number for every transaction, and the latest block index number to the "**Overview**" window.

![rvn](https://user-images.githubusercontent.com/42591821/46031367-fa62c700-c0f8-11e8-8db5-199880e8a229.png)

**Comment by blondfrogs** [comment]
At the current moment, this isn't the priority. We will always look at PR's that would fix this issue however
