### ISSUE TITLE
Mac .dmg file issue

### ISSUE THREAD

**Issue by jstep1** [RavenProject/Ravencoin#33]
Hello,

This was an issue brought to attention in a previous ticket (Mac DMG missing or incorrectly named #29) but here is the file in question:

https://github.com/RavenProject/Ravencoin/tree/master/binaries/release/mac

The README.md lists raven.dmg as the primary file to be added to the "Applications" folder on Mac but the only .dmg file on the repo is the one that is linked with the qt.

Could you please review this readme and let us know how to proceed with downloading the wallet from GitHub?

Thanks!

**Comment by jstep1** [comment]
https://github.com/RavenProject/Ravencoin/blob/master/binaries/release/mac/README.md

**Comment by JoshTickles** [comment]
The release DMG is simply called 'Raven-Qt.dmg'.

Download the DMG and open. The disk image will mount. Now simply drag the app into the Applications folder. Job done, you can now launch the app from your Applications folder. 

On first launch you will get a typical macOS warning. To override, right click the app and click 'Open'.

The readme is correct apart from the DMG name but it is pretty self explanatory.

**Comment by jacksonpchen** [comment]
If your question has been answered, please close this issue.
