### ISSUE TITLE
unspecified launch failure

### ISSUE THREAD

**Issue by Happyballz** [RavenProject/Ravencoin#34]
This issue tracker is only for technical issues related to bitcoin-core.

General bitcoin questions and/or support requests and are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).

For reporting security issues, please read instructions at [https://bitcoincore.org/en/contact/](https://bitcoincore.org/en/contact/).

#### If so, please list the steps to reproduce below:
1. start the miner
2. mines for a while then error
3. [2018-02-27 10:10:07] GPU #1: unspecified launch failure
Cuda error in func ‘cuda_check_cpu_setTarget’ at line 41 : unspecified launch failure

### Expected behaviour
continue without error

### Actual behaviour
[2018-02-27 10:10:07] GPU #1: unspecified launch failure
Cuda error in func ‘cuda_check_cpu_setTarget’ at line 41 : unspecified launch failure

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of bitcoin-core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.

### Machine specs:
- OS: windows 10
- CPU: i7-6700
- RAM: 16gb
- Disk size: 240gb
- Disk Type (HD/SDD): SSD

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by MSFTserver** [comment]
this related to ccminer not the wallet id suggest asking in some forums in our community chats for a silution

**Comment by hoidsflute** [comment]
@Happyballz @RavenCoinDev Please close this issue as its unrelated to this repo.  As MSFTserver said, Discord is a great place to ask questions like this.

**Comment by TronBlack** [comment]
Unrelated to this repo.  Please submit to the ccminer repo.

Closing issue.
