### ISSUE TITLE
Wrong date for Asset Activation

### ISSUE THREAD

**Issue by wehard** [RavenProject/Ravencoin#348]
Raven Core wallet shows wrong date for Asset Activation Status.

Tried closing and reopening raven-qt.exe but issue remains.

### Expected behaviour
Asset Activation Status should be 31/10/2018

### Actual behaviour
Date for Asset Activation Status is 31/10/2020

### What version of bitcoin-core are you using?
Raven Core version v2.0.4.1-f55b00aea (64-bit)

### Machine specs:
- OS: Windows 10
- CPU: Intel Core i7 4770K
- RAM: 32 GB
![capture](https://user-images.githubusercontent.com/4597568/46255888-b5011980-c4ab-11e8-899b-faa747c7778a.PNG)

**Comment by mxl86** [comment]
It means that assets will not activate on that version of the wallet until 2020.  A new version of the wallet will be released before the asset launch date, so you will need to update to that version (when available) in order to get assets in October.

**Comment by blondfrogs** [comment]
@wehard We did this on purpose so users that updated to wallet 2.4.0.1 wouldn't interfere with the new 2.1 wallet that will be deployed soon.

**Comment by wehard** [comment]
OK I understand. Thanks for clearingit up.
