### ISSUE TITLE
make fails building with Windows Subsystem for Linux - Ubuntu

### ISSUE THREAD

**Issue by VERTlG0** [RavenProject/Ravencoin#36]
Building native_protobuf...
make[1]: Entering directory '/mnt/c/Crypto/coins/Ravencoin/depends/work/build/x86_64-w64-mingw32/native_protobuf/2.6.1-1d885113350/src'
make[2]: Entering directory '/mnt/c/Crypto/coins/Ravencoin/depends/work/build/x86_64-w64-mingw32/native_protobuf/2.6.1-1d885113350'
 /bin/bash ./config.status
./config.status: line 2321: syntax error near unexpected token `('
./config.status: line 2321: `  for (key in D) D_is_set[key] = 1'
Makefile:626: recipe for target 'Makefile' failed
make[2]: *** [Makefile] Error 2
make[2]: Leaving directory '/mnt/c/Crypto/coins/Ravencoin/depends/work/build/x86_64-w64-mingw32/native_protobuf/2.6.1-1d885113350'
Makefile:1235: recipe for target 'Makefile' failed
make[1]: *** [Makefile] Error 2
make[1]: Leaving directory '/mnt/c/Crypto/coins/Ravencoin/depends/work/build/x86_64-w64-mingw32/native_protobuf/2.6.1-1d885113350/src'
funcs.mk:242: recipe for target '/mnt/c/Crypto/coins/Ravencoin/depends/work/build/x86_64-w64-mingw32/native_protobuf/2.6.1-1d885113350/./.stamp_built' failed
make: *** [/mnt/c/Crypto/coins/Ravencoin/depends/work/build/x86_64-w64-mingw32/native_protobuf/2.6.1-1d885113350/./.stamp_built] Error 2

Following this guide Building for Windows 64 https://github.com/RavenProject/Ravencoin/blob/master/doc/build-windows.md , The make step fails with the above message. NOTE: the build would fail prior because it was missing automake-1.1.4 and because it couldnt find openssl on the system which is installed. Fixed by installing libssl-dev and grabbing the automake-1.14 binary from a new deb source.

**Comment by lukepighetti** [comment]
Did you ever get the Windows wallet to compile? I've been trying the instructions in doc/build-windows.sh and also the Gitian Builder script referenced in doc/release-process.md without luck.

**Comment by TronBlack** [comment]
Many changes have been made to the build for upcoming asset release.   Please re-submit the problem if binaries do not build from master after July 30 2018.

Closing issue.
