### ISSUE TITLE
Very Permissive Unique Asset Name Regex Rules

### ISSUE THREAD

**Issue by hans-schmidt** [RavenProject/Ravencoin#361]
The regex rules limiting unique asset naming in "assets.cpp" are VERY generous, allowing most characters. Moreover, the rules for LEADING_PUNCTUATION, DOUBLE_PUNCTUATION, and TRAILING_PUNCTUATION are not applied. 

Is this really what was intended? 

According to the current rules, `".*"` is a valid unique asset tag. The develop2 client had no problems with letting me create `"LOOKIN4TRUBL#.*"` as a valid unique asset. But then it immediately lost track of it. It does, however, continue to show up in RPC call inquiries and on the web explorer at testnet6 address mgxX3jvjJA2Nc5dkHXG75iRWUAG3DgqTa6

`"LOOKIN4TRUBL#.*"` seems appropriately named.

**Comment by blondfrogs** [comment]
@hans-schmidt I am having trouble duplicating this issue. I am using MacOSX. 
THis is what I see when I created a Unique Asset #.* 
![screen shot 2018-10-05 at 4 03 03 pm](https://user-images.githubusercontent.com/8285518/46562182-2845c980-c8b8-11e8-972f-cc7a0592b847.png)

**Comment by russkidooski** [comment]
also having trouble duplicating this.
![image](https://user-images.githubusercontent.com/25957956/46562350-4e239c00-c8c1-11e8-8ed7-1a5340f38a1a.png)

**Comment by TronBlack** [comment]
We did remove some of the characters that were particularly tricky when working with the command-line -- specifically the pipe character and the greater-than.  If there is something particularly bad about the remaining characters (for unique assets), let us know soon and we'll reconsider them.

**Comment by blondfrogs** [comment]
This isn't an issue
