### ISSUE TITLE
[GUI] Minor issues in QT UI

### ISSUE THREAD

**Issue by Scotty0448** [RavenProject/Ravencoin#372]
The initial Assets dialog is for transferring assets and the Assets dropdown starts with saying "Select an asset to transfer", but the following field for entering the Raven address is labeled "Pay To:" whereas it could be better labeled "Transfer To:".

The Manage Owned Assets button brings up a dialog titled "Reissue Assets". It could be better keeping them consistent, probably titling the dialog as "Manage Owned Assets" as well.

In the Create Asset dialog the Name field has a tooltip saying "A-Z 0-9 and . or _ as the second character" which makes it seem like . and _ can only be the second character rather than any character besides the first or last for main assets and sub assets (but not for unique assets). Understandably the tooltip probably can't be changed easily for different asset types so perhaps the best option is to change it to be just "A-Z 0-9 and . or _" and let the red error message explain as it already does if a . or _ is misplaced.

Finally, within the Create Assets dialog, after clicking the Check Availability button and getting a green "Valid Asset" response, the Create Asset button at the bottom does not change to show it as enabled even though it now is. (In case it matters, I'm testing on an OSX version of QT)

**Comment by blondfrogs** [comment]
Thanks. Love seeing QT changes coming down the line.
