### ISSUE TITLE
unable to type in text fields on pre-built binary 2.1.0 running ubuntu 18.04

### ISSUE THREAD

**Issue by russkidooski** [RavenProject/Ravencoin#378]
i launched the raven-qt and got an error message in console: 
xkbcommon: ERROR: failed to add default include path auto
Qt: Failed to create XKB context!
Use QT_XKB_CONFIG_ROOT environmental variable to provide an additional search path, add ':' as separator to provide several search paths and/or make sure that XKB configuration data directory contains recent enough contents, to update please see http://cgit.freedesktop.org/xkeyboard-config/ .

**Comment by samexner** [comment]
Same issue here with Ubuntu 18.04. Reproducible on my other computer running the same distribution.
Running `export QT_XKB_CONFIG_ROOT=/usr/share/X11/xkb` before running raven-qt seems to temporarily solve the issue.

**Comment by Neofito89** [comment]
> Same issue here with Ubuntu 18.04. Reproducible on my other computer running the same distribution.
> Running `export QT_XKB_CONFIG_ROOT=/usr/share/X11/xkb` before running raven-qt seems to temporarily solve the issue.

thx, it work for me the trick on debian!

**Comment by seanvetter** [comment]
+1

**Comment by russkidooski** [comment]
fixed.
