### ISSUE TITLE
Testnet chain split

### ISSUE THREAD

**Issue by enigma978** [RavenProject/Ravencoin#379]
Up to and including wallet version 2.0.4.1 was testnet4 in directory install wallet. After wallet version 2.1.0.0 became testnet6 and my wallet.dat was clean. After replacing the backup transactions are visible but the balance is zero.

**Comment by russkidooski** [comment]
a new testnet was made due to incompatibilities, your testnetv4 coins will not be on the testnetv6 chain.

**Comment by blondfrogs** [comment]
This isn't a bug correct? Can this issue be closed?

**Comment by enigma978** [comment]
You better know whether it's a mistake or not. But I think it's a mistake. Because the coins are gone and I need to mine the coins again in the new test network to use all the functionality.
