### ISSUE TITLE
Raven token fund raising and 'TOKEN HOLDERS AGREEMENT' - Feature Request

### ISSUE THREAD

**Issue by liqdmetal** [RavenProject/Ravencoin#380]
RVN tokens are going to have a dividend feature.

Therefore, I think it would be prudent to also have a RVN fundraising feature built into the code for the RVN tokens.

Basically it would be a RVN cash call / capital raising feature whereby the TOKEN controller could request  RVN to be sent to his/her wallet from the subsidiary token holders. 

We should also build in basic buyback features for the tokens as well as straight forward Token Holders Agreement" rules that are part of the code. These features will help alleviate future token ownership issues.

**Comment by bedri** [comment]
I think your proposal suggests a global and static smart contract for ICOs. The first thing come to my mind is that does "One smart contract to rule them all!" will work in a broad variety of TOKEN ideas.
This kind of feature eventually will be requested so i am happy that it came forward at the beginning.

**Comment by lsji07** [comment]
A smart contract is not really possible on utxo chains. Utxo records the transctions but doesn't enforce smart contracts or the agreements as such. Hence using trusted issuers is so important. 

Might just be slightly adjusted to better suit part of the utxo model by using a concept similar to dividends but via the future messaging functionality tbc or "request for payment" from specific asset/token holders? Imho that's the closest raven could get without getting into smart contracts... Any other ideas?

**Comment by cfox** [comment]
Messaging and Dividends should give you most of the tools to do this, as well as complying to some sort of metadata standard for assets (issuance ipfs).
