### ISSUE TITLE
RVN wallet 2.1.0.  don't work/install  on Mac OS Sierra

### ISSUE THREAD

**Issue by lonelyminer** [RavenProject/Ravencoin#382]
Hello,
I try to install 2.1.0 wallet  on Sierra, but got "forbidden" sign on Mac during install , same happen  before on 2.0.4  version. Later someone gave me compiled version that works, should we get through this every time Raven team  upgrade wallet?

**Comment by carlzimmerman** [comment]
try high sierra... but i wasnt able to download 2.1.0 wallet either..

**Comment by lonelyminer** [comment]
I am not sure that I will make OS upgrade because of 2.1.0.  RVN wallet , it  should work on Sierra as it worked before.

**Comment by carlzimmerman** [comment]
you can download it but it wont start up..

**Comment by ganzocrypt** [comment]
same issue, cannot install on High Sierra

**Comment by underdarkskies** [comment]
This is due to the build process. Core Please follow the static build guide to build functional dmgs.
For those interested in testing a functional build on Sierra, use at your own risk/discretion: https://github.com/underdarkskies/Ravencoin/releases/tag/v2.1.0

**Comment by lonelyminer** [comment]
It would be nice if some from  Raven core team explain could we use 2.04 after 31.10.2018 ,  and when will have 2.1 version that works on Mac

**Comment by blondfrogs** [comment]
You can't use build 2.04 after 31.10.2018. There have been bug fixes that are in build 2.1.1 that are required for asset to function properly. Could you please try @underdarkskies build to see if it fixes the issue?  https://github.com/underdarkskies/Ravencoin/releases/tag/v2.1.1

**Comment by ganzocrypt** [comment]
I tested 2.1.1 and has the same issue, I open a thread https://github.com/RavenProject/Ravencoin/issues/404

**Comment by underdarkskies** [comment]
@ganzocrypt did you try the dmg from my repo? It uses a different build process that should work on older macOS versions. https://github.com/underdarkskies/Ravencoin/releases/tag/v2.1.1

**Comment by ganzocrypt** [comment]
ok I installed the unsigned version and it's working
thx

**Comment by lonelyminer** [comment]
Unsigned version 2.1.1. working on OSX Sierra.
