### ISSUE TITLE
Error displaying the number of coins

### ISSUE THREAD

**Issue by enigma978** [RavenProject/Ravencoin#391]
Error in displaying the number of received and sent coins in notification Windows, no comma.

**Comment by enigma978** [comment]
I specify that I mean Windows 10

**Comment by Youmadeo** [comment]
I've had the same issue on my PC (Windows 10 - Raven Core version v2.0.4.0-e1a96a0bd-dirty (64-bit))

**Comment by enigma978** [comment]
Sorry, this is for v.2.0.4.0 not for v.2.1.0.0. Close this.
