### ISSUE TITLE
Duplicate Unique IDs Issued

### ISSUE THREAD

**Issue by Scotty0448** [RavenProject/Ravencoin#400]
Using the Qt 2.1.1 console, I was able to issue duplicate Unique IDs in the same transaction. The command used was:

issueunique AMCE2 '["1","1"]'

The txID was 97c9c085e4c34ed83097a6666980da028d5c12e135085f6d8b9e0f69da613065 and the raw transaction output shows two identical new_asset scripts. 10 RVN was also deducted from my account.

**Comment by blondfrogs** [comment]
Thanks for the bug report. We are one this

**Comment by blondfrogs** [comment]
Fixed with commit #9c5993f3724c56d03eaaf62c568de10ac81bab53
