### ISSUE TITLE
RVN   wallet.dat  is damage~~~~~~~~~

### ISSUE THREAD

**Issue by wuwei200000** [RavenProject/Ravencoin#407]
What should I do when I restore my wallet?

**Comment by wuwei200000** [comment]
wallet.dat corrupt, salvage failed

**Comment by TronBlack** [comment]
Use your backup wallet.dat, and copy it into the datadir.

The datadir varies depending on which OS.

Replacement wallet.dat from backup in place of the existing wallet. 

To find datadir, open the qt, hit Help->'Debug window', then [Information] tab, and it will show your Datadir.

**Comment by wuwei200000** [comment]
。。。。。。。。 I have only one backup.。。。。。
wallet.dat corrupt, salvage failed
