### ISSUE TITLE
Receiving address is created even though asset creation fails

### ISSUE THREAD

**Issue by atisvagyok** [RavenProject/Ravencoin#413]
I am running raven-qt on Testnet and just tried to create an asset for the first time. I left the address field blank and tried to create my test asset. My balance was 0 RVN so I got the insufficient balance error message correctly but a new receiving address was created even though the asset creation failed.

I guess we should not create new receiving address if the asset creating fails for some reason.

Raven Core version v2.1.1.0-4f5f87c3d (64-bit)
OS: Ubuntu 18.04

**Comment by underdarkskies** [comment]
Technically the receiving address isn't created, its just displayed from the pre-generated pool of 1000. Not really harmful to display it though.

**Comment by atisvagyok** [comment]
Okay, that sounds better. It is not really harmful just a little bit misleading since an unlabeled address appears in the Receiving addresses section.

**Comment by fokep** [comment]
The address space is practically undepletable. Collisions are theoretically possible but so is the earth getting smashed by an asteroid.

**Comment by atisvagyok** [comment]
I should have highlighted that this is rather a UX issue. I know it will not cause any harm to display an address from the pool, it is just unnecessary when an asset creation fails.

**Comment by blondfrogs** [comment]
Closing as this isn't an issue. As described by underdarkskies
