### ISSUE TITLE
code allows reissue of the asset to the same owner address even when the specs of the asset is same unchanged

### ISSUE THREAD

**Issue by digitalarhm** [RavenProject/Ravencoin#422]
### Describe the issue
 I tried to reissue the same asset to its owner address multiple times with the same spec or parameters. It got successfully reassigned to the same owner address, Should not the code reject any reissue to same owner address with same specs. TX Hash are below.
TX ID - c888d515a2d4b4b97b055e5a5b9302ca9f067db3a4765c3b670a73a307142373
TX ID - ecc21812fe5d0002d2d4aa07d53a13e55bab5dde9c199f95571d500ccaaa75b9
TX ID - ef0302ab4de089dcc6ef24ee4a598fe697fd981e3eeab8d6bb9467775eee5beb

### Can you reliably reproduce the issue?
yes

### Expected behaviour
TX should be rejected if you are reissuing the same specs to the same asset owner address

### What version of Raven wallet?
Testnet - Raven Core version v2.1.1.0-4f5f87c3d (64-bit)

**Comment by cfox** [comment]
No-op reissue is not interesting but valid.  Use the gui to prevent this!
