### ISSUE TITLE
About ICOs and possible scam attempts

### ISSUE THREAD

**Issue by bedri** [RavenProject/Ravencoin#424]
I want to bring forward this issue of scamming attempts. I know we all concern about these kind of actions. Recently I got this article https://cryptovest.com/news/ethereum-developer-introduces-reversible-ico-concept-for-safer-investor-experience/ about stopping ICO scamming in Ethereum.
So maybe we can discuss where are we at the fraud level of assets and stopping them.

This issue can be closed if it's unnecessary but as a paranoid person in sense of security i cannot think any kind of trade of assets legally without considering scam atempts. Let's discuss it here for the discussion may be invisible in discord channel or we can alternatively create a new #subchannel in discord to talk about this.

**Comment by cfox** [comment]
> This issue can be closed if it's unnecessary
