### ISSUE TITLE
About asset name rules and URL specifications

### ISSUE THREAD

**Issue by bedri** [RavenProject/Ravencoin#425]
URL specifications allows URLs in general such that
> http://example.com:1223/some/path?query1=something1&query2=something2#somelabel

We use "#" sign for a specific purpose so i think it should be reconsidered the usage of "#" sign in the asset names with taking the standard URL specifications into account.

The URL's about assets are bind to IPFS metadata files but we know that there are a lot of trials about domain names as main asset names in testnet. If domain names or even URLs like "WWW.EXAMPLE.COM/TEST" are allowed as a subasset name, then why not other standard URL rules are not acceptable for the subasset names or the ones below that level?

I think this should be debated.

**Comment by cfox** [comment]
No plans to change this.
