### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by underdarkskies** [RavenProject/Ravencoin#426]
-----BEGIN PGP MESSAGE-----
Version: BCPG C# v1.6.1.0

hQIMA9yi40QFn4f/ARAAjwpgqbEXqzL9R0M4fcoFpl0MU+XlEOo210pOtQv9VgYq
QxPJp+jdhE4xqBy85GjYuerzg7KLJpScnjUHp5JZr9C+afMrlN//OUmZarytJTEV
rwcKaX+DgWsFL/AFK3FKhCO+BnaCRqIlNnPn7YUHICvkz7RMwEX6XaEAQRqtq2bL
9Jdm6nje2CHi8a6Pq81b9NS6i2Axh3m9HurLd+hPAvwWCyDAW85/OW58KQMwsv9K
SQ1iXbN7Q41VlKTeue+rlUEx0g/jisidTVS8IoRSb/7zFguQ+p58d2jGaPixgrxL
pU25gaE07FYAzjgAAQhmzXS8/RhFtIc+pnxYgz7CKH7/6cn8qZMfh/gX74kNyhc9
4UswabpE63mkv7bE3e0YwqPuLwPyyqVR5mQnc/9qs2gA4X5TmZf1D7IfBZvaldY6
0cSbMxueI7HllAP5vXtc7yL8rsDPbyrtBN894YMTRTOfSkLLxw8nEbe5yGuXuTrc
vqB7YIb2yFRNUbjxjpPNgyKyTxMxvWwfqNgNEVSC5vvyATuC+VlJ8lM/m9tp7Pqj
l4S6SR+c7RK2i+QsIBcgjAUv1EwjAuj0MITfQAlYPrEIJVaHHCJ/gjGkyVvgkAQp
nvYRGXJPkQQITv5Kw8KCgXXNSjT8lD+K8m7xsWn/C82GjHnNBkmwwrGWZwk+06PJ
wq2FBhtXbhx3topvKeW4NosQ8hczalof6A20ggHe5zzskld6vvXgxpdCj9jsiNNu
OiitfW1xCuvTieOi+pK8LvGUYYIqMwi+7xpGPjDJyJnoNPECfqINAuaf47TorvHF
y2G+rh8uPvJOjGrMeA417kXNtVTanE3MB+3xNwLxv2fyyvn8kSGfqeKx93sDbwID
s/Gndas9nnU+ekXiyFDCKv2kDa/IWRW4vMdqjMPw05TJVLtT2QAgEcjZi0K3fb1h
wtvswJsFTl19dreNIFNjdzIvxF63xCd6Eaa29lwHomOgUmGIrSi7Rr2xrZMiqCxE
gM710OQiAYISdmvHEw9Pzr6n1qcRYeBIwQCrnFQe9au7gUf2QIyTYqWAszMutc+Z
FA/DoLyEuopjqxtu5RZPPEIUXO5vaMxBGl7twD8xNv+BhnzEJHc25AWSK3e++hzK
PsLc4B9PSrpX4oTZd+YBc3fk2OfxLb7VuB0336qoqxbKOawe5kE2e46IkwbuoGUQ
Cw8FNIqSV8lD859Qoc71jPBx8i3IXUl2XUf1btb3tERHloDDJCJRDEZVa4bnfwYw
KyLojiojEDiVRa0hY1DGR9Pu9blscmv2MAX72eXJvgtVOJEZjUkeBq2T8PC3SX9R
SF9RZgu/jiLo4KzJSPJyNmlB3pMylsMPs+rrmzBNrz8KFUaXaf/5c/BpiA1f/xfg
NXgCsbtT+os9OTRAPazUOmF4OmqWCZgln4D1eaFna4jPWxCL17TKb7q5mXA3R+6U
h6tuZP9H8Hc4Q6TtrctKl4p/N0AledcBLjl+Fi/Fq2FbeOtQEsAHjHXv6RCjUEFT
YMRvzpi5XGwKv47yPHlyMDI22VPqsgxz1rfxzTWrtsNK9XhY1OwfoR4BVbG+w827
QvbvkpC0UjppW7TXnI5bRVufsDqnyW6ZW7+KBJU7K3Hc6ZRIBW61cULTjbKpqgoF
PVDp7s8bSCx6/XVtx+gItfPOlYTu5SaBcr1qKiDemuJH7KC7xHE0cCwJJTBWbAwo
LBYosDem/vkIeOmGIjQwSZMM+4jgNH8Flbiu/MnZk46NAPTxZ0usrf9JIjylimCf
ZOb7OBpr2xNdMVlA7EyTnh5lsLsvfw3BLJOwUwzdhftoWDQwnGIcRKx+DUu3Rp+9
B4/d66EH+seSbUpc8ZB0
=fXsO
-----END PGP MESSAGE-----

**Comment by underdarkskies** [comment]
-----BEGIN PGP MESSAGE-----
Version: BCPG C# v1.6.1.0

hQIMA9yi40QFn4f/AQ//SLVVXTLRhK9v5zhrLtv2QwCnqhD92t09OEJSKwYmQBIP
6Y8JfM4sKm883ZTQ8FA8YH2QYCZXh16goZIW3DE2z9yu8slFlJkmUP9Wfu4FqDfP
KgMvqiUlsUdyyBCzIyth9ygMDkoIUKpBQO12nDL0i4UAmvXSL15iRrCr6xtvtiK3
TCKZFlk5q/zqlYjaWzUOFyXzb8F1359LFc1Apqx02C57/h3Jyd0BDaPZTamUWQ1n
wbg0/jsYbHecqvrwNp8/DfZkUeT9kEbQHeiOzVpIRoEQS+eRc+ls+xF2RZf64Dhd
vvrDWcsvtvg8tDXkELt2X7MWUveMWIsGAzw8M3TsZV2Cg6T3rVQsc8tTJyRjwp1C
nPRI6NS4ZumhhApmdhDA3W0lJwSTm9FDaQ2cW56pprNQdFV+yk9OmRz8QIXcVaGk
xLHtE7FD2yT8MVbaLIU1E0LGT2Vtyz+psbGAimUXqd3W4KGAwQYvhbRWQKfyhy7m
wfs1NKHSToqVC47GE2QsroEY8HCKKj8Szvs5QHFiDXgb4gXbJ50aAvKjfQe9iWpS
Uz05Ojb46J4PMm81yRNem0ETrlJLO5MAg0uMsOr4ki/SgalBmBx6LtBNfNLTuAJw
TVY1E7KW3gJk9IU4O2fXLfCFAiA0Y1Y8mjwFcHxETQBynM8mYX11W9rG+8vfzLvJ
wIkYvA2legl2Ao3AH4QKpcBsYD5aTGKij6dhDIwWwqU6m799j1j8LSRQ3xNplMle
qA+U99nEGcWA0hz+RENxL+nnRDJMG2+X3WSfsRUGiJB9dtKK9oxou1sQ54CLJQ3g
M/ApZ6AY0apg7AsV3Kta9azi8sjRpvK6MCra/8Wtsz9iuTkvAxJexzCM7q4S/lT3
SxkM/XUGqKNLgT5Po72kgFcRVtZtkCXUQAEuZsJJYBkLl/H9JvP3k+PJGUlwwKxe
O0ROSXzRdXdpjS376E7mIf4ixtg6O4Pea/klASsf2je6bPkg0f7gSS1byMEf3Ei6
YOQCroLy4m8YOty8biN0xZmjWjX5QdPgMCc7/yjtWTRRpBDiBv1NzSJpG+anSzMU
PNiS3cyR0eVj7CQaJM0d9D3pPC3AhqBxuDJIVXIwOayLy7IpoKMu3rah2g==
=4VAc
-----END PGP MESSAGE-----

**Comment by blondfrogs** [comment]
After investigation. THis issue isn't

**Comment by cfox** [comment]
Fix has been implemented and will be released in 3.0
