### ISSUE TITLE
bad-txns-inputs-missingorspent

### ISSUE THREAD

**Issue by ocminer** [RavenProject/Ravencoin#427]
With 2.1.2 *sometimes* you have bad-txns-inputs-missingorspent and getblocktemplate fails completely and thus giving no template until the next block is mined.

Instead of "deadlocking" the coin should simply skip that tx and still give a valid response to getblocktemplate

**Comment by blondfrogs** [comment]
This is a great idea. I was thinking of clearing the mempool if this happens so that future getblocktemplate calls are using a wiped mempool. This will let the chain progress even with some sneaky tx making there way into the mempools.

**Comment by fdoving** [comment]
Fature added in #671 closing.
