### ISSUE TITLE
Windows Defender AntiVirus detecting raven-cli.exe as malware

### ISSUE THREAD

**Issue by bluewookie** [RavenProject/Ravencoin#43]
### Describe the issue
Attempting to download raven-cli.exe from github. Windows Defender quarantines the file.

### Can you reliably reproduce the issue?
Happens 3 out of 3 times for me.

### Screenshots.
![image](https://user-images.githubusercontent.com/9031033/36936811-34c02af2-1ec7-11e8-99cf-2d301dd01798.png)

### What version of bitcoin-core are you using?
Last commit: 8e8ccb76df4cb3d107a0156478fcbca2d4de14ed

### Machine specs:
- OS: Windows 10
- CPU: i7
- RAM: 16GB

**Comment by bluewookie** [comment]
Verified on 2nd PC

**Comment by MSFTserver** [comment]
there's really nothing that can be done I dont think, most if not anything crypto related is flagged as malware now

**Comment by bluewookie** [comment]
Works today.
