### ISSUE TITLE
[GUI] Suggestion: the ability to pick your own colors for the new ui.

### ISSUE THREAD

**Issue by russkidooski** [RavenProject/Ravencoin#437]
As the title says, the ability to pick your color scheme would be nice.

**Comment by metacoin** [comment]
@russkidooski no way - other than night/day mode, there's no example of a good user experience from letting users decide on colors on an app or website. The theme should just work without the user having to tweak it around.

My suggestion: remove complementary colors positioned on top of each other. For example, the orange highlight on the blue icons on the left navigation.

Either change the highlight color (a lighter blue with the same hue and saturation would be nice), or change the icon to white when it's highlighted.

**Comment by MSFTserver** [comment]
tons of libs to avoid that ^

**Comment by wolfsokta** [comment]
Something the community could tackle if interested.

**Comment by cfox** [comment]
no
