### ISSUE TITLE
  Raven: Failed to load Assets Database.

### ISSUE THREAD

**Issue by cbelcher** [RavenProject/Ravencoin#438]
This issue tracker is only for technical issues related to bitcoin-core.

General ravencoin questions and/or support requests and are best directed to the [Ravencoin Discord](https://discord.gg/GwtXdyc).

For reporting security issues, please direct message one of the core developers in discord.

### Describe the issue
Installed Raven Core 2.12, since then I have never been able to fully download the Block chain.

#### If so, please list the steps to reproduce below:
1. Remove Raven Core 2.12
2. rename Raven in the DataDir
3. Install Raven Core 2.12 and let it start start synchronizing
4. Say's it completes, stop the Core and restart.
5. Give me this Error Dialog box: 
     Raven: Failed to load Assets Database.
                 Do you want to rebuild the block database now?
6. Starts all over again, and hangs at like 98%, happened 5 times today, never had an issue before this release.  I'm going to install and older build and see if anything changes.

### Expected behaviour
Should be able to shutdown the core copy my wallet.dat file and fire up the core.  No Errors

### Actual behaviour
5. Give me this Error Dialog box: 
     Raven: Failed to load Assets Database.
                 Do you want to rebuild the block database now?
### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of bitcoin-core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.
v2.1.2.0-gc1544fac9634

### Machine specs:
- OS: Windows 10 Pro
- CPU: Intel Core i7- 6850K
- RAM:  16GB
- Disk size: 512GB
- Disk Type (HD/SDD): SDD

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.
[debug.log](https://github.com/RavenProject/Ravencoin/files/2569006/debug.log)
![screenshot 2018-11-10 16 14 53](https://user-images.githubusercontent.com/4452789/48308362-b0eb0180-e517-11e8-80c4-1595bf160d11.png)

**Comment by cbelcher** [comment]
Just Noticed this on the Core " Asset Activation Status"  Status Waiting and just cycles from 1 to 2016 and back to 1?  Probably related?
![screenshot 2018-11-10 18 58 37](https://user-images.githubusercontent.com/4452789/48308489-04ab1a00-e51b-11e8-987c-0cf9e082f604.png)

**Comment by cfox** [comment]
reindex
