### ISSUE TITLE
Missing shared library upon starting

### ISSUE THREAD

**Issue by Oddly** [RavenProject/Ravencoin#44]
Upon starting any binaries(ravend,raven-cli,raven-qt), I get this error:
"./Linux/ubuntu_17.04/raven-cli: error while loading shared libraries: libevent-2.0.so.5: cannot open shared object file: No such file or directory"

I have libevent-dev installed on ubuntu 17.10, which means libevent-pthreads-2.1-6:amd64 is installed.

**Comment by Serpent6877** [comment]
ln -s /usr/lib/x86_64-linux-gnu/libevent_pthreads-2.1.so.6 /usr/lib/x86_64-linux-gnu/libevent_pthreads-2.0.so.5
ln -s /usr/lib/x86_64-linux-gnu/libevent-2.1.so.6 /usr/lib/x86_64-linux-gnu/libevent-2.0.so.5

**Comment by Oddly** [comment]
Awesome! Simple solution and stupid I didn't figure it out in retrospect.
Thanks for taking the time for this answer.

Op 12 mrt. 2018 23:28 schreef "Serpent6877" <notifications@github.com>:
