### ISSUE TITLE
listassetbalancesbyaddress returns nothing due to cache

### ISSUE THREAD

**Issue by sull** [RavenProject/Ravencoin#445]
This has been discussed in Discord Development channel.

*listassetbalancesbyaddress* fails to reliably return data (apparently due to caching).

In my tests. the wallet that generated an address can query ok but my external wallet on a remote server often cannot retrieve any data via RPC.

**Comment by blondfrogs** [comment]
Fixed in #447

**Comment by buzzdave** [comment]
In the meantime, making a call first to listaddressesbyasset ASSETNAME seems to refresh the cache for listassetbalancesbyaddress (at least for a specific asset I targeted.)
