### ISSUE TITLE
RPC Daemon returns different results from raven-cli

### ISSUE THREAD

**Issue by leshacat** [RavenProject/Ravencoin#449]
### Describe the issue
**raven-cli getblockchaininfo works fine**
```
raven@miningpool:~$ raven-cli getblockchaininfo
{
  "chain": "main",
  "blocks": 436460,
  "headers": 436460,
  "bestblockhash": "0000000000002cec4765cfe4437c0fca351d21d6d6000ac57798c5c63f06422a",
  "difficulty": 88897.43464491959,
  "difficulty_algorithm": "DGW-180",
  "mediantime": 1541487723,
  "verificationprogress": 0.4219018881969352,
  "chainwork": "0000000000000000000000000000000000000000000000021ba9f51d4aae7b99",
  "size_on_disk": 3372933267,
  "pruned": false,
  "softforks": [
  ],
  "bip9_softforks": {
    "assets": {
      "status": "active",
      "startTime": 1540944000,
      "timeout": 1572480000,
      "since": 435456
    }
  },
  "warnings": ""
}
```
**but pool making RPC call to port 19002 (configured raven RPC port) ravend gives the downloading blocks error:**
```
0|pool  | [2018-11-15T18:24:05.000Z] [warn] [ravencoin] [Pool [:1]] : Daemon returned unexpected return code 500, data = "{\"result\":null,\"error\":{\"code\":-10,\"message\":\"Raven is downloading blocks...\"},\"id\":1542306245002}\n"
```

#### If so, please list the steps to reproduce below:
1. pm2 restart pool
2. wait for pool to initiate RPC with daemon
3. see above errors in logs (for ravencoin only, other coins work)

### Expected behaviour
should return blockchain information as raven-cli does

### Actual behaviour
returned downloading blocks error

### What version of bitcoin-core are you using?
"version": 2010000,

### Machine specs:
- OS: Debian 9
- CPU: Dual Core VPS
- RAM: 4096 MB
- Disk size: ???
- Disk Type (HD/SDD): SSD

### Any extra information that might be useful in the debugging process.
Logs above

When I stop the server it returns nothing and I get a connect error. When it starts it works with raven-cli but when requesting blockchain info over RPC it says it still downloading blocks

**Comment by underdarkskies** [comment]
First off update that daemon to 2.1.3, second, doublecheck that the pool software doesn't initialize the daemon with different specs(such as a different config or startup flags) odds are this is a misconfiguration of your pool and when you are querying the daemon via 'raven-cli getblockchaininfo' you are hitting a different instance of the daemon. If thats the case consult your pool software setup.

**Comment by leshacat** [comment]
@underdarkskies 
> First off update that daemon to 2.1.3, second, doublecheck that the pool software doesn't initialize the daemon with different specs(such as a different config or startup flags) odds are this is a misconfiguration of your pool and when you are querying the daemon via 'raven-cli getblockchaininfo' you are hitting a different instance of the daemon. If thats the case consult your pool software setup.

I will update the daemon. There are nicer ways to notify someone of this. You could be less snarkier.

Also, I said the ports were configured to the right ports, so read my posting. Snarky back at you :)

**Comment by underdarkskies** [comment]
Please don’t read snarkiness into my comment. I was simply suggesting you update your pool daemon seeing as that version prevents assets from being added to blocks due to a mempool bug.  Somewhat essential to this chain. Furthermore if you call raven-cli without any switches to specify rpcport then you are connecting on the default port. The code block you showed above specifys no port in it. There for I would assume you are querying a daemon that is fully synced with that command and your pool software is querying another instance of the daemon that is not.

**Comment by leshacat** [comment]
**Maybe my wires got crossed. Sorry :-/**

My understanding is that **raven-cli** checks the config file for the port number and other information needed for login.

**Comment by standard-error** [comment]
raven-cli uses RPC calls to the daemon just like the pool
But I suspect you're comparing two different RPC calls here
The pool is using getblocktemplate vs your getblockchaininfo
The "downloading blocks" error occurs because ravend is still syncing
The error will go away after a while and your pool will (or should) retry

**Comment by wolfsokta** [comment]
@leshacat is this still an issue or can we close this out?

**Comment by leshacat** [comment]
Sorry guys/gals I was busy with family emergency. 

I actually found out the stupid blockchain got stuck downloading... But for some reason when I run getblockchaininfo from the cli it doesnt say "downloading blocks..." anymore it returns the information which is why it confused me.

I will close it and investigate. Will reopen if still issue after full sync.

Sorry again

Thanks!

**Comment by leshacat** [comment]
Confirmed working. Pool back online and port is open :)
