### ISSUE TITLE
Missing core boost lib on Fedora24?

### ISSUE THREAD

**Issue by tchalk** [RavenProject/Ravencoin#45]
I ran the Fedora instructions, and it updated all the boost dependency libs to 1.60, but it seems to be missing the core boost lib?  What am I missing?

[/raven]-->dnf install boost
Last metadata expiration check: 2:27:43 ago on Sun Mar  4 10:06:26 2018.
Package boost-1.60.0-8.fc24.x86_64 is already installed, skipping.
Dependencies resolved.
Nothing to do.
Complete!
[/raven]-->./ravend
./ravend: error while loading shared libraries: libboost_system.so.1.64.0: cannot open shared object file: No such file or directory

From the install:
\==================================================================
 Package                    Arch        Version              Repository    Size
\==================================================================
Installing:
 boost                      x86_64      1.60.0-8.fc24        updates       45 k
 boost-atomic               x86_64      1.60.0-8.fc24        updates       47 k
 boost-chrono               x86_64      1.60.0-8.fc24        updates       53 k
 boost-context              x86_64      1.60.0-8.fc24        updates       61 k
 boost-coroutine            x86_64      1.60.0-8.fc24        updates       61 k
 boost-graph                x86_64      1.60.0-8.fc24        updates      138 k
 boost-locale               x86_64      1.60.0-8.fc24        updates      278 k
 boost-log                  x86_64      1.60.0-8.fc24        updates      434 k
 boost-math                 x86_64      1.60.0-8.fc24        updates      310 k
 boost-program-options      x86_64      1.60.0-8.fc24        updates      165 k
 boost-python               x86_64      1.60.0-8.fc24        updates      128 k
 boost-regex                x86_64      1.60.0-8.fc24        updates      298 k
 boost-serialization        x86_64      1.60.0-8.fc24        updates      149 k
 boost-signals              x86_64      1.60.0-8.fc24        updates       71 k
 boost-test                 x86_64      1.60.0-8.fc24        updates      238 k
 boost-timer                x86_64      1.60.0-8.fc24        updates       52 k
 boost-type_erasure         x86_64      1.60.0-8.fc24        updates       60 k
 boost-wave                 x86_64      1.60.0-8.fc24        updates      221 k
 libdb4                     x86_64      4.8.30-20.fc24       fedora       615 k
 libdb4-cxx                 x86_64      4.8.30-20.fc24       fedora       644 k
 libquadmath                x86_64      6.3.1-1.fc24         updates      181 k
 libsodium                  x86_64      1.0.12-1.fc24        updates      176 k
 miniupnpc                  x86_64      2.0-1.fc24           updates       51 k
 openpgm                    x86_64      5.2.122-6.fc24       fedora       175 k
 zeromq                     x86_64      4.1.4-5.fc24         fedora       555 k
Upgrading:
 boost-date-time            x86_64      1.60.0-8.fc24        updates       60 k
 boost-filesystem           x86_64      1.60.0-8.fc24        updates       76 k
 boost-iostreams            x86_64      1.60.0-8.fc24        updates       69 k
 boost-random               x86_64      1.60.0-8.fc24        updates       52 k
 boost-system               x86_64      1.60.0-8.fc24        updates       50 k
 boost-thread               x86_64      1.60.0-8.fc24        updates       91 k

Transaction Summary
\================================================================
Install  25 Packages
Upgrade   6 Packages

**Comment by bedri** [comment]
This is caused by the version of libboost that compiled binary of Ravencoin requires. You should compile from source code. You may get error for miner.h and txmempool.h files which I fixed and made a pull request [here](https://github.com/RavenProject/Ravencoin/pull/32) - #32.

**Comment by bedri** [comment]
Version of libboost library files required in the binary files of Ravencoin and the ones exist in your system are different so Ravencoin binaries giving the error of not finding the libraries.

**Comment by bedri** [comment]
You should use the [instructions here](https://github.com/RavenProject/Ravencoin/issues/5#issuecomment-355771348) to compile and run the correct executable that is compatible with your system. After installation you will find the raven-qt executable under src/qt directory relative to the cloned Ravencoin directory.
