### ISSUE TITLE
win32 cross compilation error

### ISSUE THREAD

**Issue by wkibbler** [RavenProject/Ravencoin#460]
keep getting this issue when trying to cross compile for win32 from ubuntu 14.04

/usr/share/mingw-w64/include/winbase.h:414:0: note: this is the location of the previous definition
 #define THREAD_PRIORITY_ABOVE_NORMAL (THREAD_PRIORITY_HIGHEST-1)
 ^
In file included from support/allocators/secure.h:10:0,
                 from key.h:12,
                 from base58.h:19,
                 from httprpc.cpp:8:
./support/lockedpool.h:196:18: error: ‘mutex’ in namespace ‘std’ does not name a type
     mutable std::mutex mutex;
                  ^
./support/lockedpool.h:229:17: error: ‘once_flag’ in namespace ‘std’ does not name a type
     static std::once_flag init_flag;
                 ^
./support/lockedpool.h: In static member function ‘static LockedPoolManager& LockedPoolManager::Instance()’:
./support/lockedpool.h:216:9: error: ‘call_once’ is not a member of ‘std’
         std::call_once(LockedPoolManager::init_flag, LockedPoolManager::CreateInstance);
         ^
./support/lockedpool.h:216:24: error: ‘init_flag’ is not a member of ‘LockedPoolManager’
         std::call_once(LockedPoolManager::init_flag, LockedPoolManager::CreateInstance);
                        ^
Makefile:6356: recipe for target 'libraven_server_a-httprpc.o' failed
make[2]: *** [libraven_server_a-httprpc.o] Error 1
make[2]: Leaving directory '/home/******/Desktop/Ravencoin/src'
Makefile:10556: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/******/Desktop/Ravencoin/src'
Makefile:750: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
******@******-VirtualBox:~/Desktop/Ravencoin$

**Comment by standard-error** [comment]
With mingw there are two different threading models: posix and win32. You need to use posix

You can change that by running

`sudo update-alternatives --config x86_64-w64-mingw32-g++`

and there should be a 'posix' option there

**Comment by wkibbler** [comment]
I tried that, still got the same issue

**Comment by standard-error** [comment]
Ok, I'm awake now. If you're trying to do a 32 bit build that would be
`i686-w64-mingw32-g++` and `i686-w64-mingw32-gcc`

rather than x86_64

Posix threads are the issue, though

**Comment by wkibbler** [comment]
me being an idiot, not quite with it lol, thanks anyway
