### ISSUE TITLE
A block chain backed Tethered Asset (TA) proposal for Ravencoin

### ISSUE THREAD

**Issue by ypey** [RavenProject/Ravencoin#462]
### The issue:
We all know the usefulness of a tethered token in crypto trading, namely to hatch against market volatility without having to exit the digital crypto sphere. This usefulness applies just as much to raven dividend payments or raven assets trading. Known solutions are the TA's backed by a company like Tether and Bitfinex. This solution could be implemented into a Raven asset instantly, but it still involves third party trust while we just like it when code is law. Another approach is the smart contract Maker/Dai on Etherium. This is a code heavy and participation heavy solution, but it is autonomous and trustless. There are other solutions like the TA proposal on the Burstcoin network. A raven is a smart bird and Raven wouldn't be Raven if it didn't try to incorporate the major use cases of other crypto into the heart of its lean and mean bitcoin protocol. Like it does with assets, dividends, messaging, fast transaction time and asic resistance. We are early in the project and i think now is the time to start thinking about the trustless tethered asset use case for Raven!

### The proposal:
The initial proposal here is a relatively straight forward and easy to understand solution that would require a hard fork and some major psychological barriers, but i feel it might be worth it. We might be at the right place at the right time for this. We want a TA backed by the raven blockchain code where 1TA=1$ or at least where 1TA will return to its value of 1$ quickly. The devil is in the details but here is the main idea:

**Proposal;** a TA dollar is created out of thin air and send to a specified address by sending the equivalent exchange rate worth of RVN to a special burn address. The reciprocal; a TA dollar can be send to this special burn address and its equivalent exchange rate worth of RVN are created out of thin air and send back to a specified address.

After creation a TA is a normal raven asset and can be send and spend like all other assets. The TA is meant to be used and circulated, not meant to be burned back to RVN. The TA-burn is there merely to secure trust in its minimum value of 1$. The reciprocal is also true; the TA-creation is securing trust in its maximum value of 1$. All miners need to agree on a list of API's and the used algorithm to determine a valid current exchange rate in order to validate the creation/burn transaction. The used exchange rate is recorded on the blockchain. 

### The stability issue:
Now for the devil and the security details: This principle of TA creation and burning is prone to manipulation and coin dilution when it is not bounded within strict stability rules. Furthermore the introduction of stability rules will in practice loosen the strict peg of the TA and will make it hover around the 1 dollar value. Stability rules can be categorized as value boundaries or time boundaries and these can either be absolute or relative. I will expand the reasoning later but here is the TL;DR:

- Stability rule 1: a maximum of 1000RVN worth of tethered assets can be burned and created per block.
- Stability rule 2: no more new TA's can be created when the TA market cap exceeds 10% of Ravencoin.

### Expected behaviour:
At first sight there are not much reasons to restrict the creation of new TA's. The process of TA creation has a deflationary effect on the Ravencoin value because of RVN burn. It is to be expected that the demand for more TA's is the highest when the exchange rate for Raven comes from a relatively high value and is going into a down trend. The deflationary effect of TA creation dampens this downtrend and has therefore a counter cyclical effect. The same applies for TA burning: we can expect this to be highest when Ravencoin comes from a relatively low value and is going into an up trend. The inflationary effect of creating new RVN will dampen this up trend and is therefore also a counter cyclical effect. This is all positive for the stability of the ravencoin value. 

The main argument for restricting the TA creation is the solvency of the whole blockchain; the ratio of its market capitalization against the TA liabilities. Swings of 50% in market capitalization is extreme but not uncommon in crypto. This means that a total TA value of 20% of the total market capitalization would turn into 80%. This is huge and to be more conservative i would double the stability and choose a maximum of 10% for now. As a testcase you can start with a much lower percentage and reviewed the value after prove of concept. The calculation for the rule can be done over a longer term average like 24h and/or using the last 10 transactions with a recorded exchange rate on the blockchain. This is to minimize direct market manipulation to escape the rule. When the popularity of the TA may end up exceeding the use case of raven itself, this 10% limit rule may also be an upward force for the raven price itself as the underlying supporting network.

Speaking of manipulation: Imagine a large investor having enough recourses to pump the raven price for a short period while at this peak creating large amounts of new relatively cheap TA's. A hard limit to the TA creation per block will minimize this problem. This stable coin is meant for long term purposes not for short term market manipulation so it is good to take the speed out of its creation and burn. Still the main psychological hurdle will be this mechanism of creating new RVN. This is potentially inflationary to the Ravencoin value and a necessary evil. Lets say we would like to guarantee that the dilution always stays well below 2,5% yearly of the maximum of 21 billion coins. This is a hard limit of 525 million per year, 1.4 million per day and 1000RVN per block. We will further limit the real dilution by making it an absolute limit of 1000RVN per block. So every block missed to create RVN is lost for ever and means less dilution for the blockchain. Also the real dilution will be many times smaller because for every RVN created there have been a similar amount of RVN burned in the first place. Furthermore if we expect the whole value of the Ravencoin blockchain to grow in the future, this would mean that more and more TA's will be created and more and more RVN will be burned and the net result will be extremely deflationary instead of inflationary. 

### Actual behaviour:

More discussion needed....

Cheers, 
Ypey

**Comment by cfox** [comment]
Great idea but not applicable here -- go forth and conquer.
