### ISSUE TITLE
Please explain rational for QT upgrade

### ISSUE THREAD

**Issue by underdarkskies** [RavenProject/Ravencoin#473]
LTS version of QT is version 5.12 not 5.11
support for 5.11 ends in March of 2019
5.9 remains LTS hence why its used in bitcoin
version 5.11 and up have a known bug with openssl 
@cfrogjump

**Comment by cfrogjump** [comment]
The rational is to address bugs in the new interface and OS X Mojave. We'd like to update to 5.12 but no testing has been done on 5.12 whereas all of @blondfrogs efforts have all been on 5.11.2, hence the attempt at getting it to work. We will be releasing using 5.9.7 which addresses the major font issue but introduces a odd gradient bug. We will then work on getting updated to 5.12 which seems to resolve the gradient issue.
