### ISSUE TITLE
menu toggle

### ISSUE THREAD

**Issue by MSFTserver** [RavenProject/Ravencoin#478]
add a toggle option to only show menu icons to save space and make it cleaner when in smaller window size as some things gets distorted.

_Sent from my Galaxy Note5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by jeroz1** [comment]
Links to images don't work for me. _"Non-Image content-type returned"_

**Comment by MSFTserver** [comment]
@jeroz1 wierdd stupid discord

**Comment by fdoving** [comment]
Something like this?

![image](https://user-images.githubusercontent.com/26197922/119564741-6c5ba480-bda9-11eb-8453-61e364df62f9.png)

**Comment by lsji07** [comment]
This works on Windows 10 using Raven Core version v4.7.0.0-b5010492c (64-bit).

The distortion mentioned still occurs but to a lesser degree once the fix #1030 is applied. Recent Transactions gui handling needs further investigation in #1127

**Comment by soullesscomputerboy** [comment]
This works in linux mint with core v4.7.0.0-b5010492c (64-bit) on my 1366x768 screen. I don't see any distortion.

**Comment by m4r1m0** [comment]
Tested and working on Ubuntu 20.04 using raven-4.7.0test3-b5010492c (64 bit). 1600x1200. 

Icons look clean, no distortion. The mouseover dialogue for "create assets" is incomplete in terms of what asset types can be created but that is a minor/non-issue.

**Comment by fdoving** [comment]
Thanks. Would be nice if you can create a separate issue on the mouse-over.

**Comment by fdoving** [comment]
3x confirmed. Closing.

**Comment by fdoving** [comment]
Proposed fix for the mouse-over issue: https://github.com/RavenProject/Ravencoin/pull/1138

**Comment by HyperPeek** [comment]
Closed as fixed in #1030
