### ISSUE TITLE
Integrate the latest supported QT (5.12) to address Mojave Font issues

### ISSUE THREAD

**Issue by wolfsokta** [RavenProject/Ravencoin#482]
There are several issues with Mojave and QT with the UI enhancements we have been making.

**Comment by spyder46n2** [comment]
Manual build process to get here, but proof that QT 5.12.0 can be compiled, and Raven can be compiled against it.  Now to integrate it into the dependency build processes...
![image](https://user-images.githubusercontent.com/33036650/50022564-d6957b80-ff99-11e8-8f85-614b0f80bc34.png)

**Comment by fdoving** [comment]
Fixed with #922
