### ISSUE TITLE
[Request] User friendly feature that resets the chain files for wallets that stopped syncing.

### ISSUE THREAD

**Issue by jeroz1** [RavenProject/Ravencoin#486]
Almost on a daily basis, users report that their wallet stopped syncing. I am fully aware that this could be caused by multiple reasons but in many cases they are connected to up to date nodes and adding more nodes does not help their case. 

As it might be that their blockchain may have ended on a forked chain (or theirs got corrupted), the easiest way to get back on track is clearing out blockchain files and re-downloading the chain from scratch. Currently, that option is insanely user unfriendly. Users have to
1) close the wallet, 
2) look up where these files are (hidden folder by default), 
3) manually delete the files, 
4) make sure they don't accidentally erase wallet.dat, and
5) start their wallet again. 

I think it would be far more user friendly if the raven core wallet would notice that it is not syncing and/or would have a menu option to safely clear/reset the blockchain to get it back up and running.

**Comment by jeroz1** [comment]
![wallet_repair](https://user-images.githubusercontent.com/44138303/50058262-b30e3480-0143-11e9-86e4-84385265543f.png)
I found this functionality in Dash Core. It is exactly what I what I would like to request.

**Comment by TronBlack** [comment]
This is a good idea.

**Comment by jeroz1** [comment]
I'd like to add the idea of an (optional) wallet Groomer for people who constantly run into "transaction too large" messages.

**Comment by jeroz1** [comment]
https://github.com/RavenProject/Ravencoin/pull/570
