### ISSUE TITLE
[Suggestion] A p2p WTS and WTB smart client

### ISSUE THREAD

**Issue by sudux** [RavenProject/Ravencoin#490]
update 2019.3.6

I have a new idea...

A p2p WTS and WTB smart client.

Someone create a unique asset XXX#WTS_100_AAA_1_BBB. And send it to RXissueAssetXXXXXXXXXXXXXXXXXhhZGt.

All the client will get this message "WTS_100_AAA_1_BBB" from RXissueAssetXXXXXXXXXXXXXXXXXhhZGt. If someone want AAA, he can send 50 BBB to the issuer address and he will get 50 AAA.

A smart client can do this: (client a and b are same client)

1. If someone need to sell asset, he should create XXX#WTS_100_AAA_1_BBB. 

2. Client A will transfer 100 AAA asset and some rvn to the issuer address. 

3. Client A  will send XXX#WTS_100_AAA_1_BBB to RXissueAssetXXXXXXXXXXXXXXXXXhhZGt for broadcasting when 100 AAA is in the issuer address.

4. All the client B will get this message "XXX#WTS_100_AAA_1_BBB". The message is available for 1 
 minutes. All the client B can check the issuer address if client A is online and how many AAA left.

5. Client A need to send small rvn to RXissueAssetXXXXXXXXXXXXXXXXXhhZGt every 30 second to make sure it is online.

5. If someone want AAA, he can send 50 BBB to the issuer address.

6. Client A will check the chain if the issuer address get BBB. Then client A send 50 AAA to the sender address.

7. This smart client will sync the chain and keep processing the WTS and WTB message.

I think this is better than atom swap because there are a message list that we do not need to know each other. 

update 2019.2.4

There is a game called Ragnarok Online （RO）. This game is interesting because there is a tool called openkore to play command out of the client.

If a player want to sell some items, he create a txt file, like this

item  price amount

The following example will create a shop called "My Little Shop", with all Steel that you have in cart, for 39z each, and two Andre Cards, for 150,000z each.

My Little Shop
Steel	39
Andre Card	150,000	2

http://openkore.com/index.php/Shop.txt

open openkore and input openshop

then some players want to buy the items, he can input command like this

input vl to list vender (http://openkore.com/index.php/Vl)

vl

-----------Vender List-----------
    Title                                Coords     Owner
0   My Little Shop              (227,  48)    Top-Sales4
----------------------------------

then enter the vender shop (http://openkore.com/index.php/Vender)

vender 0

--------------------------- Vender: Top-Sales4 (2) ----------------------------
  Name                                      Type           Amount       Price
3   Steel                                                            100               39z
4   Andre Card                                 		2                    150,000z
-------------------------------------------------------------------------------

Buy the Steel

vender 0 3 1  

Game item is also asset. Rvn assets like online game items. 

If rvn wallet could add an auto send assets ticket list  like shop list, asset owner coud create a rule to auto send assets or rvn when wallet is running.

No wallets could do this before, because they are no asset.

For example:

wallet owner create a txt file

ebookstore

bookstore/a/apple_book 1
bookstore/b/banana_book 3
bookstore/z/zion_book for 5

run the wallet with ip 1.1.1.1

every could check the Vender Shop like this:

vl 1.1.1.1

--------------------------- Vender: ebookstore 1.1.1.1 (3) ----------------------------
#   Name                                      Type           Amount       RVN  
3   bookstore/a/apple_book                             100               1
4   bookstore/b/banana_book                            50               3
5   bookstore/z/zion                           		    20               5
-------------------------------------------------------------------------------

buy 20 apple_book

vender 1.1.1.1 3 20

done.

Everyone can send 1-5 rvn to the bookstore ip address to get book with ipfs link when the bookstore wallet online.

there are also many ways...

1. Send any rvn or assets to get 1 or N rvn or asset.

Create a new address.

If this address get any rvn,  the wallet will auto send 1 asset to the the sender.

The sender's address can be found with decoderawtransaction.

If this address get any asset or specific asset ,  the wallet will auto send 1 rvn or asset to the the sender.

2. Send 1 or N rvn or assets to  get 1 or N rvn or asset.

Create a new address.

If this address get 1 or N rvn,  the wallet will auto send 1 asset to the the sender.
If this address get 1 or N asset or specific asset ,  the wallet will auto send 1 rvn or asset to the the sender.

Every wallet will be an asset shop for sending or receiving assets (rvn). ^^

**Comment by cfox** [comment]
No plans for DEX in protocol but go build something awesome!
