### ISSUE TITLE
[Request] send rvn or assets to asset name (asset issuer)

### ISSUE THREAD

**Issue by sudux** [RavenProject/Ravencoin#492]
No wallets could do this before, because they don't have  assets. But rvn can do this.

Almost all wallet addresses are difficult to remember, few coins support name to address like Gbyte/Pasc.

Rvn asset address is also rvn address. If someone create an asset, he can ask someone to send rvn to his asset name. A name is better than an address for daily use.

**Comment by MSFTserver** [comment]
theres different ways to go about this and using an asset name doesnt sound like the right path to me as most those would entail a real world usecase, i could see some issies coming from people getting confused if it is asset or just an alias gor the address

**Comment by sudux** [comment]
> theres different ways to go about this and using an asset name doesnt sound like the right path to me as most those would entail a real world usecase, i could see some issues coming from people getting confused if it is an asset or just an alias for the address, also would be ideal to find a cheaper option for aliases
> 
> _Sent from my Galaxy Note5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_


Thanks for replying^^.

Blockchain is also a database. The blockchain address didn't exist 10 years ago. I was one of the people got confused about the 34 characters address when I began to use wallet. The address is too long but it not means it should be long. I think the 34 characters address confuse people first, we accept this address because we have to and no choice... I am sure everyone like using short address and easy to remember.

RVN is a great project in the 10 years blockchain history and the world need long time to understand how great are coming. Bitcoin is a database with numbers. RVN is a database with words. We all know the words are asset now. But the asset is only a tool about how to use the words. RVN are digitizing the world to blockchain and will digitize everything.

If someone wants to send rvn to an asset name now, he need to open ravencoin.asset-explorer.net and search the asset name to get the issuer address. They can do this by themself. They can add the address to the address book later. I understand if wallet support this, some people will confuse with asset and address or account.

Actually, the number of the addresses with asset are only 35K+(not include / and #). The number of top 1 asset addresses ravencoincash is 9K+. The number of top ten asset addresses hug is only 150. I think these address holders are smart to create and collect assets. But we need more people to use assets because assets are better than before. RVN will change the world better. The asset can be more useful for people. Asset is a rvn address. Address/account can also be an asset to accept or send rvn. Everything could be a rvn asset. Asset should not be limited to be everything.

I think we can call this smart asset. :)

If someone wants others to know his rvn account, he can type rvn:xxx or rvn:xxx.com or rvn:editor/xxx or rvn:steve#xxx. He can create as many assets as he can for every use. He doesn't need to copy his 34 characters address anymore. I think this is very very useful.

I suggest wallet can mark every issuer address like an address book. When someone input an asset name for sending rvn, the wallet will send rvn to the asset issuer address. This is a choice. Not all People have to understand because they can still send 34 characters address. Nothing changed. We are hard to do something we don't understand. But we like to trust someone we believe and this is growing. The account asset issurs will teach their fans how to use asset name to send rvn.

Let address easy use again.:)

**Comment by ypey** [comment]
Great idea! This helps user friendliness which is of major importance to gain mass adoption. Tech people in crypto always underestimate the importance of this aspect! This feature would be relatively easy to implement in any wallet.

cheers

**Comment by cfox** [comment]
use accounts or something?
