### ISSUE TITLE
RPC calls resulting in unresponsive node

### ISSUE THREAD

**Issue by RealBokito** [RavenProject/Ravencoin#499]
It seems that multiple users with the raven core software are experiencing issues with regards to its responsiveness and performance. So, I am opening a new issue, this way we can all look at it and go over it as a group.

My problems started on a VM with Win2K8-64 and Raven QT 2.0.3. High CPU and memory usage. At some point things went sideways and i had to shutdown my asset explorer.
I have tried to setup a new node on Ubuntu Server 18.04.1 LTS with Ravend 2.2.0.0. When fully synced, the node would be available for either a few minutes or hours until it became unresponsive, again. At other times the node became unresponsive after just a few RPC calls (getblockchaininfo) and would experience high CPU en memory usage.
I am currently setting up a new node with Ubuntu Server 18.04.1 LTS and Ravend 2.1.3.0. Will give an update in the next few days.

Update:
Some links from BTC's Github:
https://github.com/bitcoin/bitcoin/issues/15148
https://github.com/bitcoin/bitcoin/issues/15015

**Comment by jeroz1** [comment]
I can add that I see an increasing number of complaints on all social media channels (twitter/reddit/telegram/discord).

**Comment by cryptozeny** [comment]
I have similar issue. If the mining pool requests an RPC call very often, the node will not respond. It's a custom coin, but bitcoin v0.16.3 based.

**Comment by RealBokito** [comment]
Have been testing with ravencoin version 2.2.2 provided by Jeroz. So far, the fixes for the sync issues seem to have an positive effect on RPC calls as well. Have been stress testing Ravend for three days without any big issues.

**Comment by cryptozeny** [comment]
@RealBokito What have you fixed?

**Comment by jeroz1** [comment]
@cryptozeny, @RealBokito refers to changes documented in https://github.com/RavenProject/Ravencoin/pull/503.

**Comment by RealBokito** [comment]
That document that @jeroz1 mentioned and some settings in the conf file, mainly dbcache. and some RPC related settings.

**Comment by blondfrogs** [comment]
Closing as version 2.2.2 seems to fix this issue.
