### ISSUE TITLE
Build guide builds bitcoin core client, not raven?

### ISSUE THREAD

**Issue by braydo25** [RavenProject/Ravencoin#5]
Hey guys, I'm following this guide to the T (https://github.com/RavenProject/Ravencoin/blob/master/doc/build-unix.md). Everything goes through fine, runs fine - but I'm not seeing raven-qt anywhere, however it did build bitcoin-qt? This is the first time I've compiled a client from scratch so is there anything specific that's not in this guide that I need to do in order to build the raven-qt client?

**Comment by RavenCoinDev** [comment]
What OS are you compiling for? I'd like to try and reproduce the problem you are seeing.

**Comment by braydo25** [comment]
Raspbian 😅

**Comment by braydo25** [comment]
Same issue following https://github.com/RavenProject/Ravencoin/blob/master/doc/build-unix.md on my Ubuntu PC.

**Comment by RavenCoinDev** [comment]
@braydo25 

To build on ubuntu 16.04, I install the following packages:

> apt-get update && apt-get install -y software-properties-common
> 
> add-apt-repository ppa:bitcoin/bitcoin
> 
> apt-get update && apt-get install -y automake autotools-dev bsdmainutils build-essential git libboost-all-dev libdb4.8-dev libdb4.8++-dev libevent-dev libminiupnpc-dev libprotobuf-dev libqrencode-dev libqt5gui5 libqt5core5a libqt5dbus5 libssl-dev libtool libzmq3-dev pkg-config protobuf-compiler python3 qttools5-dev qttools5-dev-tools 

and then run the following commands to build it:

> git clone https://github.com/RavenProject/Ravencoin.git
> 
> cd Ravencoin
> 
> ./autogen.sh
> 
> ./configure --enable-cxx --disable-shared --with-pic --prefix=$BDB_PREFIX CXXFLAGS="-fPIC" CPPFLAGS="-fPIC"
> 
> make

**Comment by cgarnier** [comment]
Hey @RavenCoinDev 
I followed the steps and i got:
```
/usr/bin/ld: crypto/libraven_crypto.a(crypto_libraven_crypto_a-blake.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
crypto/libraven_crypto.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
Makefile:3835: recipe for target 'ravend' failed
make[2]: *** [ravend] Error 1
make[2]: Leaving directory '/home/clement/rvn/Ravencoin/src'
Makefile:9947: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/clement/rvn/Ravencoin/src'
Makefile:747: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```

**Comment by braydo25** [comment]
I'm getting the same as @cgarnier

**Comment by cgarnier** [comment]
Could you make a dockerized wallet ?

**Comment by cgarnier** [comment]
I m working on a docker wallet, compiling wallet is always a mess.
@braydo25 I found a way, this is my dockerfile. I will publish it when it will be cleaner.
It should help you.
```Dockerfile
FROM ubuntu:16.04
RUN apt-get update && apt-get install -y software-properties-common && \
  apt-get install -y \
  software-properties-common \
  build-essential \
  libtool \
  autotools-dev \
  automake \
  pkg-config \
  libssl-dev \
  libevent-dev \
  bsdmainutils \
  python3 \
  libboost-system-dev \
  libboost-filesystem-dev \
  libboost-chrono-dev \
  libboost-program-options-dev \
  libboost-test-dev \
  libboost-thread-dev \
  libboost-all-dev \
  git

RUN add-apt-repository ppa:bitcoin/bitcoin && \
  apt-get update && \
  apt-get install -y libdb4.8-dev libdb4.8++-dev

RUN git clone https://github.com/RavenProject/Ravencoin.git /app

RUN cd /app && \
  ./autogen.sh && \
  ./configure CXXFLAGS="-fPIC" CFLAGS="-fPIC" --enable-cxx  && \
  make && \
  make install
```

**Comment by mymuzk** [comment]
make clean
./configure CFLAGS=-fPIC CXXFLAGS=-fPIC
make
