### ISSUE TITLE
Investigate chain Sync Speed

### ISSUE THREAD

**Issue by blondfrogs** [RavenProject/Ravencoin#501]

**Comment by DarrenTa** [comment]
@blondfrogs 
I believe there is a memory leak which contributes to the slow sync.  

Report:  
Syncing blockchain on local machine with raven-qt, memory usage would creep up to over 20% (of 8GB) upon restart, chain syncs faster and memory usage is less.  

Syncing blockchain with ravend on Debian 9 digital ocean 4GB machine.  Left it overnight, when returned memory usage was 42%.  I stopped and started the node, now memory usage is 22%.

Future test.  I will sync my local machine with a persistent connection to remote node.

**Comment by jeroz1** [comment]
Is this with 2.2.1 that was released yesterday? @blondfrogs addressed a potential memory leak in that version as well. See for more details: https://github.com/RavenProject/Ravencoin/pull/500

**Comment by DarrenTa** [comment]
I installed yesterday, but this was with 2.2.0.0

**Comment by DarrenTa** [comment]
Now trying with 2.2.1.0

Much better!!!  No issue.  Sync seems to work as expected.

**Comment by blondfrogs** [comment]
Fixed in #503
