### ISSUE TITLE
[Help] compiling in windows

### ISSUE THREAD

**Issue by MSFTserver** [RavenProject/Ravencoin#502]
im trying to compile this on my windows machine, im having trouble getting the Boost libs to work correctly the configure.ac finds my boost and claims it using it but when i get to making the program it gets to `standard.h` and fails on `#include <boost/variant.cpp>` - no file or dir found

```
checking for boostlib >= 1.47.0... configure: We will use a staged boost library from /C/Users/MSFTserver/Desktop/raven_tests/sync/lib/boost_1_55_0
yes
```

screenshot of error - ![img](https://cdn.discordapp.com/attachments/429133749867905024/536156341589508107/unknown-8.png)

file its using to compile - https://pastebin.com/sLmrWtHN

variables used for file above - https://pastebin.com/iE5hbz8K

using `BOOST_ROOT=`boost/location/dir

_Sent from my Galaxy Note5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by MSFTserver** [comment]
heres the config log if it is needed, may be an issue near the very bottom where is has HAVE-***-***=*** all the boost ones say /../ but higher in the tree the regular BOOST= have the correct paths
https://cdn.discordapp.com/attachments/519193647749791755/536458836735688714/config.log

**Comment by MSFTserver** [comment]
![img](https://cdn.discordapp.com/attachments/519193647749791755/536466828189368350/Screenshot_20190120-004719.jpg)
maybe its an issue here i noticed this isnt passing along Boost defined flags when it should...other checks are paasing those flags that include boost except this guy

**Comment by MSFTserver** [comment]
example check that includes boost flags 
![img](https://cdn.discordapp.com/attachments/519193647749791755/536467372282871820/Screenshot_20190120-004935.jpg)

**Comment by MSFTserver** [comment]
![img](https://cdn.discordapp.com/attachments/519193647749791755/538399790392803338/unknown.png)

**Comment by MSFTserver** [comment]
![img](https://cdn.discordapp.com/attachments/519193647749791755/538572000390545429/unknown.png)
i think ive narrowed down the issue to a filenaming issue during make or configure process im not sure wich one creates ravend-res.o but it is creating it as ravend-ravend.o i manually renamed that file and the laat error i was getting about -f invalid option went away and its happily moving past that and continue with the compile now

**Comment by spyder46n2** [comment]
This isn't something that I think has really been flushed out, at least I haven't ever tried it.  I'll try to poke at this a little and see if we can figure out what is going on.

**Comment by MSFTserver** [comment]
here's what I've been putting together, if you need it for reference on how i got some libs and things to work and what versions are being used

https://github.com/MSFTserver/easywinbuilder

**Comment by silence48** [comment]
Building in windows is much easier using the linux subsystem for windows.
If youre trying to build in windows visual studio you need to build all the
dependencies first in it.

**Comment by MSFTserver** [comment]
yea if your using the latest windows, honestly no reason it should build on windows unless the make code is bad, and yes I have all dependencies

**Comment by MSFTserver** [comment]
also avoiding visual studio thats another headache to setup all depend for
