### ISSUE TITLE
Cannot start up raven-qt on Ubuntu 16.04, missing libQt5Network.so.5

### ISSUE THREAD

**Issue by OedipusR3x** [RavenProject/Ravencoin#51]
I followed all the instructions for Ubuntu 16.04 on the README file and installed everything noted. I received no errors during all the installations. After installing everything required and downloading the binaries, I checked they were downloaded correctly using md5sum, which they were. I attempted to run raven-qt to start the GUI, but I got the error: 

./raven-qt: error while loading shared libraries: libQt5Network.so.5: cannot open shared object file: No such file or directory

I don't know what library was supposed to contain this file and I haven't been able to find out with "apt-file search" or googling. Any assistance would be helpful.

### Machine specs:
- OS: Ubuntu 16.04 LTS
- CPU: Intel Celeron g3900
- RAM: 4g corsair value select ddr4 2133mhz
- Disk size: 80gb
- Disk Type (HD/SDD): HD

**Comment by be4i** [comment]
Check this guide in the readme file, i had similar problem and helped me.

https://github.com/MSFTserver/RavenCoin-Wallet-With-Miners/tree/master/Wallet/Linux/ubuntu_16.04

**Comment by bedri** [comment]
It obviously says you dont have the libQt5Network.so.5 in your system. Check the version of libQt5Network if it's already installed on your system. If version does not match with 5 (as in so.5) then try to install that version.

**Comment by OedipusR3x** [comment]
I tried to find out what library contains the file I need but I didn’t have
much success. I just installed the wallet on my Mac instead.

**Comment by bedri** [comment]
The pre-compiled binaries looked for specific versions of libraries. In most cases users use latest versions of operating systems or updates their systems regularly which will result to installation of the latest versions of the libraries. If you need to use the wallet on Ubuntu, it's better you to compile and install it from source code. You can use the same [instructions](https://github.com/RavenProject/Ravencoin/issues/5#issuecomment-355771348) that I had linked earlier for a source code compilation and installation. It will very probably work without any errors. After compilation you can find the raven-qt executable under src/qt/ directory relative to Ravencoin directory.
It's also good to use the wallet from Mac so if it works I am glad to hear that.

**Comment by bedri** [comment]
Can we close this issue? It seems to be solved in a way.
