### ISSUE TITLE
Compile error on openSUSE LEAP 42.2

### ISSUE THREAD

**Issue by richardji7** [RavenProject/Ravencoin#52]
This issue tracker is only for technical issues related to bitcoin-core.

General bitcoin questions and/or support requests and are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).

For reporting security issues, please read instructions at [https://bitcoincore.org/en/contact/](https://bitcoincore.org/en/contact/).

### Describe the issue
Error during make when compiling from source.
#### If so, please list the steps to reproduce below:
1.  Run autogen.sh
2.  Run configure --with-gui
3.  Run make

### Expected behaviour
Expect to compile source successfully.

### Actual behaviour
Got error during make

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of bitcoin-core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.

Self compile using source code pulled today 2018/3/25.

### Machine specs:
- OS: openSUSE LEAP 42.2  4.4.104-18.44-default
- CPU:  Intel(R) Core(TM) i5 CPU       M 480  @ 2.67GHz
- RAM:  4GB
- Disk size:  500GB
- Disk Type (HD/SDD):  HD

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

make
Making all in src
make[1]: Entering directory '/home/oracle/git/Ravencoin/src'
make[2]: Entering directory '/home/oracle/git/Ravencoin/src'
make[3]: Entering directory '/home/oracle/git/Ravencoin'
make[3]: Leaving directory '/home/oracle/git/Ravencoin'
make[3]: Entering directory '/home/oracle/git/Ravencoin/src/secp256k1'
make[3]: Leaving directory '/home/oracle/git/Ravencoin/src/secp256k1'
  CXXLD    ravend
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: crypto/libraven_crypto.a(crypto_libraven_crypto_a-blake.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: crypto/libraven_crypto.a(crypto_libraven_crypto_a-bmw.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: crypto/libraven_crypto.a(crypto_libraven_crypto_a-echo.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: crypto/libraven_crypto.a(crypto_libraven_crypto_a-groestl.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: crypto/libraven_crypto.a(crypto_libraven_crypto_a-jh.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: crypto/libraven_crypto.a(crypto_libraven_crypto_a-keccak.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: crypto/libraven_crypto.a(crypto_libraven_crypto_a-luffa.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: crypto/libraven_crypto.a(crypto_libraven_crypto_a-shavite.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: crypto/libraven_crypto.a(crypto_libraven_crypto_a-simd.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: crypto/libraven_crypto.a(crypto_libraven_crypto_a-sph_hamsi.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: crypto/libraven_crypto.a(crypto_libraven_crypto_a-sph_fugue.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: crypto/libraven_crypto.a(crypto_libraven_crypto_a-sph_shabal.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: crypto/libraven_crypto.a(crypto_libraven_crypto_a-sph_whirlpool.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: crypto/libraven_crypto.a(crypto_libraven_crypto_a-sph_sha512.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
Makefile:3822: recipe for target 'ravend' failed
make[2]: *** [ravend] Error 1
make[2]: Leaving directory '/home/oracle/git/Ravencoin/src'
Makefile:9934: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/oracle/git/Ravencoin/src'
Makefile:733: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by bedri** [comment]
I am having the same error on OpenSUSE Tumbleweed

**Comment by bedri** [comment]
I am having the same error

**Comment by bedri** [comment]
Ok I guess i missed the -fPIC message.
The solution is to configure with parameters.
```
./configure --enable-cxx --disable-shared --with-pic CXXFLAGS="-fPIC -O" CPPFLAGS="-fPIC -O"
```
This solves the -fPIC error ( [#27](https://github.com/RavenProject/Ravencoin/issues/27) )

**Comment by richardji7** [comment]
That worked.  Thank you.
