### ISSUE TITLE
Still Stuck at Feb 9th after latest update

### ISSUE THREAD

**Issue by gotminer** [RavenProject/Ravencoin#522]
What's up guys? Stuck two weeks behind with new update. Feb 9. Anyone else?

**Comment by MSFTserver** [comment]
when you updated the wallet did you try resyncing the chain from scratch, simply upgraded to the wallet would fix it if you stuck before the upgrade

**Comment by jeroz1** [comment]
2.2.1 came with some serious performance gains. Unfortunately, also with a couple of bugs related to this speed up. As a result, there is a small chance that your blockchain could get stuck. These issues should be resolved in 2.2.2 which brings more performance updates.

If your wallet got stuck on v2.2.1 while you are connected to peers, your best way of getting it going again is to remove the blockchain files (see below for locations) to download a fresh chain. Merely updating to 2.2.2 does not solve the issue. 

**Caution: Do not remove wallet.dat!** (that file contains your keys and you should always have a backup of that file). 

After removing the blockchain files, open your Raven Qt again and let the wallet fully resync from day 1. Be aware that the progress bar is not accurate. It will speed up once your wallet is done syncing headers.

Default locations for your blockchain files:
Windows: `%appdata%\Raven`
Mac: `~/Library/Application\ Support/Raven/`
Linux: `~/.raven`

**Comment by gotminer** [comment]
I was able to delete the last revXXXXX.dat file from the blocks folder and that fixed it. It had to re-index and re-process the entire chain again (from my ssd), but at least I didn't have to download the entire chain again. Tired of doing that. Would have been the 3rd time since inception.

**Comment by MSFTserver** [comment]
ohhh nice duly when we help others alot with these issues, alot hate resyncing from scratch will have them try this first

**Comment by gotminer** [comment]
I fixed a similar issue with my bitcoin core node the same way at one time, so I thought I would give it a shot. Re-syncing isn't as big of a deal with rvn, because the chain is much smaller, but I still would rather not waste the bandwidth, if I don't have to.
