### ISSUE TITLE
Increase the maximum fee allowed from 10 to something like 1000 so that there is a way to make sure you get the asset you want by pricing out mempool adversaries.

### ISSUE THREAD

**Issue by blondfrogs** [RavenProject/Ravencoin#529]
Setting a 1000 RVN fee to create an asset ($10 now) would cause the attack to fill the mempool with higher fee transactions would cost around $2 million.  Currently the allowed 10 RVN fee will cause about $20,000 for front-run attack.

**Comment by cfox** [comment]
done
