### ISSUE TITLE
Low hashrate on rx 570

### ISSUE THREAD

**Issue by Gencaaa** [RavenProject/Ravencoin#53]
Guys,how many mhs u get for this card with 4gb hynix memory.My mhashrate is about 3.5 and i think that i can push it more.Intensity 20,mem clock 1950(i read that overclocking gpu can lower hashrate on this algo,but im not sure if that is true) but can push it to 2050.And where do i follow how many coins i have mined?

**Comment by ezaruba** [comment]
There's an image posted to the twitter that will tell you exactly how many Mh/s that you should be getting with each card. You can tell how much you've mined by looking in your wallet to see how many coins are there.

Or look at the dashboard (website) of whatever pool you're using to mine Raven.

**Comment by hoidsflute** [comment]
@Gencaaa If your question has been answered, please close this issue.  Your question is unrelated to the source code.  In the future, please use the proper channels like #mining in the Discord channel to ask your questions, there are plenty of people there who'd love to help.

**Comment by jacksonpchen** [comment]
![dycojljwkaeuckq 1](https://user-images.githubusercontent.com/37381763/39063539-44261d2e-4480-11e8-98d2-4ffb04d171e6.jpg)

**Comment by jacksonpchen** [comment]
@RavenCoinDev Please close this ticket. It's unrelated to code.
