### ISSUE TITLE
Issue wallet on windows

### ISSUE THREAD

**Issue by ronxb** [RavenProject/Ravencoin#538]
This issue tracker is only for technical issues related to bitcoin-core.

General ravencoin questions and/or support requests and are best directed to the [Ravencoin Discord](https://discord.gg/GwtXdyc).

For reporting security issues, please direct message one of the core developers in discord.

### Describe the issue
When I start the wallet it gives an error. Unable to start HTTP server. see debug log for details.
### Can you reliably reproduce the issue?
Yes
#### If so, please list the steps to reproduce below:
1. Double click to start wallet
2. Error message
3.I click OK
4. Wallet closes

### Machine specs:
- OS: windows
- CPU: Ryzen threadripper 1920x
- RAM: 32GB
- Disk size: 1.75TB
- Disk Type (HD/SDD): Both SSD and HDD

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by cfox** [comment]
What version were you using and does this problem persist?

**Comment by ebwworkpro** [comment]
change target in file properties to open file target as specified like you would a .bat file ...

**Comment by ebwworkpro** [comment]
then resync

**Comment by HyperPeek** [comment]
Seems ok.
