### ISSUE TITLE
std::cout spammed with blocktime

### ISSUE THREAD

**Issue by presstab** [RavenProject/Ravencoin#54]
This issue tracker is only for technical issues related to bitcoin-core.

General bitcoin questions and/or support requests and are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).

For reporting security issues, please read instructions at [https://bitcoincore.org/en/contact/](https://bitcoincore.org/en/contact/).

#### If so, please list the steps to reproduce below:
1. Run the wallet in terminal without detaching the process

### Expected behaviour
Clean terminal, std::cout rarely occurring.

### Actual behaviour
Every block prints out the time.

### Screenshots.
![screenshot from 2018-03-31 15-00-14](https://user-images.githubusercontent.com/6628210/38167575-c2caac4e-3526-11e8-8bbf-c781fded8ed3.png)

### What version of bitcoin-core are you using?
b488c034d512c8763cc6b2d50a69fdca4687d0c1

### Machine specs:
- OS: LinuxMint

**Comment by TronBlack** [comment]
Removed in develop branch which will be moved to master and released in binaries on July 30 2018.  Closing issue.
