### ISSUE TITLE
File google-services.json is missing. The Google Services Plugin cannot function without it. 

### ISSUE THREAD

**Issue by rojomisin** [RavenProject/Ravencoin#542]
This issue tracker is only for technical issues related to bitcoin-core.

General ravencoin questions and/or support requests and are best directed to the [Ravencoin Discord](https://discord.gg/GwtXdyc).

For reporting security issues, please direct message one of the core developers in discord.

### Describe the issue
while setting up dev env, android studio complains that 
```
File google-services.json is missing. The Google Services Plugin cannot function without it. 
 Searched Location: 
/Users/schmo/Dev/ravenwallet-android/app/src/rvn/debug/google-services.json
/Users/schmo/Dev/ravenwallet-android/app/src/debug/rvn/google-services.json
/Users/schmo/Dev/ravenwallet-android/app/src/rvn/google-services.json
/Users/schmo/Dev/ravenwallet-android/app/src/debug/google-services.json
/Users/schmo/Dev/ravenwallet-android/app/src/rvnDebug/google-services.json
/Users/schmo/Dev/ravenwallet-android/app/google-services.json
```

#### If so, please list the steps to reproduce below:
1. follow directions for https://github.com/Roshiix/ravencoin-android#how-to-set-up-the-development-environment
2. build the project

### Expected behaviour
Not sure where to get a valid `google-services.json` or how to craft one

### Actual behaviour
missing google-services.json file prevents build

### What version of bitcoin-core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.

### Machine specs:
- OS: OS X 10.14
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SDD):

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by MSFTserver** [comment]
this isn't related to the ravencoin desktop wallets... better to close this and reopen in the proper repository https://github.com/RavenProject/ravenwallet-android

**Comment by blondfrogs** [comment]
Closing as this does not pertain to this repo. @rojomisin If you haven't created the issue in the 
https://github.com/RavenProject/ravenwallet-android project please do.
