### ISSUE TITLE
[develop branch][testnet][gui] Name field in Create Assets tab freezes the gui wallet

### ISSUE THREAD

**Issue by bedri** [RavenProject/Ravencoin#550]
![image](https://user-images.githubusercontent.com/765487/54729171-0fde1880-4b93-11e9-9b27-b6e7d5ac8e7a.png)

Without a video I cannot demostrate the situation but as I click on Create Assets tab no cursor appears on the Name input box (it appears in some input box in Transfer Assets and Manage Assets tabs).

After clicking on Name input field in Create Assets tab the gui wallet freezes and when i try to close the wallet the OS pops up a Terminate Application window.

![image](https://user-images.githubusercontent.com/765487/54729311-eb367080-4b93-11e9-8e94-582982c34eb9.png)

My OS: OpenSuSE Tumbleweed updated to the latest. I haven't tested it on other operating systems or distributions.

I compiled the wallet from source code of develop branch so it's not a stable version issue.

Thanks in advance.

**Comment by bedri** [comment]
The same freezing also happens when the Amount input field is clicked in Receive tab but it does not freeze when Message input field is clicked in Receive tab.

![image](https://user-images.githubusercontent.com/765487/54729409-5c762380-4b94-11e9-87c9-8c3e6cf85b38.png)

The input fields in Send tab seems to be free of this problem.

**Comment by ravenlandpush** [comment]
I noticed there was some lag in the newer version of the UI with the blue background when interacting with the interface and its buttons. But no permanent freeze occurs for me. It was more of a usability observation.

 I wonder if this 'freezing' problem is to do with the way that the ui is rendered, since the same 'lag' or rather 'temporary freeze' I suffer from on a windows system. Although it is not so much as severe, but a few seconds for a mouse click to register is significant and have experienced that.

This did not affect the wallet functionality itself, for me.

Best,
Adam

**Comment by bedri** [comment]
I enabled Dark Mode from Options->Display and the problem magically disappeared :)
It's really weird.
When I disable "Dark Mode" the problem returns back.
Also when Dark Mode is disabled you can see that the Overview, Send and Receive elements in the left menu indented but in Dark Mode this is also shown correctly.

![image](https://user-images.githubusercontent.com/765487/54730933-9ba87280-4b9c-11e9-9858-cb180f9d887a.png)
Cursor is enabled in Amount input field in Dark Mode without any freezing problem.

![image](https://user-images.githubusercontent.com/765487/54730971-bbd83180-4b9c-11e9-9ad1-0d05c6b7f230.png)
Again cursor is enabled in Name input field in Dark Mode without any freezing problem.

**Comment by ravenlandpush** [comment]
I had dark mode enabled too. 
It seems your correct, there is a longer delay when clicking buttons in interface for me, when using dark mode, vs disabling the toggle option setting and restarting raven-qt.

I was able to recreate this. It make me think that something is unoptimized for the dark mode in regards to the UI that relates to your issue,


Best,
Adam

**Comment by HyperPeek** [comment]
Can this be related to unresponseness when the chain is not running due to missing miner on testnet? This is what I encountered. Still worth looking, but maybe a separate issue.

**Comment by hans-schmidt** [comment]
Thoughts on why the GUI would become unresponsive when mining slows or stops? I have also noticed on testnet that syncing stops when mining stops, even if the node is way behind the chain tip (so that lots of the connected peers should have newer headers and blocks to offer).

**Comment by fdoving** [comment]
Closing as this is old and many fixes for slow GUI are merged to develop.
Open new issues with references to this, if you still experience this.
