### ISSUE TITLE
Installation Instructions for different OS's

### ISSUE THREAD

**Issue by 05nelsonm** [RavenProject/Ravencoin#556]
### Describe the issue
Thorough Installation instructions are not readily available when trying to install Raven-Qt on various OS.

#### If so, please list the steps to reproduce below:
1. Go to https://ravencoin.org/wallet/
2. Click on a wallet
3. Takes you to the files needed for your OS, but no step by step instructions on the process from correctly verifying the file, to installing it, to running it.

### Expected behaviour
A short write up from the project for users to appropriately verify the the download, and how to install on their OS.

### Actual behaviour
No README.txt file available outlining this process accompanying the wallet downloads.

### What version of ravencoin-core are you using?
v2.2.2

### Machine specs:
- OS: Ubuntu 18.04 Desktop & Windows 10
- CPU: Intel(R) Core(TM) i7-8550 @ 1.80GHz 1.99GHz
- RAM: 16 GB
- Disk size: [Windows Partition = 343.1 GB] [Ubuntu Partition = 93.1 GB] [Linux Swap = 26.7 GB]
- Disk Type (HD/SDD): SSD

### Any extra information that might be useful in the debugging process.
A simple file (install_instructions.txt) added to the same place the files for the wallets are at would reduce user need to look elsewhere for instructions, especially with verifying of the download and ensuring it is properly signed.

**Comment by JonPizza** [comment]
HOW TO INSTALL RAVEN-QT ON UBUNTU

Step one) 
Download the ravencoin wallet at https://github.com/RavenProject/Ravencoin/releases

Step two)
Find the downloaded file named "raven-X.X.X.X" in your machine. It should live in ~/Downloads

Step three)
Open up the file and open up the bin folder

Step four)
Open up the folder in your command line (right-click, then open in terminal)

Step five)
Enter "./raven-qt"

The blocks should start downloading now

**Comment by HyperPeek** [comment]
Has been updated
