### ISSUE TITLE
[Request] Lock transactions before wallet is synced

### ISSUE THREAD

**Issue by jeroz1** [RavenProject/Ravencoin#560]
I need to help more and more users that tried to send a transaction in a hurry before their wallet was synced. These transactions tend to get stuck in their mempool and often they stay in there for a long time. I have to help them run trough the zapwallettxes procedure but I think it is better to go to the root of the problem: 

Could transactions get locked before the wallet is fully synced?

**Comment by danielhiatt** [comment]
Add warning dialogue if creating a transaction when not fully synced.

**Comment by hans-schmidt** [comment]
Jeroz1 reported that a warning has been added to the GUI.
Issue is being closed
