### ISSUE TITLE
I have Mac Book Pro.  I have had Ravencoin bought since 2-18 and have had Ravencoin wallet where I keep it.  All was well one month ago.  Now I go to my Ravencoin wallet and it refuses to synch with no active nodes connected.  How do I restart this wallet so it will synch?

### ISSUE THREAD

**Issue by arthurbieganowski** [RavenProject/Ravencoin#567]
This issue tracker is only for technical issues related to bitcoin-core.

General ravencoin questions and/or support requests and are best directed to the [Ravencoin Discord](https://discord.gg/GwtXdyc).

For reporting security issues, please direct message one of the core developers in discord.

#### If so, please list the steps to reproduce below:
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of bitcoin-core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.

### Machine specs:
- OS:
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SDD):

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by ravenlandpush** [comment]
Greetings. Can you come onto the ravencoin discord and we will help you resolve this in #helpdesk or #thenest ?

I would recommend to start off either reindexing the chain of the existing installation or reinstalling wallet altogether. Take care to ensure you have a backup of the wallet.dat, it is absolutely critical.

1. Take a backup of your wallet.dat and store it safely on another computer or usb stick if you havent already.
2. Download the latest release. https://github.com/RavenProject/Ravencoin/releases/download/v2.2.2/raven-2.2.2.0-win64-setup.exe
3.  Once you have reinstalled the wallet it should sync correctly.

Recommend you drop in on the discord https://discord.gg/AbKmen 

and we'll help you get this sorted :) 👍 


Best wishes,
Adam

**Comment by blondfrogs** [comment]
@arthurbieganowski Where you able to resolve this? Can we close this issue?

**Comment by arthurbieganowski** [comment]
I have a Mac and you suggested I download new release win64-setup.exec.  Is this correct for a Mac?

**Comment by MSFTserver** [comment]
@arthurbieganowski no thats is for windows you want the raven-XXX-osx.dmg
https://github.com/RavenProject/Ravencoin/releases/download/v2.2.2/raven-2.2.2-osx.dmg

**Comment by arthurbieganowski** [comment]
Morning again.  I opened a new wallet 2.2.2-osx.dmg and when it opened, I saw my Ravencoin balance but it is not synching. What do I do now?
Dr. B

**Comment by ravenlandpush** [comment]
Apologies , my mistake giving you the 64bit windows wallet instead of the mac OSX one there.  I would recommend rescanning the blockchain now. 

Click Help-> Debug window. and type 'rescanblockchain'. This should rescan the blockchain and correctly update the balances. Failing this you may need to start the application with -reindex, to reindex the chain from beginning.

Apologies for giving you the wrong link previously, so used to helping people using windows :) Hope this helps get you synced correctly!

Cheers &
Best wishes,
Adam

**Comment by arthurbieganowski** [comment]
I have downloaded the new updated wallet 2.2.2-osx.dmg and after awhile it showed my old balance, which is correct and then, it finally started to synch.  After it synchs, should I back up this wallet like I did with my 1st version?  Will I still be able to use my old paraphrase to unlock the encryption or should I re-install this again?  After I have done all of this, should I erase the old wallet?

Thank you,
Dr. B

**Comment by ravenlandpush** [comment]
Dr B, 

You should be OK if you already have a backup the wallets used by Ravencoin are HD (Heirarchical deterministic). It basically means that one key will be the master key, and all new keys are backed up (or based on) the original key. So as long as you have a backup of that wallet, you should not need to take another backup having installed the new version.

I hope this helps clarify. Please let us know if you have any more questions or concerns, we're happy to help!

Best,
Adam

**Comment by arthurbieganowski** [comment]
Thanx for advice.  Synching now but connected to only 1 active node.  Is this the usual with one node?  And shall I just wait?

Dr. B

**Comment by ravenlandpush** [comment]
If you type %appdata%\raven this will bring up the main installation directory.

You can place a file called raven.conf in the folder that opens, by creating a file called raven.conf and adding these lines, then restarting raven-qt.

addnode=35.166.222.70
addnode=35.210.244.221
addnode=221.244.210.35
addnode=165.227.23.185
addnode=165.227.23.185
addnode=35.163.33.254
addnode=35.221.251.106
addnode=106.251.221.35
addnode=18.202.96.180
addnode=18.202.105.221
addnode=18.202.73.87
addnode=54.149.71.91
addnode=52.25.221.13
addnode=34.248.13.29
addnode=52.37.42.247


Alternatively, you can goto help->debug->console and type them in manually as so

addnode "35.166.222.70" add
addnode "35.210.244.221" add
addnode "221.244.210.35" add
addnode "165.227.23.185" add
addnode "165.227.23.185" add
addnode "35.163.33.254" add

I include an image for clarity.

![image](https://user-images.githubusercontent.com/47545876/55741564-7aada180-5a25-11e9-8ece-6acfedfe7630.png)


Best,
Adam

**Comment by arthurbieganowski** [comment]
Hi,

I went to console and typed in 1st 2 nodes and it kept coming up with method not found (code-32601)


What next?

Dat. B

**Comment by ravenlandpush** [comment]
Hi, 

It is very important the syntax to use. addnode "35.166.222.70" add

No spaces between add and node, the ip address needs to be in quotes "" and there needs to be a space between 'add' and the ip address previously. 

It's worth noting your wallet is syncing correctly and should finish syncing and adding these peers itself, but you can add these to speed it up if you are familiar with using the console :)

Best
Adam

**Comment by arthurbieganowski** [comment]
Bro,

I finally got it right.  Thanks so much for being there for me.  You are helping to turn me into a geek!

Dr. B

**Comment by ravenlandpush** [comment]
Hey Dr. B its a pleasure man. Glad your up and running with latest version 💃

**Comment by arthurbieganowski** [comment]
Hi,

It finally synched.  I just have 2 more questions.  Can I remove my old wallet and in doing so, my DAT FILE WILL REMAIN?  Also, will my encryption passphrase be the same on my new wallet, as I noticed it is locked and needs the passphrase?


Thanx,


Dr. B

**Comment by ravenlandpush** [comment]
Greetings Dr B. I do not understand the question exactly here. 

If you remove the old wallet (wallet.dat). (make sure you have a back up of the file made in case you need it), then, the next time you startup raven-qt, a new wallet will be made. 

Please note the new wallet made does not contain a copy of your old wallet.   It is very important to understand.

Any new wallet made will not have an encrypted password, as I believe this is something you 'add after generation' of the wallet. 

I hope this helps clarify?

Cheers &
Best wishes,
Adam

**Comment by blondfrogs** [comment]
You only need to have the most recent raven qt app on your computer. 
Removing as the client was synced.
