### ISSUE TITLE
Wallet Repair Tab user accessibility 

### ISSUE THREAD

**Issue by ravenlandpush** [RavenProject/Ravencoin#568]
Greetings. Here is a feature request for 'wallet repair tab'

It would be really nice to see something more like a 'wallet repair' tab as is the case with bitcoin. I dont think it is requiring much but restart/reforking the process with the necessary -reindex flag and the such. I notice a few users have problems like this so there is probably a need for a clearer wallet repair tab. I think instead of hiding it in the menu, it should be placed more prominantly in its own 'repair menu'. I have seen many users get confused.

Something like this would also be a great step forward I think;

![example](https://coinguides.org/wp-content/uploads/2018/10/rescan-rebuild-index.png)

Best,
push

**Comment by jeroz1** [comment]
#486

**Comment by ravenlandpush** [comment]
well ahead of me jeroz! Cheers

**Comment by jeroz1** [comment]
Perhaps it is easier to add a debugging folder with shortcuts that do these things during wallet installation? In that case, you don't have to create a GUI. @blondfrogs @cfox 

Moreover, these options are not only useful for "repairing" the wallet but the reindex flag, for example, is also required when someone wants to use a backup of wallet.dat.

**Comment by jeroz1** [comment]
https://github.com/RavenProject/Ravencoin/pull/570

**Comment by blondfrogs** [comment]
Closing as this is a duplicate and was merged in #570
