### ISSUE TITLE
Why is the raven wallet using so much CPU?

### ISSUE THREAD

**Issue by doublexz94** [RavenProject/Ravencoin#57]
It's as if I'm mining with my CPU, can I close the wallet while mining?

**Comment by Larceniii** [comment]
Goto the Menu aunder Help -> debug window -> console and type "setgenerate true 0" without quotes.
This sets the built in miner to use zero cores. "setgenerate true 8" would use 8 cpu cores to mine for example. By default it mines with 1 core.

**Comment by doublexz94** [comment]
Thanks it worked.

**Comment by bedri** [comment]
> setgenerate false 0

is a better approach i guess.

**Comment by Larceniii** [comment]
yea but it's kinda weird like
`setgenerate false 4`
Keeps on mining, so false doesn't do what you think it would I guess.

**Comment by hoidsflute** [comment]
@doublexz94 @RavenCoinDev This issue has been resolved, please close.
