### ISSUE TITLE
Modified X16R algorithm proposal in order to achieve hash rate constant in short time

### ISSUE THREAD

**Issue by eastera1** [RavenProject/Ravencoin#572]
i have a post about how to make GPU-run miner having a constant hash rate with a modified X16R algorithm. you can find it   [https://www.reddit.com/r/Ravencoin/comments/bhyrxv/modified_x16r_algorithm_proposal_for_constant/](url), some guys complain not to get my point because of my poor english. really, it is not my native language:(.  what's more, i think understanding the content needs  some technical background, so i post here also.

in case you are intrested in this topic, i'd like to briefly describe our idea first (it is really generated in a brainstorm of guys who use GPU to mine RVN)

we found hash rate fluctuation for GPU-run miner software. the reason is that these 16 sub hashing algorithms have different running cycles. current algorithms could not mitigate it because a combination of these sub algo are different block from block. 
we suggest to vary such combination nonce by nonce in a random maner, so that the differece of running time could be averaged in a span of a block time. in turn constant hash rate could be seen in GPU-run miner.

BTW
here is another link [https://medium.com/systems-nexus/modified-x16r-algorithm-proposal-for-constant-hash-rate-in-short-time-164711dd9044](url) which may be easier understood.

**Comment by lsji07** [comment]
Hi this issue could be simply resolved on gpu miners but increasing the average hashrate over a longer time period. 1 hour or 3600 seconds rather than instantaneous hashrate that can fluctuate dramatically over the short term. 

No algo change required to the core protocol imho for that known issue.

**Comment by HyperPeek** [comment]
obsolet after move to kawpow
