### ISSUE TITLE
QT wallet speed issue caused by shadows on macOS

### ISSUE THREAD

**Issue by volbil** [RavenProject/Ravencoin#577]
### Describe the issue
QT shadows created by `QGraphicsDropShadowEffect` class is killing my MacBook, wallet slow and irresponsive. After I removed them (I removed `getShadowEffect()` which add them to GUI element) wallet start working like a charm. I haven't tried wallet on other systems, so it could be macOS specific issue.

### Can you reliably reproduce the issue?
Yes, this issue is occured each time when I build QT wallet on my own.
#### If so, please list the steps to reproduce below:
1. Autogen and configure Raven without any additional falgs on macOS. 
2. Build it.
3. Run raven-qt wallet.

### Expected behaviour
Wallet works without any issues.

### Actual behaviour
Instead wallet work slow and barely respond to any interactions.

### Machine specs:
- OS: macOS Mojave 10.14.1
- CPU: Intel Core i7 2,2 GHz
- RAM: 16 GB 1600 MHz DDR3
- Disk size: 256 GB
- Disk Type (HD/SDD): SSD

**Comment by blondfrogs** [comment]
@volbil Thanks for creating this, on the next release, I will remove the shadow effects of the wallet as performance is preferred over the look of the wallet.

**Comment by blondfrogs** [comment]
@volbil Can you please test the build on my personal repo as see if my changes also fix this problems you were running into. 
https://github.com/blondfrogs/Ravencoin/tree/test_issue_577

**Comment by volbil** [comment]
Hello @blondfrogs. Just tested your fix, works slightly better than before, but shadow on sidebar still present. It makes UI bit irresponsive. After I commenting out [this](https://github.com/blondfrogs/Ravencoin/blob/test_issue_577/src/qt/ravengui.cpp#L655-L661) code qt wallet start working much faster. Here is final result without sidebar shadow:
![Wallet without shadows](https://i.imgur.com/HIqc7iI.png)

**Comment by blondfrogs** [comment]
oops forgot about the side bar, that one is declared in a different area. Will update

**Comment by volbil** [comment]
Thanks @blondfrogs !

**Comment by HyperPeek** [comment]
fixed
