### ISSUE TITLE
Not receiving the mined coins in my wallet!

### ISSUE THREAD

**Issue by RamiCrypto13** [RavenProject/Ravencoin#58]
HI,
Wish I can get get on this.

I am mining ravencoin using ccminer 2.2.5 on yiimp.eu to my raven core qt wallet. I was receiving coins consistently every one hour (I was on threeeyed pool) till yesterday evening around 4pm, since then I received nothing, I switched to yiimp.eu, and still I have received nothing after 5 hours mining.

Is there something wrong with either the wallet or the pools? I tried to isolate the different factors to see what is causing this, but with no luck.

Appreciate your help.

**Comment by Larceniii** [comment]
Check the difficulty - it's going up.

**Comment by doublexz94** [comment]
Same here, the miner is mining fine, but I'm not receiving any coins. Maybe threeeyed is holding all the coins so when the price goes up they will dump it, and buy the lowered price ones to give it to us.

**Comment by mortifiedvictim** [comment]
Same here, I went from making 180 coins a day to ZERO over the last 30 hours. What the heck is going on?!

**Comment by otgonmn** [comment]
Same to me. What is going on? Is it because of miner or wallet issue? Any updates?

**Comment by mortifiedvictim** [comment]
It seems that this is a three eyed pool issue.
1. It's happened before on Feb 28th
2. I found a thread on Reddit where other people had the issue and stopped getting payouts
Some people say the difficulty is skyrocketing but for myself having a 5 GPU rig and not getting paid for 30+ hours now its a pool issue and I'll have to switch to anther. I'm pretty sure we won't get paid for what we mined either, but if I do I'll re-post to announce. Thanks.

**Comment by mortifiedvictim** [comment]
I switched to SUPRNOVA's pool. I probably won't be up long enough to see a payout, but I'll post when I'm able to confirm I'm getting paid from their pool which will corroborate my theory.

**Comment by xtrash** [comment]
Hi. Same issue on ThreeEyed pool for me. Got 190 mature RVN not paid for more than 30 hours.
the next payout info on the website stats is locked at 14:33:56 GMT-0500 (CDT) ...
No information from the pool team....

**Comment by minotaurdesign** [comment]
Please be sure to contact the pool owners for pool support issues.

**Comment by mortifiedvictim** [comment]
I just had a chance to check my raven coin wallet and I did receive the payouts.

**Comment by otgonmn** [comment]
Yes I get my coins too... start mining again same pool... hopefully doing ok now.... good luck fellow miners.

**Comment by hoidsflute** [comment]
The dev from ThreeEyed is asking everyone to switch pools and if you haven't received your payouts, you will shortly.  @RamiCrypto13 @RavenCoinDev Close this issue, it's unrelated to the code.

**Comment by hoidsflute** [comment]
close #58

**Comment by chabgood** [comment]
I have 355 still in immature status!!

**Comment by carlzimmerman** [comment]
Can be closed..

**Comment by jacksonpchen** [comment]
@RamiCrypto13 Please close this ticket.

**Comment by TronBlack** [comment]
Was related to a pool.  Closing issue.

**Comment by coinmaster4you** [comment]
Still happens. Blockchain record the tx but not reconised as wallet balance
