### ISSUE TITLE
I need a rvn faucet

### ISSUE THREAD

**Issue by subaohu** [RavenProject/Ravencoin#582]

**Comment by jeroz1** [comment]
Code for a faucet? Or just locations of them? 

There are some posted here: https://sugikingdom.com/ultimate-crypto-faucet-list/

**Comment by liteliger** [comment]
thanks for sharing my site jeroz. I think the community could use more faucets in general, they are great way for mass adaption.

**Comment by ravenlandpush** [comment]
hey I don't see our faucet on there @liteliger your welcome to include it if you like !

https://faucet.ravenland.org/

I'll provide some details soon in my presentation at blockchain expo and hopefully, do a release of the source for it 🙏 

- push

**Comment by liteliger** [comment]
> hey I don't see our faucet on there @liteliger your welcome to include it if you like !
> 
> https://faucet.ravenland.org/
> 
> I'll provide some details soon in my presentation at blockchain expo and hopefully, do a release of the source for it 🙏
> 
> -- push

hey i will list it today.

**Comment by ravenlandpush** [comment]
cheers man! also I hopefully will be able to provide some more source for others looking to do things like their own raven faucets soon !

**Comment by danielhiatt** [comment]
Looks like this was resolved.  Closing the ticket.
