### ISSUE TITLE
Offline signature scheme

### ISSUE THREAD

**Issue by subaohu** [RavenProject/Ravencoin#583]
What is the language signature library?s it the same as Bitcoin's offline signature scheme? Whether to use third-party libraries（https://bitcoinj.github.io）？
Can I provide an offline signature transaction demo, not an offline node?

**Comment by bedri** [comment]
What is your problem?

**Comment by subaohu** [comment]
it the same as Bitcoin's offline signature scheme? Whether to use third-party libraries（https://bitcoinj.github.io）？

**Comment by blondfrogs** [comment]
The signature scheme has not changed Bitcoins. It is the same scheme as bitcoins. Please try to use Discord / Telegram to ask these types of questions. @subaohu
