### ISSUE TITLE
QT Sluggishness in windows

### ISSUE THREAD

**Issue by ravenlandpush** [RavenProject/Ravencoin#589]
I know this may have been mentioned before, please close out if replica.

I noticed that when transactions are pending inthe new QT windows UI, that it is especially slow to poll the ui. Im wondering if this is something to do with the way the program uses its available threads, and it ends up waiting a really even longer time, when transactions are pending in 'Assets Received' under transactions of the Raven-QT wallet.

Cheers &
Best wishes,
push

**Comment by blondfrogs** [comment]
Can you please given an example of what you are doing, and how it is sluggish. I will try to duplicate the issue so the sluggish issue can be pin pointed down.

**Comment by fdoving** [comment]
Could be related to #1036

**Comment by jeroz1** [comment]
#1036 fixes the huge wallet lags that I also experience in a ubuntu 20 testnet wallet containing a very large amount of txes.

**Comment by fdoving** [comment]
Closing as 1036 should fix this. Please open a new issue if you still have problems.
