### ISSUE TITLE
I lost like 10 hours of mining. It shows as less than 1mh/s

### ISSUE THREAD

**Issue by AlexCorv** [RavenProject/Ravencoin#59]
Problems with Threeeyed 
More than 10 hours shows as 1 MH/s instead of the 20-25 that my GTX 1080 + GTX 980 make.
And now they have been working for like 6 hours and its not showing like in getting any coin.
https://photos.app.goo.gl/o6DFXTw902AjpuW02

**Comment by minotaurdesign** [comment]
Have you contacted the pool owner? We have no control or authority over pools, but I know the pool owner was aware and working on the issue. I believe they advised miners to switch pools while they figured it out, via discord chat.

**Comment by AlexCorv** [comment]
Cant use their discord... It says invitation expired.
But thanks for the info
