### ISSUE TITLE
Block explorer doesn't display raw tx hex data

### ISSUE THREAD

**Issue by johnnynanjiang** [RavenProject/Ravencoin#591]
Hi folks, 

Does anyone know how to get tx hex raw data, it doesn't seem to be available via the explorer, but it would be helpful for developers to verify tx data.

e.g.:
https://ravencoin.network/api/tx/128793fa1635c630a3463225515f9aabfa6160ae32028d5ae6f09b04802abebe

**Comment by Scotty0448** [comment]
There's another block explorer available now that uses a similar API but
happens to include the raw hex data for transaction queries.  It's at
https://blockbook.ravencoin.org and the equivalent URL to the example you
posted would be the following:

https://blockbook.ravencoin.org/api/tx/128793fa1635c630a3463225515f9aabfa6160ae32028d5ae6f09b04802abebe

**Comment by underdarkskies** [comment]
Yea it does provide raw tx hex.  https://ravencoin.network/api/rawtx/128793fa1635c630a3463225515f9aabfa6160ae32028d5ae6f09b04802abebe  Use the rawtx path

**Comment by jeroz1** [comment]
List of all known API's:

https://api.ravencoin.org/api/
https://explorer.ravenland.org/api/
https://ravencoin.network/api/
https://rvn.traysi.org/api/
https://checkraven.com/api/
https://explorer.rvn.zelcore.io/api/

**Comment by blondfrogs** [comment]
Closing as this seems to be answered.
