### ISSUE TITLE
Q: Why there are no documents about how to run RavenCoin Daemon?

### ISSUE THREAD

**Issue by uurcm16** [RavenProject/Ravencoin#596]
Why there are no documents / wiki about how to run RavenCoin Daemon (ravend?)

I'm going to open a pool for RVN and I want to read some optimization tips, ravend arguments and etc.

Are there any documents ?

Best regards.

**Comment by Raptor3um** [comment]
it is the same as bitcoin core which is very well documented.

**Comment by uurcm16** [comment]
Thank you. Closing the issue!
