### ISSUE TITLE
Mining Pools

### ISSUE THREAD

**Issue by jmh77777** [RavenProject/Ravencoin#6]
Does anyone have a mining pool set up, or instructions on how to?

**Comment by RavenCoinDev** [comment]
As far as we know there hasn't been any work done on setting up any mining pools. Right now they aren't really needed as the mining power is relatively low and even small machines are still getting blocks.

**Comment by jmh77777** [comment]
Thank you, and in regards to pools and mining, is Ravencoin's algorithm GPU mineable? Will there be more information regarding that? I assume it would render CPU mining almost useless.

**Comment by RavenCoinDev** [comment]
Theoretically yes but nothing has been built for GPU mining, it is ASIC resistant however.

**Comment by resiroth** [comment]
The link to the white paper on the website doesn’t work. What’s the algorithm? Thanks!

**Comment by jeroenroodnat** [comment]
I have been experimenting with building a pool for ravencoin. Just to see if I could get it to work. I have the mining pool running and now stuck on how to point ravend to the pool. I think that is not in the code yet?

**Comment by resiroth** [comment]
It is somewhat obvious someone(s) have started to GPU mine this coin as it now is 5x the networks despite no public pools and effectively not being viable on any laptop processors at this point. The average time for a laptop to find a block is 100 hours at this point, and given difficulty increases we can assume that someone mining with a laptop will more likely than not, never find a block.

**Comment by jediwarpraptor** [comment]
Not sure there is evidence to support that @resiroth.   I guarantee you that Bitcoin hashrate grew by 5x early as more and more people were starting to mine.  I know 3 different people who have mined blocks (and still do) with laptop processors.

**Comment by jmh77777** [comment]
I agree with @jediwarpraptor as one GPU would be around 20 million hashespersecond. That would be far more noticeable. If someone was GPU mining, they'd be far more noticeable. Maybe someone has 1 GPU running, or something.

I would like to know how to GPU mine, that's for sure.

**Comment by jediwarpraptor** [comment]
We don't know anything about the X16R Algorithm yet (I don't think the full source is here yet) - so it would be nearly impossible for GPU optimization... yet.  I know that they've designed the algorithm to be ASIC - resistant so it could be that it's also resistant to massive parallelization which would make it optimal for GPUs.

Most people think that GPUs are just super-hopped up general purpose computer chips.  GPUs primarily are better at jobs that can be split into a ton of smaller tasks and pipelines of tasks (there are a _*LOT*_ more processors in GPUs than on an Intel chip, for example - but they've got slower clock speeds, so they can't compete on a one-on-one basis.

**Comment by resiroth** [comment]
I’m not talking about yesterday, I’m talking about today. While writing that comment the network hash per second was 192,146 khash. A standard laptop will get about 30 khash. So about 1 in 6000 chance of mining a block. If we simplify things you mine 1 block out of every 6,000 or 1 in 100 hours. 

However that’s assuming the hashrate stays the same. If it went up so dramatically it will only rise further from here, potentially resulting in a block never being mined. 

I personally have been mining 27 hours without a block, with a high end processor about 8x as fast as the example hash rate. The day before I was hitting a block every couple hours.

I’m not particularly worked up about it, after all this is purely for fun at this point, and tbh the white paper link doesn’t even load which isn’t encouraging for the long term prospects of this coin.

It is simply sad that a relatively obscure coin became relatively “unmineable” in such a short period of time.

**Comment by jediwarpraptor** [comment]
For the moment, I don't think we even need a Whitepaper, there isn't any tech to talk about yet.  Just a dream. The thing I love about Raven is that @BruceFenton has gone out of his way to deliberately pay homage and tip of the hat to the original OG cryptocurrency, namely BTC.  Satoshi already wrote a whitepaper about the tech underlying Ravencoin at this point.

We're all mining it because we like whatever it is about Ravencoin that has been published and is available to date and we think there's a good reason to support it.  At some point, there will be more devs and/or the devs and the community will start laying out plans for what this coin will be.  At that point, I'd expect a whitepaper.  

This ain't an ICO where a whitepaper and a dream and a marketing budget can get you $200 million and a fast dump payday.  IMHO, it's Bitcoin reincarnated with a good proposed theoretic usecase, a faster blocktime and a higher supply/block reward.  The rest is yet to be sorted out.

**Comment by jmh77777** [comment]
@jediwarpraptor-

 @RavenCoinDev said on twitter "Now that the code is available, anyone is free to build additional tools and pools.   If it doesn't happen soon, we'll consider building them ourselves.", regarding GPU mining. So I guess it's there. I'm not technical enough to figure it out. But it's there. And whoever gets to it first will do well.

**Comment by resiroth** [comment]
http://cryptomining-blog.com/tag/x15-miner/

For the x15 algo GPUs do 1500-3000 khash. There is no reason to suspect GPUs would do 20,000 khash. The network increased by 100,000 khash despite virtually no online presence or reddit posts etc. white paper or marketing or purpose. I’m mining this because I’m curious. And it was fun to mine something just beginning to take shape. Now that the number of people mining has skyrocketed to the point you don’t even find blocks it’s a bit boring tbh.

**Comment by RavenCoinDev** [comment]
@jediwarpraptor The source code for the X16R algorithm is in the published source code.   Specifically in src/hash.h

We're still cleaning up a few outstanding issues related to missing libraries for our Mac qt client.

**Comment by LiteSaber** [comment]
@jeroenroodnat Any luck figuring it out yet?

**Comment by jeroenroodnat** [comment]
@LiteSaber the source code needs to be adapted to work with miningpools. I have not found any reference to supporting this yet.

**Comment by bouguerra12** [comment]
@jeroenroodnat which source of mining pools are you using ?

**Comment by quagliero** [comment]
There is a mining pool over at Suprnova. https://rvn.suprnova.cc/index.php

**Comment by RavenCoinDev** [comment]
To view a list of mining pools, visit bitcointalk announcement page:
https://bitcointalk.org/index.php?topic=2752467.0

**Comment by theolddragon01** [comment]
06:22:44
￼
Error: Node already added (code -23)
 please hepl

**Comment by hardline7** [comment]
how to build rvn mining pool?

**Comment by Dradden** [comment]
It is not easy and unless you are somewhat comfortable as a systems admin really not recommended. You have a few choices:

1. Yiimp which is the easiest to setup but has some performance / stability issues at high miner counts and also has a max of 2000 per port.

2. Use a Unomp branch but then you need to piece things together for Ravencoin such as hashing algo.

Takes some time and work to get it going and this also does not work to solo mine if you had that in mind. Alternatively you can joins a pool such as https://mineit.virtopia.ca

**Comment by hardline7** [comment]
It is expected that it will be difficult.
I already have an ETH-based pool.
What do you think is the best source for you to think?
Thanks.

**Comment by Dradden** [comment]
Really depends what you are looking for or are comfortable with. Yiimp is easier but the node.js is faster in every regard and I think also gives an edge on finding blocks.

https://github.com/foxer666/node-open-mining-portal

Has support for x16r. Stats though especially worker stats are incomplete and it is not just a matter of htmls, the core is missing some needed functions. I am working on this but will take a little time.

**Comment by mman07** [comment]
@Dradden 

Thank you for answer.  I had same issue. 
I suceed open deamon from binary files from your answer.
raven-cli alslo working well. (getinfo, getnetworkinfo etc.)
But, I didn't find how to connect with NOMP (same as your github link). 

Thanks.

**Comment by wjohnpit** [comment]
> Alguém tem um pool de mineração configurado ou instruções sobre como fazer?

Where can I find official information for creating a professional RVN Pool, information about daemons, operating systems, ideal hardware configuration, etc. Thank you
