### ISSUE TITLE
minRelayTxFee and BIP-9

### ISSUE THREAD

**Issue by hans-schmidt** [RavenProject/Ravencoin#602]
### I would like to propose that the "AreMessagingDeployed()" BIP-9 checking for the planned default "minRelayTxFee" increase should be removed everywhere from the code. ###
Although its use is admirably democratic, I submit for discussion that it should be removed because:

> 1) BIP-9 signalling is intended as a mechanism for chain soft-fork consensus decisions. "minRelayTxFee" is a client policy parameter, not a consensus parameter- changing it can never cause a chain fork.

> 2) Users of any version of ravend or raven-qt can set the "minRelayTxFee" to any value they like by utilizing the client "-minrelaytxfee=<amt>" command line launch option.

> 3) "minRelayTxFee" has been changed numerous times by bitcoin core without any BIP-9 or BIP-34 signalling:

``` 
        commit 2bfda1be11a079f7b468c79d79a91ddb30369557
	        first created MIN_RELAY_TX_FEE = 50000;

        commit 6de1326ba4a35ab781107a8b56f74affaed87cba
            lowered  by 5x MIN_RELAY_TX_FEE = 10000;

        commit 000dc55181f77cd96076c76b2cc13f8bcbe4146e
            added command-line setting option with same default CTransaction::nMinRelayTxFee = 10000;

        commit 6a4c196dd64da2fd33dc7ae77a8cdd3e4cf0eff1
            lowered by 10x CTransaction::nMinRelayTxFee = 1000;

        commit 28e3249e53b8ef7516636df0f1406466a513095d
            raised by 5x CFeeRate minRelayTxFee = CFeeRate(5000);

        commit 9e93640be6c49fa1505ba5c5df8c89210da5a6e4
            lowered by 5x CFeeRate minRelayTxFee = CFeeRate(1000);
```
> 4) Implementing an immediate non-BIP-9 change to the default "minRelayTxFee" in the new version ravend/raven-qt clients concurrently with the BIP-9 messaging and restricted asset changes could help speed up adoption of the new client version. As usage of the new client version increases on main_net, users and miners of the old version clients would be increasingly likely to notice their transactions not being relayed, thereby motivating them to investigate and to upgrade.

*Community agreement for increase of the default "minRelayTxFee" prior to implementation could be achieved by discussion in the community forums rather than by stretching the use of BIP-9 beyond its intended application.*

**Comment by jeroz1** [comment]
I agree
