### ISSUE TITLE
db_cxx.h:No such file or directory

### ISSUE THREAD

**Issue by lfj7282** [RavenProject/Ravencoin#611]
hi . i build  the master branch. 
occur this error

In file included from ./wallet/walletdb.h:12:0,
                 from wallet/wallet.h:20,
                 from miner.cpp:31:
./wallet/db.h:22:20: fatal error: db_cxx.h: No such file or directory
 #include <db_cxx.h>
                    ^
compilation terminated.

**Comment by lfj7282** [comment]
cmd :

git clone https://github.com/RavenProject/Ravencoin.git
cd raven/
./autogen.sh
./configure --disable-wallet --without-gui --without-miniupnpc
make check

**Comment by volbil** [comment]
Hello, have you installed `libdb4.8-dev` and `libdb4.8++-dev` from Bitcoin repository?
```
sudo add-apt-repository ppa:bitcoin/bitcoin
sudo apt-get update
sudo apt-get install libdb4.8-dev libdb4.8++-dev
```

**Comment by spyder46n2** [comment]
@lfj7282 - It does look like this is a configuration that does not compile. Interestingly the same configuration works on Bitcoin.  I haven't dug into it enough yet to know what it is about this combo of disable-params that is causing the issue but I'll poke at it a bit more today.
