### ISSUE TITLE
IPFS hash is not shown anywhere on the Qt GUI

### ISSUE THREAD

**Issue by lsji07** [RavenProject/Ravencoin#613]
Ravencoin functionality is based around asset token that have IPFS metadata attached to the  various asset token types as per the token issuers needs and agreements.

The GUI currently doesn't show tokens IPFS hash anywhere in the current GUI arrangement. 

Potential users currently have to use the cli with command `listassets ASSETNAME true` to see the ipfs hashes associated with tokens they own, or an asset explorer run by others.

I believe this could short term simply be added to the transactions section of the qt wallet until the additional GUI work is implemented to show the asset ipfs hashes and messages in a more user friendly manner.

But if a sexy rework of the GUI is coming soon, showing IPFS hashes, ignore me...

**Comment by jeroz1** [comment]
This extends to the messaging functionality.

**Comment by fdoving** [comment]
This is fixed, can be closed. @HyperPeek
