### ISSUE TITLE
Mac version not working on OS X El Capitan v10.11.16

### ISSUE THREAD

**Issue by Al-WaySlate** [RavenProject/Ravencoin#62]
This issue tracker is only for technical issues related to bitcoin-core.

General bitcoin questions and/or support requests and are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).

For reporting security issues, please read instructions at [https://bitcoincore.org/en/contact/](https://bitcoincore.org/en/contact/).

Mac version not working on OS X El Capitan v10.11.16. The Ravencoin icon is crossed out signaling this wallet build will not work on a version lower than OS X v10.12...Basically making this build useless for A LOT of OSX users.

### Expected behaviour
Tell us what should happen

-->Add more supported OS X versions

**Comment by OACA** [comment]
This is the message obtained after trying to install the wallet Raven-2.0.4.0-osx.dmg: "No mountable file systems". And after installing the file manually in the Terminal the message reads as follows: 
$ hdiutil/Applications/Ravencoin/Raven-2.0.4.0-osx.dmg 
-bash: hdiutil/Applications/Ravencoin/Raven-2.0.4.0-osx.dmg: No such file or directory
The wallet is still not installing in a Macbook Pro with OS X El Capitan v10.11.16
