### ISSUE TITLE
transferfromrvnaddress

### ISSUE THREAD

**Issue by ravenlandpush** [RavenProject/Ravencoin#622]
Greetings,

In the dev branch the transferfromassetaddress is very useful, brilliant.

I was wondering if it might be possible to add a similar function for RVN. So transferrvnfromaddress(src_address, asset, targetaddress, amount) or similar. I think it will be very useful

Cheers &
Best wishes,
Adam

**Comment by sudux** [comment]
you can use getaddressesbyaccount address to create an address account.

you will have an address account and a new address in this account.

then use sendfrom "address account“ ”address“ rvn

**Comment by ravenlandpush** [comment]
Its a deprecated function. We can't use a function that is deprecated for production stuff. Also this does not support change addresses.

There is no change addresses specified in the RPC function that you refer as it stands. That is the real reason for this request..

 So the suggestion being made here is for sendfromrvnaddress, a non deprecated function with change_address as an rpc option. Regarding the last bit with the change address ,apologies that it is not clear from my above statement, but I had spoken about it in some detail to blondfrogs about he simply asked me to open up an issue here, and I wasn't very specific about it since I knew he already understood the function suggested by us,

Best,
Adam

**Comment by sudux** [comment]
I think sendfromrvnaddress is better than sendfrom too~ ^^ Sendfrom is the only way  to send rvn from address right now, but not good to use.

**Comment by HyperPeek** [comment]
fixed
