### ISSUE TITLE
Sending txs while not fully synced results in txs getting stuck in mempool

### ISSUE THREAD

**Issue by jeroz1** [RavenProject/Ravencoin#624]
Multiple (impatient) users have reported over the last year that txes get stuck in their mempool when they tried to send them while not fully synced. This results in reduced available balance in the wallet while nothing hit the network. I helped them by zapping their wallet.

Is it possible to rebroadcast txes in mempool when the wallet is fully synced?

**Comment by ravenlandpush** [comment]
yes I thinkso. For example;

adam@terminalserver:~$ raven-cli help abandontransaction
abandontransaction "txid"

Mark in-wallet transaction <txid> as abandoned
This will mark this transaction and all its in-wallet descendants as abandoned which will allow
for their inputs to be respent.  It can be used to replace "stuck" or evicted transactions.
It only works on transactions which are not included in a block and are not currently in the mempool.
It has no effect on transactions which are already conflicted or abandoned.

Arguments:
1. "txid"    (string, required) The transaction id

Result:

Examples:
> raven-cli abandontransaction "1075db55d416d3ca199f55b6084e2115b9345e16c5cf302fc80e9d5fbf5d48d"
> curl --user myusername --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "abandontransaction", "params": ["1075db55d416d3ca199f55b6084e2115b9345e16c5cf302fc80e9d5fbf5d48d"] }' -H 'content-type: text/plain;' http://127.0.0.1:8766/

It is possible to delete the mepool.dat, but in some cases it hits the wallet and you still need to wait I think. So you raise something that is potentially important. How to reliably make sure that wallet has an easy 'zap-free' way of resolving this? Or a button perhaps that is capable of abandoning and 'zapping' such transactions if the user so desires it in raven-qt. seems like a good call.


Best,
Adam

**Comment by ravenlandpush** [comment]
It is possible to delete the mepool.dat, (since above not working if it hits it) but in some cases it hits the wallet and you still need to wait I think. So you raise something that is potentially important. How to reliably make sure that wallet has an easy 'zap-free' way of resolving this? Or a button perhaps that is capable of abandoning and 'zapping' such transactions if the user so desires it in raven-qt. seems like a good call.

Removed my previous post as it was a bit misleading really.

Best,
Adam

**Comment by blondfrogs** [comment]
Added functionality that will ask the user if they still want to send a tx without being synced to the develop branch. Closing this issue for now
