### ISSUE TITLE
GUI Develop 08117f7 - Limited Tag Token Creation (max 10) and GUI Tag asset reissue not possible

### ISSUE THREAD

**Issue by lsji07** [RavenProject/Ravencoin#629]
### Describe the issue

New testnet wallet GUI (Raven Core version v3.0.0.0-08117f7 (64-bit)) has a hard coded limit in the GUI of maximum 10 quantity. The GUI wallet also doesn't allow reissuing the Qualifier Assets (or tags) once created.

### Can you reliably reproduce the issue?

Yes

#### If so, please list the steps to reproduce below:
1. Try reissue Qualifier asset (already created initially once) under asset management section of the wallet gui.
2. Nothing (i.e none of the already created Qualified Assets) appears in the drop down menu to select the asset tags and reissue.

### Expected behaviour
Reissuing the tags is fairly important. Especially for me as the initial Qualifier asset token creation was hampered by the asset quantity box size being small. I could only see 10, and despite typing in 1000, only created 10. I kinda assumed the trailing zeros were hidden not missing! My oops... seems that box is limited to 10. That shouldn't be that restricted that much...

Image of tag token quantity and box being a little bit tiny....
![image](https://user-images.githubusercontent.com/39772657/62825361-3fbda500-bba2-11e9-98a8-b2026cd436c2.png)

**Comment by ravenlandpush** [comment]
This looks like it could be related to https://github.com/RavenProject/Ravencoin/issues/628,

Best,
Adam

**Comment by ravenlandpush** [comment]
and #626

**Comment by hans-schmidt** [comment]
Qualifier qty of 0<qty<=10 and non-reissuable is by design, Perhaps open to debate, but not bugs

**Comment by jeroz1** [comment]
Then it’s quite important to know that beforehand!

**Comment by ravenlandpush** [comment]
I had no idea of this either. Perhaps raven-qt or raven-cli could make this a bit clearer so users don't get an unexpected surprise.

Best,
Adam

**Comment by lsji07** [comment]
Updating and closing this github issue as my queries were answered on discord.

This should explain the rational behind a max of 10 qualifier assets and not being able to reissue them in the event you would need more than initially issued.

1. The development team think of qualifier as owner tokens. Which you usually only get 1 of. However we wanted to also be able to send them to people who can tag on a qualifier token owner's behalf. Which is why the developers made them have multiples when created (upto 10 currently for testnet). 
2. The reason we can't reissue them is because they don't have their own ADMIN/owner tokens. `#KYC` doesn't have the `#KYC!` asset or admin token to allow reissuing.
3. The qualifier token provides for a new tag issuer type role.  This allows restricted asset owners (companies to comply with governmental authorities) to allow management of their restricted assets via multiple separate wallets and departments.

Additional information.

- @blondfrogs thinks that there maybe potential to changing the max amount for mainnet to 1000 or something like that for additional co-taggers.


- Antispam prevention - Note that currently to tag an address it **burns** RVN. Currently circa 0.01 RVN per address tagged. Removing a tag from an address and freezing an address is free other than the network tx fee.

Throughout testing, we will be finding the best values to incorporate into mainnet.

If anyone thinks the quantity of qualifier token creation (or essentially co-taggers) **should be** reissuable please make a separate issue on github with your reasoning, and the team can discuss it. That way we keep things organized.
