### ISSUE TITLE
CPU Mining on Testnet (and mainnet) commands not correct

### ISSUE THREAD

**Issue by lsji07** [RavenProject/Ravencoin#632]
### Describe the issue

CPU mining on testnet can be activated with `setgenerate true 2` for 2 cores mining etc.

The issue is that `setgenerate false` doesn't work to stop the wallet mining as per bitcoins core wallet implementation. 

Longtime ravencoin testnet tester/users automatically just do `setgenerate true 0` to stop mining but this should really be corrected.

### Can you reliably reproduce the issue?

Yes

#### If so, please list the steps to reproduce below:

1. Start mining with `setgenerate true 2` or however many cpu cores you want to use.
2. Try stop mining with `setgenerate false`. No error message that this command has failed or has changed to another command. `getmininginfo` quickly verifies that the wallet is still mining.
3. Then do what we all have been doing for ages and do `setgenerate true 0` to stop mining in the wallet.

### Expected behaviour
Mining should stop once the command `setgenerate false` is given. 

### Actual behaviour
Nothing.

### Screenshots.
![image](https://user-images.githubusercontent.com/39772657/62837287-c8514980-bc65-11e9-9d9b-2922f146578e.png)

### What version of bitcoin-core are you using?
Raven Core version v3.0.0.0-08117f7 (64-bit)

### Machine specs:
- OS: Windows 64 Pro
- CPU: AMD 1850x
- RAM: 48GB
- Disk size: 250GB SSD for Os,  2TB HD with testnet chain/data
- Disk Type (HD/SDD): Mixed

**Comment by danielhiatt** [comment]
Further investigation needed.

**Comment by spyder46n2** [comment]
I've re-tested this and the process and threads stop when `setgenerate false` is set.  From the debug log the following is issued:
```
2019-08-22 20:49:47 RavenMiner -- terminated
2019-08-22 20:49:47 RavenMiner -- terminated
2019-08-22 20:49:47 RavenMiner -- terminated
```
This was validated on Windows.
`getmininginfo` displays the same information regardless of sending `setgenerate false` or `setgenerate 0`:
```
setgenerate false
3 of 4
getmininginfo
{
  "blocks": 385138,
  "currentblockweight": 4000,
  "currentblocktx": 0,
  "difficulty": 0.001176333705921276,
  "networkhashps": 118709.6318059299,
  "hashespersec": 119063,
  "pooledtx": 0,
  "chain": "test",
  "warnings": ""
}
setgenerate true 0
0 of 4
getmininginfo
{
  "blocks": 385138,
  "currentblockweight": 4000,
  "currentblocktx": 0,
  "difficulty": 0.001176333705921276,
  "networkhashps": 118709.6318059299,
  "hashespersec": 119063,
  "pooledtx": 0,
  "chain": "test",
  "warnings": ""
}
```
Additionally no new blocks were generated, while mining on Testnet I was getting a block every minute or two, I waited 10+ minutes after sending `setgenerate false`.
