### ISSUE TITLE
Transcation not completing and not showing in Blockchain

### ISSUE THREAD

**Issue by nhasanit** [RavenProject/Ravencoin#64]
Sent a transaction from Desktop Wallet to Cryptobridge wallet. Wallet shows 36 confirmations but transaction now showing up in Blockchain explorer nor did it send to Crytobridge wallet. 

http://explorer.threeeyed.info/address/R9ot8yZ7zWTMxAiTJU6xuy8EroMzZg4E8b

Status: 36 confirmations
Date: 4/15/2018 19:57
To: R9ot8yZ7zWTMxAiTJU6xuy8EroMzZg4E8b
Debit: -9430.99998524 RVN
Transaction fee: -0.00001476 RVN
Net amount: -9431.00000000 RVN
Transaction ID: 736f6d282d444dcc8489550b0fa4cbf3d2cbe0695ddef07ead4c313361ab5c81
Transaction total size: 1404 bytes
Output index: 0
<img width="601" alt="screen shot 2018-04-15 at 8 55 52 pm" src="https://user-images.githubusercontent.com/26906506/38785625-f096fe82-40ef-11e8-905b-7759610df4c6.png">

**Comment by a37k** [comment]
Threeyed is stalled. Please use other explorer to explore the state of the blockchain.

**Comment by YNOSPaw** [comment]
Did anyone verify the MD5 or SHA256 checksum before installing the wallet, cuz the MD5 checks out but the SHA256 does not. i suspect some tampering. :(

**Comment by nhasanit** [comment]
It showed up in the morning on the other explorer.
