### ISSUE TITLE
When dose testnet change to HashX16RV2

### ISSUE THREAD

**Issue by ruyichang** [RavenProject/Ravencoin#659]
I am running the suggested version v3.2.0 on testnet.
Is this testnet activation  at TESTNET_X16RV2ACTIVATIONTIME = 1569931200?

where can I get the code v3.2.0

**Comment by jeroz1** [comment]
Develop tree or https://raven-nightly-builds.ravencoin.org/

**Comment by DinoStray** [comment]
From develop branch, 
static const uint32_t TESTNET_X16RV2ACTIVATIONTIME = 1567533600;
So by now, testnet is X16V2

**Comment by blondfrogs** [comment]
Closing as this seems to be answered
