### ISSUE TITLE
14.04 support

### ISSUE THREAD

**Issue by jbnl** [RavenProject/Ravencoin#66]
Please add cmake files with Boost 1.55 library support so we can compile this on ubuntu 14.04.

**Comment by graze1234** [comment]
not wanting to start a fight or anything, but out of interest are there lots of people still running 14.04? 17.04 out shortly, or was that a typo?

**Comment by jbnl** [comment]
Most pools run on node 0.10.48, ubuntu 14.04 - which comes with boost 1.55 yes :-)

**Comment by bedri** [comment]
Did you mean 16.04? If pools are still running 14.04 then they are the ones who should upgrade to 16.04. 14.04 shouldn't be used unless some very old software requires it and this is not the case in Bitcoin software family.
16.04 supports libboost 1.58. I am using it in my rig without any issue for all my mining operations and i can compile all healthy wallets in it as well. Besides world now using libboost 1.66 and i cannot understand why anyone insist on using 1.55. Pool server should be dedicated to pooling work. It should not used as a multi purpose server.

Thanks

**Comment by jbnl** [comment]
No, I really do mean 14.04 - as repeatedly stated above. There is no typo here. 14.04

Nearly all cryptonote pool software runs only without having to downgrade half your libraries on 14.04. 

And its not a multi purpose server, its only running pools. The pools need the daemon and wallet to run, so thats why I ask for a compatible version.

**Comment by bedri** [comment]
Is this issue solved? @jbnl did you managed to work it out? Can we close this issue?
