### ISSUE TITLE
Is there any api endpoint to get number of transactions?

### ISSUE THREAD

**Issue by RudrikaFichadiya** [RavenProject/Ravencoin#662]
Have already visited to given link where I've founded api endpoint to get raw data,
https://github.com/RavenProject/Ravencoin/issues/591

Similar to that is there an endpoint to get list of transactions?

**Comment by danielhiatt** [comment]
Don't think this exists.  Need more info on the use case.

**Comment by RudrikaFichadiya** [comment]
@danielhiatt , Use case is does not exists anymore. Closing these issue. 
If this issue is required by anyone, please reopen this!
