### ISSUE TITLE
Add ability to send admin token to one address and asset tokens to one/multiple different addresses with createrawtransaction

### ISSUE THREAD

**Issue by MangoFarmAssets** [RavenProject/Ravencoin#675]
When issuing/reissuing a RVN asset using the createrawtransaction RPC call, it would be helpful for some use cases to have the ability to send the admin token to the issuer (Alice) and send the created assets themselves directly to one or more recipients (Alice, Bob1, Bob2, ..., Bobn) as part of the original issuance transaction.  The current createrawtransaction RPC call automatically issues both the admin token and all assets only to Alice.  

We have a specific use case in mind, where Alice wants to create an asset with encrypted attachments using soon-to-be proposed RIP11/14.  Recipient addresses are known at the time of asset issuance.  Currently, Alice needs to send the asset to herself, then transfer it in a second step to each recipient at their encryption receiving address.  We would love to cut this step out and allow the admin token to be sent to Alice and allow the tokens to be sent directly to the recipients at their encryption receiving addresses.  Other use cases are conceivable, and this functionality would add value of general applicability.

We propose to add to the createrawtransaction RPC call the ability to include an optional "admin_address" and array of "recipient_addresses" (or similar functionality) within the JSON object for issuing/reissuing assets and unique assets.

Thanks for considering this issue.

**Comment by blondfrogs** [comment]
@MangoFarmAssets After doing some research on whether this type of transaction can be built I found that it is part of the consensus rules that when issuing an asset. The owner and the asset must be sent to the same address. This code can be found in assets.cpp
<IsNewOwnerTxValid> function line 630-633

<    if (ownerAddress != address) {
        errorMsg = "bad-txns-owner-address-mismatch";
        return false;
    }>

**Comment by MangoFarmAssets** [comment]
OK thanks very much for checking @blondfrogs
