### ISSUE TITLE
Will add aarch64 build?

### ISSUE THREAD

**Issue by kawww** [RavenProject/Ravencoin#685]
I found arm build add, that's great.

I tried to use arm build on termux with ubuntu...but ubuntu is 19, not support 32 arm. I couldn't find a 32-bit ubuntu or packages to run 32-bit arm build.

https://blog.bitcoinprivacy.net/2019/05/25/ive-built-the-worlds-cheapest-bitcoin-node-and-so-can-you/

Then I try aarch64 bitcoin build, it worked. 

https://bitcoin.org/bin/bitcoin-core-0.18.0/

Maybe raven aarch64 will work too. But I don't know how to make aarch64, no skill about this.

If we have aarch64 build, it is great we can run raven full node on android and use rpc to operate.

Then every android app could read/write data on ravenchain.

update 11.11

I try  to use this (https://github.com/RavenProject/Ravencoin/blob/master/static-builds/staticbuild.md) to build one aarch64 to test and success on android with termux. I think if there is an offical build will be easy for developer to use for android. ^^

updata 01.03

I found termux support package https://github.com/termux/termux-packages

If we have package in termux, We can run a rvn full node on any android like bitcoin, only need to run pkg -i bitcoin. This will be great for rvn to have more nodes. Then every app and devices in the world could use ravencoin rpc peer-to-peer to read/write local datas from/to the blockchain without any intermediaries.

**Comment by giovannirco** [comment]
I would love to have an aarch64 pre-built binary available to download as well, makes the deploy process around here a bit better. Is there any plans to get this done?

**Comment by spyder46n2** [comment]
Mostly this has been as they have been asked for. I'll add it to our list...

**Comment by giovannirco** [comment]
Thanks for replying so fast! I'm looking forward to this

**Comment by giovannirco** [comment]
Friendly bump :D

**Comment by fdoving** [comment]
Looking at this now. Don't have the hardware to test, @giovannirco up for testing? You can find me as fdov at discord if interested. I can also link binaries here if you prefer.

**Comment by fdoving** [comment]
Can be closed. @HyperPeek
