### ISSUE TITLE
getaddressbalance rpc call with includeAssets=true says "Assets aren't active"

### ISSUE THREAD

**Issue by JonPizza** [RavenProject/Ravencoin#697]
### Describe the issue

Running `raven-cli getaddressbalance '{"addresses": ["RSendHereToGetListedRavenvotecTNQG"]}' true`

returns 

```
error code: -8
error message:
Assets aren't active.  includeAssets can't be true.
```

#### If so, please list the steps to reproduce below:
1. run ravend with -assetIndex and -reindex
2. run `raven-cli getaddressbalance '{"addresses": ["RSendHereToGetListedRavenvotecTNQG"]}' true`

### Expected behaviour

Return address balance with assets

### Actual behaviour

The commend returns 

```
error code: -8
error message:
Assets aren't active.  includeAssets can't be true.
```

### What version of bitcoin-core are you using?

2.5.1, downloaded the binaries

### Machine specs:
- OS: Linux (Ubuntu)
- CPU: Intel i5
- RAM: 4gb
- Disk size: 256gb
- Disk Type (HD/SDD): SSD

**Comment by JonPizza** [comment]
Error in syncing the blocks.

**Comment by strapidinnovation** [comment]
Were you able to solve this ?
