### ISSUE TITLE
This is not working with Mac OS High Sierra 2.7 GHz Intel Core i5

### ISSUE THREAD

**Issue by acassity** [RavenProject/Ravencoin#7]
### Describe the issue
This is not working on my computer for some odd reason.

#### If so, please list the steps to reproduce below:
1. Reboot
2. Updated 
3. Reinstalled the application several times

### Expected behaviour
Tell us what should happen
Work on my Mac please I did download the correct version Raven-Qt.dmg
### Actual behaviour
Tell us what happens instead
Raven Core 2 cannot be opened because of a problem.

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

![screen shot 2018-01-06 at 10 29 48 pm](https://user-images.githubusercontent.com/35185372/34646958-a0d4d190-f332-11e7-8494-b2eb0abab69e.png)

![screen shot 2018-01-06 at 10 30 05 pm](https://user-images.githubusercontent.com/35185372/34646955-7a74f264-f332-11e7-9b22-7a827101849f.png)
### What version of bitcoin-core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.

### Machine specs:
- OS: macOS High Sierra Version 10.13.2
- CPU: 2.7 GHz Intel Core i5
- RAM:8 GB 1600 Mhz DDR3
- Disk size: 1000 GB
- Disk Type (HD/SDD): SATA Macintosh

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by allthat104** [comment]
I think you have to go into Applications, right click RavenCore, click the option Show Package Contents, in the folder Contents, there will be a folder Frameworks.  In that folder, copy the file libboost_system.dylib as the file libboost-system-mt.dylib.

**Comment by jacksonpchen** [comment]
If your question has been answered, please close this issue.
