### ISSUE TITLE
Official Ravencoin development forum?

### ISSUE THREAD

**Issue by cryptotym** [RavenProject/Ravencoin#70]
Does Ravencoin have an official place for devs to discuss what they are working on and where they can request help?

I propose, if this does not exist, that we create it to help the community get involved. I think a lot of people are relying on the creators to complete the project and don't know where they can contribute.

Thanks!

**Comment by MSFTserver** [comment]
yea come by the discord tons of faces and help awaiting over in the awesome community we have built
https://discord.gg/KKSV788

**Comment by jacksonpchen** [comment]
@cryptotym Please close this ticket.
