### ISSUE TITLE
[Testnet] Mempool and freeze/unfreeze issues

### ISSUE THREAD

**Issue by Scotty0448** [RavenProject/Ravencoin#702]
Several hours ago I was testing the latest develop branch and caused a mempool issue that looks like it might have affected others as well. I had noticed when using the freezerestrictedasset command that I could use the exact same command successfully again while the first one was still in the mempool waiting.  Same for unfreezerestrictedasset, once the asset was frozen.  I was guessing that wasn't actually a problem, though wasn't sure.

I then tried using the freeze command multiple times in quick succession followed by the unfreeze command multiple times.  Somehow I ended up with a mempool that had one freeze transaction waiting and multiple unfreeze transactions after it, all for the same asset.  After that point I could no longer get anything successfully processed and nothing was clearing out of my mempool.

I've noticed now that all the seed nodes are stuck at block 88109, which I believe was at or near the time of my testing, although I didn't check the block height at the time.  Clearing my mempool, resyncing, reindexing and even fully rebuilding my blockchain hasn't been successful at getting my personal node fully working again, but that appears now to be because it keeps failing to maintain connections to the seed nodes.  Although it is holding one single connection to one other node.

I've been testing with v3.2.1.0-d0b5ea6 prebuilt image for osx.  The restricted asset I was testing with is named $TEST.

**Comment by Scotty0448** [comment]
Incidentally, my rebuilt node is fully synced and is keeping in sync with that one single node (not a seed node).  But I'm not able to do even a simple RVN send transaction.  It just sits in my mempool.  So perhaps that one node I'm connected with was affected by my earlier mempool issue as well, and maybe the seed nodes problems are something unrelated.

**Comment by jeroz1** [comment]
Sounds very similar to my previous issue #628

**Comment by blondfrogs** [comment]
Fixed in #704
