### ISSUE TITLE
Ubuntu 18.04 Support

### ISSUE THREAD

**Issue by jczuchnowski** [RavenProject/Ravencoin#72]
I'm unable to run `./ravend -daemon` on 18.04.

The error is:
```
./ravend: error while loading shared libraries: libboost_system.so.1.62.0: cannot open shared object file: No such file or directory
```
My current libboost-dev version is `1.65.1.0ubuntu1`

**Comment by fokep** [comment]
It should run if you install the all-dev pack: 
`sudo apt-get install libboost-all-dev`

I recommend you check out all dependencies [specified here](https://github.com/RavenProject/Ravencoin/blob/master/doc/build-unix.md)

**Comment by jczuchnowski** [comment]
I do have the all-dev package. 
```
libboost-all-dev is already the newest version (1.65.1.0ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```
I followed the instructions on https://github.com/RavenProject/Ravencoin/tree/master/binaries/release/linux before creating this issue.

**Comment by fokep** [comment]
I made a test build from source on 18.04 LTS. If you want to test that you can get it from [here](https://github.com/fokep/raven-builds/releases), but I recommend you don't trust strangers on the web and rather build it for your self.

Build was made on a clean, updated VM with this recipe:

Download the repo:
`git clone https://github.com/RavenProject/Ravencoin.git`

General build requirements:

`sudo apt-get install build-essential libtool autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils python3`

All boost development packages:
`sudo apt-get install libboost-all-dev`

BerkeleyDB from the bitcoin repo:
```
sudo apt-get install software-properties-common
sudo add-apt-repository ppa:bitcoin/bitcoin
sudo apt-get update
sudo apt-get install libdb4.8-dev libdb4.8++-dev
```

For upnp:
`sudo apt-get install libminiupnpc-dev`

ZMQ API:
`sudo apt-get install libzmq3-dev`

Qt 5 for GUI:
`sudo apt-get install libqt5gui5 libqt5core5a libqt5dbus5 qttools5-dev qttools5-dev-tools libprotobuf-dev protobuf-compiler`

libqrencode:
`sudo apt-get install libqrencode-dev`

```
./autogen.sh
./configure
make
make install # optional
```

Binaries will be found in /Ravencoin/src/

**Comment by fokep** [comment]
That's right, per my message above: people don't always have honest intentions and could easily include malware in binaries and it can be very hard to discover. With source code you can at least search through it (or trust that others will, [and fortunately some people do](https://www.reddit.com/r/Python/comments/8hvzja/backdoor_in_sshdecorator_package/)).

Official builds will be made but as long as building from source works fine there is no rush IMHO. For Fedora 28 it's a different story..... :-)

Just keep your issue open and it should be closed when this happens.

**Comment by bedri** [comment]
If the compiling person attach an checksum of the binary and the fixed or modified source code, then others can easily compile the source code, get the checksum and compare it to the given one and confirm about absence of any malware. Just an idea :)

**Comment by tmartinx** [comment]
Would be awesome to make Ravencoin available via snap and/or flatpak packages!   :-P
