### ISSUE TITLE
3.3 Windows QT

### ISSUE THREAD

**Issue by summertimeisfun** [RavenProject/Ravencoin#726]
This issue tracker is only for technical issues related to ravencoin-core.

General ravencoin questions and/or support requests and are best directed to the [Ravencoin Discord](https://discord.gg/GwtXdyc).

For reporting security issues, please direct message one of the core developers in discord.

### By replacing the 3.3 with 2.5.1 binaries I could connect to remote peers and download blocks again.  It appears the issue is around using an SMB mount for storage.   As part of the 3.3 install package, it was unable to use a mounted drive for storage but if you cancelled out, the files were installed and you could launch the client.  (i assume the installer would fail and rollback when clicking cancel, it did not)  A SMB SAN previously worked fine <= 2.5.1 as a storage location.   I tried the startup parms of a known good host using the addnode parm and connect parm, neither were successful in getting the chain to download. 

Once I used a local storage location the chain started to sync and I have nodes in my peer list.

Only replacing the binaries or downgrading was successful in getting the chain to sync again.

### Machine specs:
- OS: Windows 10 1903
- CPU: Intel m5-6Y57 
- RAM: 8GB
- Disk size: 20TB - SMB  / 256 GB local NVME 
- Disk Type (HD/SDD):  SAN / NVME

### Any extra information that might be useful in the debugging process.
During debugging i could see the qt node connect to a 3.3 daemon but after a few minutes the debug out from the daemon showed a timeout of my qt node.  it never fully completed the handshake when using the getpeerinfo command with the cli.

last entries in the debug.out log from the fail to connect.

2020-01-11 16:02:42 38 addresses found from DNS seeds
2020-01-11 16:02:42 dnsseed thread exit
2020-01-11 18:19:16

**Comment by summertimeisfun** [comment]
this can be closed.  found a network routing issue.

**Comment by summertimeisfun** [comment]
this can be closed.  found a network routing issue.

**Comment by summertimeisfun** [comment]
turns out it wasn't a routing issue.  i've fixed everything on my network to ensure only a single route exists to the destination and the share is accessible.  I can't install into a remote share and launch the 3.3 qt on windows.  <= 2.5.1 works with the remote SMB share.

**Comment by blondfrogs** [comment]
@summertimeisfun This is an interesting issue. Can you confirm you are using 3.3.2?

**Comment by blondfrogs** [comment]
@summertimeisfun was this fixed with the latest release 4.1.0?

**Comment by nyakze** [comment]
Could it be that your wallet node was just in split chain, that's why 3.3 peers ignored it? Deleting blockchain and starting from scratch is usually the best way to deal with it.
