### ISSUE TITLE
Error DeriveNewChildKey: Writing HD chain model failed

### ISSUE THREAD

**Issue by melvjoshua** [RavenProject/Ravencoin#746]
Hi Team, I get error `DeriveNewChildKey: Writing HD chain model failed` when send Ravencoin. How to fix it?

I am using v3.3.2

**Comment by jeroz1** [comment]
User reported that this issue was solved by replacing wallet.dat with a backup file in telegram.

**Comment by blondfrogs** [comment]
Always keep a backup. It seems like your wallet.dat was corrupted somehow. This is the first incident we have seen where this has happened. 

Thank goodness you had a backup. We will make sure to keep an eye out for this
