### ISSUE TITLE
Failed to create Restricted Asset with Sub Qualifier

### ISSUE THREAD

**Issue by sudux** [RavenProject/Ravencoin#750]
### Describe the issue

Can't create Restricted Asset with Sub Qualifier.

"The verifier string has two operators without a tag between them."

#### If so, please list the steps to reproduce below:

both gui or command line, can't create

### Screenshots.

![111](https://user-images.githubusercontent.com/25874991/74323403-6f06d600-4dc0-11ea-9f80-6e1c14c7f097.jpg)

### What version of bitcoin-core are you using?

v3.3.2.0-3499cadd9

**Comment by TronBlack** [comment]
The verifier string should use logic to require one or more tags.
Example:  "#SSS & #111" to require both tags.  "#SSS | #111" to require either tag. 
Or leave the verifier string blank.  That'll set it to 'true' and allow it to go to any address.
You can use more complex logic with & (and) | (or) ! (not) and parentheses for precedence.

**Comment by sudux** [comment]
> 
> 
> The verifier string should use logic to require one or more tags.
> Example: "#SSS & #111" to require both tags. "#SSS | #111" to require either tag.
> Or leave the verifier string blank. That'll set it to 'true' and allow it to go to any address.
> You can use more complex logic with & (and) | (or) ! (not) and parentheses for precedence.

Thank you for replying and great work. I really like Qualifier and Restricted Asset.

 "#SSS & #111" is for #SSS and #111 two  different Qualifier, this is no problem.

![222](https://user-images.githubusercontent.com/25874991/74399778-df603680-4e56-11ea-99db-f8212141a543.jpg)

The problem is "#SSS"'s Sub Qualifier "#SSS/#111". 

![222](https://user-images.githubusercontent.com/25874991/74399736-be97e100-4e56-11ea-8891-1b63f2f4cbb8.jpg)

**Comment by blondfrogs** [comment]
@sudux
We built the Qualifier Asset to show the logical path of issued Sub Qualifiers

This means that when computing if an address contains a qualifier we only check to ROOT name. In this case #SSS. 

The root of #SSS/#111 is #SSS. 

The reason we allow #SSS/#111 to be made is so companies can issue certain token to different deparments in charge on assigning qualifiers, for example #SSS/#CARDEPARTMENT, #SSS/#ACCOUNTING

All of these Qualifiers have the same root of #SSS.

Only root names can be used in the Verifier String

I hope this helps.

**Comment by sudux** [comment]
> 
> 
> @sudux
> We built the Qualifier Asset to show the logical path of issued Sub Qualifiers
> 
> This means that when computing if an address contains a qualifier we only check to ROOT name. In this case #SSS.
> 
> The root of #SSS/#111 is #SSS.
> 
> The reason we allow #SSS/#111 to be made is so companies can issue certain token to different deparments in charge on assigning qualifiers, for example #SSS/#CARDEPARTMENT, #SSS/#ACCOUNTING
> 
> All of these Qualifiers have the same root of #SSS.
> 
> Only root names can be used in the Verifier String
> 
> I hope this helps.

Thank you for replying. I understand. 

If I want to use Sub Qualifiers "#SSS/#111" as Verifier. I need to have one root names for verifier and one root/sub name for assigning.

I think this limit is a trouble that everyone need  to spend 1000*n+100*n rvn for verifier, and if no limit, only need 100*n rvn.

Sub Qualifier is good for creating Restricted Asset too. Cheap tags help create more  Restricted Asset.

I suggest if it is easy, sub Qualifier  can be used in the Verifier String.

I am not company, but if I want to create club, I will create #CLUB/#CAR, 
#CLUB/#MOVIE, #CLUB/#CAR/#2019,  #CLUB/#CAR/#2020 for for different members. 

These members are different with each other and if only root names can be used in the Verifier String, the members are the same.

**Comment by blondfrogs** [comment]
This is a use case that we can add later. Am I okay with closing this issue for now?

**Comment by sudux** [comment]
> 
> 
> This is a use case that we can add later. Am I okay with closing this issue for now?

Yes, thanks very much. Tags are very useful and creative tools.

**Comment by blondfrogs** [comment]
Closing
