### ISSUE TITLE
[BUG - Fix this with next fork release]Message only support 28-words asset?

### ISSUE THREAD

**Issue by kawww** [RavenProject/Ravencoin#752]
I am testing messages. 

![22](https://user-images.githubusercontent.com/39939137/74881360-22b32b80-53a8-11ea-8a8b-f7b40cc9286f.jpg)

I found 29 or 30 words asset not support messages.

Error: The transaction was rejected! Reason given: bad-txns-transfer-asset-bad-deserialize (code -4)

![11](https://user-images.githubusercontent.com/39939137/74881393-32cb0b00-53a8-11ea-948b-3de432744863.jpg)

v3.3.2.0-3499cadd9 testnet

**Comment by blondfrogs** [comment]
This is due an an issue with serialization. This means that no asset above text test size of 28 is going to be able to be transferred until the fix is rolled out over a hard fork release. 

If we change the algorithm. This fix will be wrapped into that release.

**Comment by kawww** [comment]
Got it. Thanks~

I found sendmessage has same problems. Maybe 27 words.


sendmessage 12345678901234567890ABCDEFGH Qmbuw1XZV8i4uFucmKSSYH7gGhD5B1B1NPMseh9tp5hgea

Error: The transaction was rejected! Reason given: bad-txns-transfer-asset-bad-deserialize (code -4)



sendmessage 12345678901234567890ABCDEFG Qmbuw1XZV8i4uFucmKSSYH7gGhD5B1B1NPMseh9tp5hgea

[
  "a2fc8cb77a9aad4776286fa8b4dd3cf17148ad34820ca736d35525807965785b"
]

**Comment by blondfrogs** [comment]
Yes that is correct @kawww. We will get this fixed up with the algo change release

**Comment by blondfrogs** [comment]
Fixed in #774
