### ISSUE TITLE
Wallet is empty

### ISSUE THREAD

**Issue by Blisk** [RavenProject/Ravencoin#756]
This issue tracker is only for technical issues related to bitcoin-core.

General ravencoin questions and/or support requests and are best directed to the [Ravencoin Discord](https://discord.gg/GwtXdyc).

For reporting security issues, please direct message one of the core developers in discord.

### Describe the issue
I have send 1500 RVN to binance end I have in my wallet -1500 but in binance walet I have nothing
I also have fev ravencoins in wallet and when it start to synchroise it always stuck on 97%.
The I google it and see I should update wallet so I have download new wallet and update it, but now I can see transaction -1500 to binance but binance walet is still empty and also my ravencoin wallet is empty and it should not be.
How to get those coins back?

### Screenshots.
[slika](https://user-images.githubusercontent.com/2773050/75624863-b8c13000-5bb8-11ea-86e5-c3e0a4eddaf8.png)

### What version of bitcoin-core are you using? 3.3.2.0
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.

### Machine specs:
- OS: win 10
- CPU: ryzen 
- RAM: 32 Gb
- Disk size: 500 GB
- Disk Type (HD/SDD): ssd

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.
https://privatebin.povej.net/?f34d7dc350140831#3CxhCQdKYgYkNevaccsQ22YJLBzp6tgRw8fADWSoZG3b

**Comment by jeroz1** [comment]
Is your transaction visible on https://ravencoin.network/ ?

**Comment by Blisk** [comment]
yes it is but all is 0

**Comment by jeroz1** [comment]
What do you mean with “all is 0”? 

Do you have a link to the transaction id?

**Comment by blondfrogs** [comment]
@Blisk Has this been resolved. It might find it easier to get support by using the Discord support channel. 

Github is for reporting bugs in the program. I think this might be a network issue. Probably can be resolved by abandoning the transaction

**Comment by Blisk** [comment]
Still no changes it is 0 in wallet and 0 in binance web site.
Transaction fee: -0.00026100 RVN
Net amount: -1500.00026100 RVN
Transaction ID: 60b5db65d4650d9da174a1b653f7ad789ceeee839efee61e73c24c5c986bd2a1

**Comment by jeroz1** [comment]
This transaction is not on the Ravencoin network and must have happened on a fork, which means your coins are still in the same address on the current chain.

Updating and resyncing blockchain on Windows:
- Close your wallet
- Install the latest Wallet version (3.2.2)
- Press Windows+R
- Type %appdata%\Raven and press enter
- In that folder delete everything BUT NOT WALLET.DAT (if you rather do not delete stuff, just put it in a different folder)
- Make a copy of wallet.dat and store it somewhere safe. Your keys are in there.
- Open your wallet again. It will download the chain from the start.
- Add some good nodes: go to help > debug window > console, and type:

addnode 192.99.16.198:8767 add
addnode 144.217.66.119:8767 add
addnode 144.217.71.156:8767 add

Response will be "null"
I picked those nodes from www.ravennodes.com

Syncing will take a couple of hours.

If the problem persists after this sync, the transaction might still be stuck in your wallet mempool. You can clear it under: help > debug window > wallet repair > zapwallettxes

**Comment by blondfrogs** [comment]
@Blisk Did you follow @jeroz1 instructions. Did this solve your issue?

**Comment by Blisk** [comment]
yes I did and still didn't solve the problem still missing 1500 RVN
