### ISSUE TITLE
Change Explorere On ravencoin.org

### ISSUE THREAD

**Issue by Machestar** [RavenProject/Ravencoin#76]
Wasn't sure how to contact you guys so trying this. The explorer linked to from ravencoin.org is offline more then it is on.

**Comment by TronBlack** [comment]
Currently linked to https://ravencoin.network/

That is the most reliable one I'm aware of.   If you know of a community block explorer that is more reliable, please post it here.   I'm leaving this issue open for now.

**Comment by TronBlack** [comment]
Closing issue.  Please re-open if https://ravencoin.network/ is not reliable.
