### ISSUE TITLE
testnet faucet

### ISSUE THREAD

**Issue by shenyaqi9527** [RavenProject/Ravencoin#760]
Where can I get the testnet coin

**Comment by lsji07** [comment]
Post a testnet address and I'm sure some will magically appear.

**Comment by shenyaqi9527** [comment]
3MxE5Xqr23BoTPFTCDk8CbJQg5V1DF9pcCU

**Comment by shenyaqi9527** [comment]
mmAfb87UBi9QHog8ixAZsbsAxFV5Q7NRen @lsji07

**Comment by lsji07** [comment]
Should be sorted now. I sent some over. Can this issue be closed @shenyaqi9527
