### ISSUE TITLE
BIP44 UI Improvements

### ISSUE THREAD

**Issue by TronBlack** [RavenProject/Ravencoin#768]
Improvement to fix an intimidating dialog for new users
Solution: 
Dialog with [New Wallet], or [Recover Wallet]
New Wallet should go to something similar with the words filled in (as if they hit [Generate], should have a button [Give me different words] which does what [Generate] does now.
[Recover Wallet] can go to something similar with a [Recover] button (not import), and remove [Generate] option.
[Cancel] - Gives dialog twice about “If you cancel, the word list will be generated….” - twice if you say No (small bug)
“Import Recovery Phrase” - Should be “Enter your 12-word Backup Seed Phrase"
“Recovery Phrase” should instead be “12-word Seed” or “12-word Backup Seed Phrase" in the instructional text
Cosmetic
The “tab” name should be named “New Wallet” or “Recover Wallet” based on the initial decision.
If not too difficult, make the tab look less like a button.

**Comment by fdoving** [comment]
@hans-schmidt has this pretty much covered with his raventoo-qt fork.
I hope he can provide a PR.

**Comment by hans-schmidt** [comment]
My improvements for a less confusing mnemonic seeds gui consisting of three separate windows has been merged as PR #939.

It has been suggested that what I call an "optional Passphrase to protect your seed words" should instead be called something like "optional extra seed words" or "mnemonic passphrase" to distinguish it from the separate "wallet encrypt passphrase" used to optionally encrypt the "wallet.dat" file from the main menu, and which is never mentioned in my mnemonic seed gui.

Additional feedback is welcome.

**Comment by fdoving** [comment]
merged to develop.
