### ISSUE TITLE
Include a list of relatively stable IPs (ipv4 and ipv6) first, with domain name based seed nodes as last resort.

### ISSUE THREAD

**Issue by TronBlack** [RavenProject/Ravencoin#779]
This will create a more distributed network, and put less load on the seed nodes that are tied to domain names like bitactivate and ravencoin.org.

This code is already in Ravencoin (inherited from BTC code).  IP addresses of stable nodes were removed when Ravencoin was launched on Jan 3, 2018 because no Ravencoin network existed.

Now that a Ravencoin network exists, the seeder should collect and identify stable nodes and those should be compiled into future Ravencoin binaries.

**Comment by fdoving** [comment]
I think you fixed this with https://github.com/RavenProject/Ravencoin/pull/837 - right?

**Comment by TronBlack** [comment]
Yep, fixed.  4.3.2.1 has a list of IP addresses from which to start, and as a fallback, hits 3 domains with lots of IP addresses each (mostly the same list).
