### ISSUE TITLE
Add sweep function for Asset tokens for User Ease

### ISSUE THREAD

**Issue by lsji07** [RavenProject/Ravencoin#782]
Users could use an easier way to move large utxo sets of both ravencoin and asset tokens. 

Solution could work with #638 as that issue is similar. #638 is more specifically directed to ease user experience within the wallet. 

This would also be valuable to users who created wallets before BIP44 to aid migration.

Propose adding a ```sweeprvn``` RPC call and ```sweepall``` RPC call, with perhaps gui integration later on.

**Comment by fdoving** [comment]
This is merged into develop.
