### ISSUE TITLE
QT compilation warnings for develop branch codes with QT version 5.15.0

### ISSUE THREAD

**Issue by bedri** [RavenProject/Ravencoin#791]
### Describe the issue
I am running OpenSuSE Tumbleweed with QT version 5.15.0 and latest versions of all external libraries. After a couple of recent QT updates, compilation begin to give the following warnings which had not been given a few QT updates ago.
```
qt/utilitydialog.h:45:66: warning: ‘constexpr QFlags<T>::QFlags(QFlags<T>::Zero) [with Enum = Qt::WindowType; QFlags<T>::Zero = int QFlags<Qt::WindowType>::Private::*]’ is deprecated: Use default constructor instead [-Wdeprecated-declarations]
   45 |     explicit ShutdownWindow(QWidget *parent=0, Qt::WindowFlags f=0);
      |                                                                  ^
```
Above warning is given for multiple files: qt/utilitydialog.h, qt/raven.cpp, qt/bantablemodel.cpp, qt/ravenamountfield.cpp, qt/addresstablemodel.cpp
```
qt/optionsmodel.cpp:241:111: warning: ‘QStringList QString::split(const QString&, QString::SplitBehavior, Qt::CaseSensitivity) const’ is deprecated: Use Qt::SplitBehavior variant instead [-Wdeprecated-declarations]
  241 |             QStringList strlIpPort = settings.value("addrProxy").toString().split(":", QString::SkipEmptyParts);
      |                                                                                                               ^
```
```
qt/receiverequestdialog.cpp:47:16: warning: ‘const QPixmap* QLabel::pixmap() const’ is deprecated: Use the other overload which returns QPixmap by-value [-Wdeprecated-declarations]
   47 |     if(!pixmap())
      |                ^
```
### Can you reliably reproduce the issue?
Yes
#### If so, please list the steps to reproduce below:
1. Use QT version 5.15.0.
2. Compile develop branch of Ravencoin github repository.

### Expected behaviour
No warning message should exists during compilation.

### Actual behaviour
Several warning messages given during compilation.

Thank you in advance.

**Comment by bedri** [comment]
The pull request [https://github.com/bitcoin-core/gui/pull/46](https://github.com/bitcoin-core/gui/pull/46) in bitcoin core github solves these warnings.

**Comment by HyperPeek** [comment]
Should be no longer relevant

**Comment by fdoving** [comment]
This can be closed. #1008 is merged to develop.
