### ISSUE TITLE
White Paper link broken

### ISSUE THREAD

**Issue by orcasaurus** [RavenProject/Ravencoin#8]
https://ravencoin.org/raven.pdf
I'd like to read the white paper referred to in the readme. 

Thanks,
News

**Comment by gpip** [comment]
I think they did a general search & replace for bitcoin -> raven, the whitepaper you're looking for doesn't exist.

**Comment by RavenCoinDev** [comment]
Whitepaper for the x16r algo is at:
https://ravencoin.org/wp-content/uploads/2018/01/X16R-Whitepaper-3.pdf

Stay tuned for whitepaper on messaging protocol, and roadmap.
