### ISSUE TITLE
Set constant variables

### ISSUE THREAD

**Issue by blondfrogs** [RavenProject/Ravencoin#800]
In VerifyDB function in validation.cpp:

Update the variables to be constants

`   bool fCheckPoW = true;
        bool fCheckMerkleRoot = true;
        bool fDBCheck = true;`

should use `const static bool ` or `#define `

**Comment by HyperPeek** [comment]
I agree -- not fixed as of now. #define should be safest, as there is no way to get between that and the runtime use. 
Not 100% sure how the compiler handles const static bools here -- I have seen those still residing in memory and loaded at runtime, which we dont want.

**Comment by fdoving** [comment]
I see no reason for the static. `const bool` would be good imo.

**Comment by hans-schmidt** [comment]
I agree with fdoving: const bool appears to be the most appropriate choice.

**Comment by fdoving** [comment]
Can be closed, #1028 is merged to develop.
