### ISSUE TITLE
Frozen asset still getting dividend rewards

### ISSUE THREAD

**Issue by joemarkets** [RavenProject/Ravencoin#840]
if a wallet that has a restricted assets in it. the creator of that restrict asset has for what ever reasoning. deemed you unworthy of using that asset anymore.  The creator freezes the assets in your wallet. if the main asset sends out dividends payments to its hodlers. the frozen asset can still receive dividend rewards/new asset coins. the asset hodler can not move the frozen asset coins but, still receives dividend rewards. then is able to send that reward out of the wallet.

**Comment by a2hill** [comment]
Seems like [CAssetsCache::CheckForAddressRestriction](https://github.com/RavenProject/Ravencoin/blob/master/src/assets/assets.cpp#L4719) should be called during the [owners list snapshot iteration](https://github.com/RavenProject/Ravencoin/blob/master/src/assets/rewards.cpp#L127). I don't know where the `AssetCache` comes from though.

**Comment by lsji07** [comment]
This is correct behaviour. 

The frozen assets should still recieve dividends. Addresses can be frozen for perfectly legit reasons like Rule 144 stock that requires permission to sell.

Use the exception list to omit addresses from dividend. 

The exception list is a parameter when distributing rewards.

The issuer would then decide on restricting paying dividends to specific addresses for specific reasons.

distributereward "asset_name" snapshot_height "distribution_asset_name" gross_distribution_amount ( "exception_addresses" ) ("change_address") ("dry_run")
["Rabc...", "Rdef...] 

Use dry run to test the dividend value and transaction addresses etc before committing to the chain.

**Comment by joemarkets** [comment]
thanks for the solution lsji07 i will close this issue
