### ISSUE TITLE
Windows Defender: Wacatac - false positive?

### ISSUE THREAD

**Issue by qwhex** [RavenProject/Ravencoin#857]
After downloading `raven-4.3.2.0-win64-setup-unsigned.exe`, Windows Defender blocked the file, because it found `Trojan:Win32/Wacatac.B!ml`. I allowed the threat, so I can check the MD5 checksum. The downloaded exe had the correct one.

I guess it's a false positive, though I'm curious if it's a known problem or not. Windows Defender usually categorizes cryptocurrency-related apps (mostly miners) as PUAs with low severity, but in this case it's labeled "severe".

<img width="370" alt="raven_virus" src="https://user-images.githubusercontent.com/16381622/101111415-685d7f80-35db-11eb-9aa7-0dd95f578d17.PNG">

### Machine specs:
- OS: Windows 10 / 19042.630

**Comment by joemarkets** [comment]
A real dev can speak to your question but I will say that the wallet has(had) a miner in it. Miners do give this error on windows.

**Comment by qwhex** [comment]
@joemarkets
Looks like they fixed it 5 hours ago and it was a false positive: https://github.com/RavenProject/Ravencoin/releases/tag/v4.3.2.1

A reply would have been nice though. :/

**Comment by hitnrun66** [comment]
I'd like to reopen this forum...
![Screenshot (27)](https://user-images.githubusercontent.com/64811951/114101357-3e6ae100-988b-11eb-9610-370d9ca341a8.png) Got this message after downloading a Modified Emulator called "Slippi." Its a very well known and trusted fork of Ishiiruka dolphin optimized for smash netplay.
