### ISSUE TITLE
kernel: [1360867.867712] raven-httpworke[839289]: segfault at 7f873d2b0b10 ip 000055d909e3baf9 sp 00007f87dc987fc0 error 4 in ravend[55d9098e0000+c08000]

### ISSUE THREAD

**Issue by joliny** [RavenProject/Ravencoin#861]
kernel: [1360867.867712] raven-httpworke[839289]: segfault at 7f873d2b0b10 ip 000055d909e3baf9 sp 00007f87dc987fc0 error 4 in ravend[55d9098e0000+c08000]

ubuntu 20.04

**Comment by shmocs** [comment]
Jan  7 00:51:51 eu1 kernel: [18993115.716407] raven-httpworke[1436478]: segfault at 7f4690d77150 ip 000055a4af3e0ca8 sp 00007f4708ff6fc0 error 4 in ravend[55a4aee85000+c08000]

same ubuntu 20.04 within docker
:)

seems this is quite a deep issue, and raven devs don't really have a solution for that (https://discord.com/channels/429127343165145089/429133749867905024/928967764109037648)

**Comment by fdoving** [comment]
Related to or duplicate of #838 and I have a proposed fix in pr #1031
