### ISSUE TITLE
Core Wallet Multisig

### ISSUE THREAD

**Issue by MangoFarmAssets** [RavenProject/Ravencoin#865]
### Describe the issue
Creating a multisig address using the createmultisig RPC call and the QT interface or raw transaction to send RVN to works perfectly.  Attempting to send a RVN asset to a multisig address has failed, both with the QT and with a raw transaction.

### Can you reliably reproduce the issue?
Yes
#### If so, please list the steps to reproduce below
(I used the console for this, not the command line)
1. Used the QT console to make a multisig address and redeem script using two external pubkeys 
`createmultisig 2 "[\"pubkey1\",\"pubkey2\"]"`
2.  Attempted to send a RVN asset to the newly-created address using QT interface and received error message "Transaction amount too small."  Thinking the transaction fee may be too low, I used coin control features to increase the fee, to no effect.
3.  Attempted to create a raw transaction to send an asset to the multisig address using the createrawtransaction RPC call (change is omitted below)
`createrawtransaction "[{\"txid\":\"mycoin\",\"vout\":0},{\"txid\":\"myasset\",\"vout\":0}]" "{\"address\":{\"transfer\":{\"MYASSET\":1}}}"`
4. Received a "true" response as expected, used the unsigned hex to sign and send, and received the following output:
`16: bad-txns-op-rvn-asset-not-in-right-script-location (code -26)`
5.  The script for the asset vout in my test example is as follows:
```
 "scriptPubKey": {
        "asm": "OP_HASH160 60df6747069664e385cb329cc0a8527025565f00 OP_EQUAL OP_RVN_ASSET 1672766e7409444156455f434f494e00e1f5050000000075",
        "hex": "a91460df6747069664e385cb329cc0a8527025565f0087c01672766e7409444156455f434f494e00e1f5050000000075",
        "type": "nonstandard"
```
6.  Substituting a regular RVN address for the multisig address in step 3 results in a raw unsigned hex with the following asset vout script, as expected:
```
 "scriptPubKey": {
        "asm": "OP_DUP OP_HASH160 5f77307a6bf099c914ac6f4d1435320f3b58badc OP_EQUALVERIFY OP_CHECKSIG OP_RVN_ASSET 1672766e7409444156455f434f494e00e1f5050000000075",
        "hex": "76a9145f77307a6bf099c914ac6f4d1435320f3b58badc88acc01672766e7409444156455f434f494e00e1f5050000000075",
        "reqSigs": 1,
        "type": "transfer_asset",
        "asset": {
          "name": "DAVE_COIN",
          "amount": 1.00000000
        },
        "addresses": [
          "RHyy4ANeavHcos9zGVxUC96t8ftj7pDKS6"
```

I have replicated this a few times, and have been unable to find any error in the manner of how the transactions were constructed.  I apologize in advance if my learning curve with respect to asset multisig transactions is the issue.  Since I did not manually serialize the transaction - the raw hex was created by the wallet using an RPC call - the source of the error could be in the manner in which the RPC call serializes the script when dealing with multisigs and assets.  I will attempt to do my own serialization at a later time to see if it works, and to compare the scripts.

RVN can be sent to a multisig address created along the lines of the steps above, both through the QT and through the console using a raw transaction, without issue.

### Expected behaviour
The QT should allow RVN assets to be sent to multisig addresses, and the createrawtransaction RPC call should build the script such that RVN assets can be sent to multisig addresses from the QT.

### Actual behaviour
Sending assets to a multisig address fails both at the QT and in the console, with different error codes.

**Comment by fdoving** [comment]
This is expected behavior, based on the existing rules.
The verification of anything related to OP_RVN_ASSET is very strict, and it will not allow any transactions related to assets without it essentially being constructed "properly", and by properly I mean exactly like the wallet constructs them itself.

I disagree with the current very strict rules. 
It will force a hard-fork on any loosening of those strict rules, and implementation of new features.

We face this exact issue when implementing P2SH for assets.
And the "catch-everyting-we-don't-recognize-even-if-it-is-valid-script-and-reject"-checks are the main reason for it.

**Comment by MangoFarmAssets** [comment]
Thanks @fdoving - this issue was actually a precursor to the Foundation proposal for P2SH a few weeks later reflected in #873.  I didn't know it was still here and will close it.  You guys have fixed it on testnet with the P2SH changes, and I made a multisig asset TX yesterday morning to confirm.  [(https://rvnt.cryptoscope.io/tx/?txid=00c33afe6d7bf838bd6ae502a7618c538b2e85b1a0b63d9f8dccb17a2cf2d4b0)]

Well done!
