### ISSUE TITLE
No hash published for linux release

### ISSUE THREAD

**Issue by fro0xwm** [RavenProject/Ravencoin#874]
Can you publish hashes for the v4.3.2.1 linux releases so they can be validated, thanks

**Comment by TronBlack** [comment]
There is one inside the zip file md5 and sha256 for the tar.gz

3md5   - 22a63625c33df7d6cfc7d53fa43ced0                                   raven-4.3.2.1-x86_64-linux-gnu.tar.gz
sha256 - d57192a656e097d4442a102b525a2e730c6aec2949cd67667b61cf9dfbc5190e  raven-4.3.2.1-x86_64-linux-gnu.tar.gz

**Comment by TronBlack** [comment]
It would be nice in the future to have the hashes also available on the foundation website ravencoin.foundation.  If you trust ravencoin.org, then checking the hashes against ravencoin.org doesn't provide a ton of security.

**Comment by TronBlack** [comment]
Or rather if you don't trust ravencoin.org...

**Comment by TronBlack** [comment]
For anyone monitoring this, the real problem is Discord and/or Telegram messages that send you to a bogus (but similarly legit sounding) website.

**Comment by fdoving** [comment]
linux*.checksums.txt is missing from the released files for 4.3.2.1.
This should be fixed for next release.

As there is no difference from 4.3.2.0 to 4.3.2.1, except the version number, one can use the previous release with published hashes.

My results follows:
SHA256 (raven-4.3.2.1-x86_64-linux-gnu-disable-wallet.zip) = 2ccbe39adbbdc383c3f31417c93c0d0a1e71bb1f7d80b5494089d55a6092b7aa
SHA256 (raven-4.3.2.1-x86_64-linux-gnu.zip) = 691b2e92e5c544d04da6745765ea53f4a975a304c4e04edcdfdcb0127df3b5fd
MD5 (raven-4.3.2.1-x86_64-linux-gnu-disable-wallet.zip) = 93a9e648c237817a17baa36fb60cea39
MD5 (raven-4.3.2.1-x86_64-linux-gnu.zip) = 9d9d0ffe76fed04ea2bbea1d85e2f529
