### ISSUE TITLE
Test password programatically

### ISSUE THREAD

**Issue by mlmarius** [RavenProject/Ravencoin#876]
Is there a way to programmatically test a passphrase against wallet.dat? An example would be great if possible.

**Comment by TronBlack** [comment]
If you just want to try one or two:

Use:
```raven-cli walletpassphrase <pwd> 120```

Or from QT, go to Help->'Debug Window'->Console
```walletpassphrase <pwd> 120```
If it returns 'null', then it worked.

For bulk attempts at a lost passphrase, try:
https://github.com/3rdIteration/btcrecover/blob/master/docs/INSTALL.md
