### ISSUE TITLE
Syncing Header stuck - 0 active connections

### ISSUE THREAD

**Issue by pixelchrome** [RavenProject/Ravencoin#878]
This issue tracker is only for technical issues related to bitcoin-core.

General ravencoin questions and/or support requests and are best directed to the [Ravencoin Discord](https://discord.gg/GwtXdyc).

For reporting security issues, please direct message one of the core developers in discord.

### Describe the issue

I am using the wallet version v4.3.2.1-25a2dbf41. My wallet is from 2018 and I wanted to resync it again. Therefore I installed a new Ubuntu Version and the new Wallet Version. It is now stuck a 73.1 % (Syncing Headers and no active network connection). Looks like there are some hosts no longer online (e.g. 121.211.116.116.190 - no route to host, 31.179.105.90 - connection refused)
 
#### If so, please list the steps to reproduce below:
1. Reboot or restarting of the wallet software didn't solved the issue. Network working fine.

### Expected behaviour
Syncing up to 100%

### Actual behaviour
Tell us what happens instead

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of bitcoin-core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.

### Machine specs:
- OS: Linux - Ubuntu 20.04.2 LTS
- CPU: AMD Ryzen 5
- RAM: 8G
- Disk size: 200G
- Disk Type (HD/SDD): 200G

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by TronBlack** [comment]
Remove your peers.dat from the data dir and try again.

If that doesn't work, back up your wallet.dat, then remove all files and folders from the datadir except wallet.dat and sync from scratch.

**Comment by pixelchrome** [comment]
@TronBlack looks like that helped. I had another backup from more than 2.5 years ago. I've removed the peers.dat file, and it looks like I have now at least one stable connection.
Pretty slow, but I can see now "Syncing Header 81.2 %".

I will keep you informed...

Thanks!

**Comment by pixelchrome** [comment]
@TronBlack it's solved! Many thanks! The removal of peers.dat fixed it.
