### ISSUE TITLE
Fix for IP address list test

### ISSUE THREAD

**Issue by TronBlack** [RavenProject/Ravencoin#883]
IP addresses were added back into the code for 4.3.2.1 and the test is failing.

Criteria:
Fix the test.

**Comment by RavencoinFoundationTron** [comment]
amount=USD$200.00
paid_in=RVN
status=open

**Comment by fdoving** [comment]
Is this the ip-list in src/chainparamsseeds.h? 
Where is the test?

**Comment by TronBlack** [comment]
I fixed the test, but auto-build is broken - dependency failure.
It was a hard-coded date in the test that expired in Dec 2020.  Moved the date out about 10 years.

**Comment by TronBlack** [comment]
Closing issue.
