### ISSUE TITLE
Problems syncing node

### ISSUE THREAD

**Issue by TechyGuy17** [RavenProject/Ravencoin#895]
Hello, i am trying to set up a node but doesnt seam like it can connect with the other nodes and sync
![image](https://user-images.githubusercontent.com/65623992/111294480-ab070d00-864a-11eb-8612-112ef7e0a3ae.png)
I have opened the firewall.
Hope someone has a fix for this

Kind regards, TechyGuy

**Comment by TechyGuy17** [comment]
Oh wait now it started syncing

**Comment by fdoving** [comment]
Can be closed?

**Comment by TronBlack** [comment]
Closing.  During times of high demand (new users) there is a heavy load on the full nodes.  Thank you to everyone who started running new nodes and opening them up by adding NAT or port forwarding on their firewall.
