### ISSUE TITLE
Add ability to use custom base URL for IPFS viewing

### ISSUE THREAD

**Issue by MangoFarmAssets** [RavenProject/Ravencoin#897]
When [PR # 30](https://github.com/RavenProject/Ravencoin/pull/820) was adopted, it helpfully added the ability to view IPFS hashes from the QT through the Cloudflare gateway.  

At the time the code for this PR was written, it was suggested to allow QT wallet users to specify their own base URL (rather than requiring use of Cloudflare).  The author of the PR [indicated](https://github.com/RavenProject/Ravencoin/pull/820#issuecomment-694342147) that using Cloudflare was the first step, but that a configuration option would be added at a later time.  This remains a good idea.

As pointed out to me by @jeroz1, the QT wallet interface currently allows the user to specify their own base URL for viewing transaction information on third-party explorers:
![image](https://user-images.githubusercontent.com/48811998/111455664-79468280-86ec-11eb-97c6-1ae978143c87.png)

Similar functionality could be added, in the same spot, to permit users to specify the base URL for IPFS hash viewing, changing the Cloudflare default used in PR 30.

This would facilitate users' ability to view more complex data structures than Cloudflare's gateway will allow:

Coudflare:

![image](https://user-images.githubusercontent.com/48811998/111456697-afd0cd00-86ed-11eb-91c6-d63932b6dbfd.png)

Custom viewer:
![image](https://user-images.githubusercontent.com/48811998/111456411-5799cb00-86ed-11eb-8a27-efda1e7392c6.png)

Note:  This suggestion is in addition to, not in lieu of, [Proposed Simple Standard For Asset Metadata Viewing In RVN QT #877](https://github.com/RavenProject/Ravencoin/issues/877), which proposes one workable method to allow asset issuers to specify an asset viewer when creating an asset, so that it can be viewed as intended by the asset issuer with customized third-party viewers.

**Comment by TronBlack** [comment]
amount=USD$200.00
paid_in=RVN
status=open
info=https://github.com/RavencoinFoundation/gitRVN

**Comment by fdoving** [comment]
PR #901  to close this is submitted.

If accepted, reward can be sent to: RFmtFb9GdZHvbvBW5hYB3s9VezJxeSfnz3

**Comment by HyperPeek** [comment]
Will be in next release. Can be closed once confirmed.

**Comment by MangoFarmAssets** [comment]
Closing this in light of PR #901.  Many thanks @fdoving
