### ISSUE TITLE
getmywords() and dumpwallet() are not displaying the right passphrase if you've changed it.

### ISSUE THREAD

**Issue by feelie75** [RavenProject/Ravencoin#899]
### Describe the issue

I changed my passphrase (the one used to send RVN/assets) a while back. I was helping a user in #helpdesk and ran a dumpwallet command from the Debug Console. I looked at the output and the "mnemonic passphrase: " was showing my original password from last year when i created the wallet, not my current passphrase.

I then ran the 'getmywords' console command and noticed it did the same thing. 

#### If so, please list the steps to reproduce below:
1. run 'getmywords' from command console. It will say something like: "passphrase": "originalPassword".
2. Now run walletpassphrasechange "originalPassword" "newpassword" (make sure you remember that new password)
3. Now run getmywords again. The passphrase will still say "originalPassword", not your new one!
4. You can verify the walletpassphrasechange worked by just running it again with the same data, "originalPassword" "newpassword" and it will fail because your password has changed. you can run it again, the opposite way, and it will succeed in restoring your password. All the while, getmywords and dumpwallet are not reflecting the changes. 

### Expected behaviour
getmywords and dumpwallet (and probably other passphrase related commands, if there are any) should reflect the CURRENT passphrase.

### Actual behaviour
Original passphrase when wallet was created always shows (where's it keeping that data stored anyhow?)

### What version of ravencoin-core are you using?
Latest, 4.3.2.1 downloaded from official site.

### Machine specs:
- OS: Windows 10
- CPU: Intel i7 9700F
- RAM: 16GB
- Disk size: 1TB
- Disk Type (HD/SDD): HD

**Comment by fdoving** [comment]
I think the output of 'getmywords' give you the (optional) recoverypassphrase generated when the wallet was created.
It is not the same as the password encrypting the wallet.

I can not find any way to show the encryption-password with rpc-commands.

I don't think this is a bug.
