### ISSUE TITLE
Dependencies for build pipeline not available - Fix build pipeline

### ISSUE THREAD

**Issue by TronBlack** [RavenProject/Ravencoin#902]
There are dependencies that are not available.

Fix build pipeline.

**Comment by fdoving** [comment]
I have kind-of started to look at this.

This includes an update of all depends/ from bitcoin.
Also includes some ugly hacks to try to make it build on my Github without the secrets and s3-access.

https://github.com/fdoving/Ravencoin/tree/fdov-git-buildscripts

**Comment by TronBlack** [comment]
amount=USD$500.00
paid_in=RVN
status=open
info=https://github.com/RavencoinFoundation/gitRVN

**Comment by fdoving** [comment]
PR #904 to close this is submitted.

If accepted, reward can be sent to: RFmtFb9GdZHvbvBW5hYB3s9VezJxeSfnz3

**Comment by HyperPeek** [comment]
Tested and works. Will close once paid.

**Comment by hans-schmidt** [comment]
It has bee paid. I am closing it.
