### ISSUE TITLE
Fix build with Qt 5.15 or later, ideally 6.X+

### ISSUE THREAD

**Issue by kentbull** [RavenProject/Ravencoin#906]
### Describe the issue
Ravencoin has build failures when building with newer versions of Qt. 
Significant effort is required to upgrade the Ravencoin Qt library usage from the existing version of 5.7.1 to the current release, 5.15. See the [Qt version history](https://en.wikipedia.org/wiki/Qt_version_history)

#### If so, please list the steps to reproduce below:
1. Use the build OSX instructions
2. try to build ravencoin
3. fails on the type signatures 

### Expected behaviour
Using the official [build-osx.md](https://github.com/RavenProject/Ravencoin/blob/master/doc/build-osx.md) instructions to build the GUI wallet should work upon completing all of the given instructions.

### Actual behaviour
The build fails.

### Screenshots.
Coming.

### What version of ravencoin-core are you using?
latest master as of 03-01-2021

### Machine specs:
- OS: OS X
- CPU: Intel 
- RAM:  16GB
- Disk size: 500GB
- Disk Type (HD/SDD): SSD

### Any extra information that might be useful in the debugging process.
Precise errors incoming.

**Comment by fdoving** [comment]
This must be build-instructions related.
Ravencoin builds fine with 5.12.10 without changing the code.

This should not be related to the depends we reference in depends/, which are used in git-builds.
The instructions in https://github.com/RavenProject/Ravencoin/blob/master/doc/build-osx.md does not have you build those.
It wants to download from brew.

**Comment by kencodible** [comment]
If we can use depends for OS X that would be great. Brew no longer allows installation of anything older than about 5.15.
Upgrading to 5.15 or 6 would be a major undertaking.

**Comment by fdoving** [comment]
I have made PR 910 for updating the Qt we use for auto builds on github to 5.12.10 (and most other depends.)
I have not tried to build Ravencoin with 5.15+

**Comment by HyperPeek** [comment]
I suggest to close with PR #910

**Comment by fdoving** [comment]
We should test-build with Qt 5.15+ and fix issues encountered in the process.
Something will need changing, anyone interested can check bitcoin PRs for Qt 5.15 related changes.

We can keep this issue, but it needs to be re-named and re-worded to describe the problem better.
Something along the lines of "Fix building with Qt 5.15+"

I do not want to upgrade depends/ to 5.15.x that at this point.
This issue is when the user installs his own newer Qt version, and do not use the depends/-folder at all.

**Comment by fdoving** [comment]
> I suggest to close with PR #910

#910 does not fix this.

**Comment by HyperPeek** [comment]
Ok, sorry -- you are right. I will rename to make clear its about Qt 5.15.

**Comment by fdoving** [comment]
I successfully built Ravencoin on Ubuntu 21.04 Hirsute Hippo, with Qt 5.15.2 and all depends installed from apt.
The only trick I used, was `./configure --with-incompatible-bdb`

**Comment by fdoving** [comment]
I think this can be closed.
If anything, this is MacOS specific.

**Comment by hans-schmidt** [comment]
The goal of building with Qt 5.15 has been achieved.
We currently have limited capability for Mac testing.
If there are any remaining Mac issues, please open a new Issue.
I am closing this issue.
