### ISSUE TITLE
Latest version of "-arm-linux-gnueabihf.tar.gz" for download

### ISSUE THREAD

**Issue by Mynima** [RavenProject/Ravencoin#907]
Just a quick request to see if it would be possible to get a "-arm-linux-gnueabihf.tar.gz" version added to the releases for v4.3.2.1. Currently looks like the last time this was available was v4.3.1.0.

Cheers

**Comment by fdoving** [comment]
It's not a release, but you can get one from https://github.com/RavenProject/Ravencoin/actions/runs/691540276

**Comment by fdoving** [comment]
It is actually the raven-4.3.2.1-arm32v7.zip package, it is released, and you can find it here: https://github.com/RavenProject/Ravencoin/releases/tag/v4.3.2.1

Issue can be closed.

**Comment by Mynima** [comment]
Thanks, I’ll go ahead and adjust my script to pull this version going forward. Will the standard naming convention be maintained?

**Comment by fdoving** [comment]
I would not be surprised if there are slight changes in the future.
A new system for releases has been mentioned.

**Comment by Mynima** [comment]
Thanks, will keep an eye out.

**Comment by wongasley** [comment]
Hello, have you figured out how to pull the new node/wallet?

**Comment by Mynima** [comment]
> Hello, have you figured out how to pull the new node/wallet?

Hi, yes taking a look at the script I see what needs to be done. First we need to download this file: raven-x.x.x.x-arm32v7.zip then (after unzipping) extract from the arm32v7 subfolder raven-x.x.x.x-arm-linux-gnueabihf.tar.gz. I can quickly make this update to the script though I don't think I will be able to test it this morning.

**Comment by wongasley** [comment]
I changed some of the codes that you made but I am stuck on this line:

cp: cannot stat './raven-4.3.2.1/bin/*': No such file or directory

**Comment by Mynima** [comment]
I've just updated my script. Delete the old one and then download the latest version of the 01 script. When it asks for the version number type 4.3.2.1. The rest should work, just tested it on my node and updated with no issues.

**Comment by wongasley** [comment]
Thank you! I was actually still figuring out how to update but you already done it!

**Comment by Mynima** [comment]
you're very welcome, hopefully that solves it for now. I'm going to close this thread :)
