### ISSUE TITLE
GUI: Transfer Assets - Spinbox for Amount default increments.

### ISSUE THREAD

**Issue by fdoving** [RavenProject/Ravencoin#908]
GUI: Transfer Asset -> Amount

1. Go to Transfer Assets
2. Select an asset.
3. Click up arrow on the Amount spinbox.

It will increment by 100 000 if the asset has no units.
The spinbox is not aware of asset-specific units.

**Comment by fdoving** [comment]
I have a fix ready for this. Waiting for #904 to be accepted and merged, before making the PR.

(The diff github includes in this issue, 872baee, can not be used directly, as it includes some auto-generated qtcreator-stuff that breaks builds on the old QT 5.7.1 we use.)

**Comment by HyperPeek** [comment]
Should be fixed

**Comment by fdoving** [comment]
This is fixed in current develp.
