### ISSUE TITLE
Please add the linked intructions to 'linux_README.md' under 'releases' for Raspberry Pi compiling

### ISSUE THREAD

**Issue by seanspotatobusiness** [RavenProject/Ravencoin#91]
Under 'releases' is a file called 'linux_README.md' - I think it could be modified to include instructions to compile on the Raspberry Pi. The instructions to do this were written by user 'traysi' from the 'Ravencoin Community' Discord. I've followed them successfully on my own Pi 3 B running Rasbian Stretch. The instructions compile the wallet without GUI. To compile with GUI change '--with-gui=no' to '--with-gui=yes'.

The instructions are here: https://traysi.org/raven_rpi.php

**Comment by TronBlack** [comment]
Added to the doc folder.
https://github.com/RavenProject/Ravencoin/blob/master/doc/build-rasberrypi.md

**Comment by TronBlack** [comment]
Thank you.
