### ISSUE TITLE
JSON file request for the complete QT wallet translation.

### ISSUE THREAD

**Issue by bradar** [RavenProject/Ravencoin#912]
I would like to work on the whole Korean translation of the QT wallet.

However, for easy updates in other languages as well, it would be the best to have one unified JSON file (English on the left, other languages on the right.)

People can submit the pull requests after the complete translation of each language.

**Comment by jeroz1** [comment]
I've seen this request more often. It should definitely be easier to provide translations.

**Comment by fdoving** [comment]
We need to figure out a way. 
I'm looking at https://docs.transifex.com/projects/open-source-project

**Comment by fdoving** [comment]
You can now translate Ravencoin at: https://www.transifex.com/ravencoin/

I think that is the solution to this problem, and this issue can be closed.

**Comment by bradar** [comment]
Thanks! I started working on translating everything in Korean.

**Comment by HyperPeek** [comment]
Will close as transifex work is in progress towards release.
