### ISSUE TITLE
RVNCOINS in rvncore network not appear in rvncore wallet on my desktop

### ISSUE THREAD

**Issue by gadoo2020** [RavenProject/Ravencoin#918]
iam using rvncore wallet desktop and i`ve generated a receving address with no label or amount
i`ve copied the address and worked with flypool 
after alot of payouts the final balance on network website not appear in my wallet !!!
NOTE:the wallet is updated and synchronised

**Comment by fdoving** [comment]
Do you have txids from flypool we can investigate?

Asking for assistance in #helpdesk on discord, https://discord.gg/GwtXdyc can be a good way to investigate this issue. 
Especially if you don't want to publish your txids and addresses here in the issues on github.

**Comment by alisscco** [comment]
I think I may have from fly pool , something is up there discord room is
full of scams they have attempted to access my info twice .

**Comment by gadoo2020** [comment]
> Do you have txids from flypool we can investigate?
> 
> Asking for assistance in #helpdesk on discord, https://discord.gg/GwtXdyc can be a good way to investigate this issue.
> Especially if you don't want to publish your txids and addresses here in the issues on github.

R9J8MH6t3BYCPXMFLa35R7aUJV9i4siPhX

**Comment by fdoving** [comment]
The coins are in this address.
First double check that your wallet has this exact address.

If your wallet have private keys for this address, try to reindex and check that you are on the same block height.

I will repeat my suggestion to ask for help in #helpdesk on discord for this issue.

**Comment by HyperPeek** [comment]
I suggest to close as it is too unspecific

**Comment by hans-schmidt** [comment]
I am closing this due to insufficient information.
Please open a new issue if appropriate.
