### ISSUE TITLE
GUI: Third party browsers URLs - move defaults to constant

### ISSUE THREAD

**Issue by fdoving** [RavenProject/Ravencoin#932]
Copy from: https://github.com/RavenProject/Ravencoin/pull/922#pullrequestreview-638241619

ben-abraham left a comment:

I would suggest moving the hardcoded URL value from OptionsDialog::on_thirdPartyTxUrlsReset_clicked() and void OptionsModel::Init(bool resetSettings) to a default constant somewhere.
I'm not sure if there is a great place for those kind of default constants anywhere currently.

I agree on the constant.
And suggest to put it in [src/qt/guiconstants.h](https://github.com/RavenProject/Ravencoin/blob/master/src/qt/guiconstants.h)

**Comment by hans-schmidt** [comment]
This has been fixed in PR#944
Closing.
