### ISSUE TITLE
contrib: verify-commits/ - update or remove.

### ISSUE THREAD

**Issue by fdoving** [RavenProject/Ravencoin#949]
contrib/verify-commits should be updated or removed.

I'm for updating and adding actually used keys.

**Comment by HyperPeek** [comment]
Not sure I 100% understand -- you mean commits in review of PR's?

**Comment by fdoving** [comment]
The folder commit/verify-commits contains a tool to check commits against a list of known good GPG-keys.
It has never been used on Ravencoin as far as I can tell. Only raven changes seems to be the automatic renaming.

The directory should either be removed, or we should start using the tool.
I vote for removing the unused directory.

If we ever want to get it back, we can get it from history or look to what bitcoin uses now and do something similar.

**Comment by HyperPeek** [comment]
Ok, 100% agree on that. Lets remove it. I was not even aware of it :-)

**Comment by fdoving** [comment]
PR #960 will close this, if accepted.

**Comment by fdoving** [comment]
#960 merged, closing.
