### ISSUE TITLE
GUI: Update QT colors to match Ravencoin Logo

### ISSUE THREAD

**Issue by MichaelFusco** [RavenProject/Ravencoin#952]
### Describe the issue
Ravencoin QT color scheme shows a shade of blue that is lighter than the Ravencoin logo. Suggest updating to logo color scheme. Will research the RGB numbers for each color.

### Screenshots.
![RavenQT Color Issue](https://user-images.githubusercontent.com/79958366/115977158-560cbf80-a543-11eb-970b-952d41650e1f.png)

### What version of Raven-core are you using?
4.3.2.1

### Machine specs:
- OS: Windows 10

**Comment by MichaelFusco** [comment]
The picture is deceiving.
Further look shows that the colors fade from dark in the lower right into lighter shade near the Writing. Seems intentional?

**Comment by fdoving** [comment]
I agree with you.
A cleaner look is better.

I think most of the current colors are set in this file: https://github.com/RavenProject/Ravencoin/blob/2613cf667fe9936295ee8462d5ba8a14dd343a22/src/qt/guiconstants.h

For dark styles https://github.com/RavenProject/Ravencoin/blob/ddc821eec726eafc7ba444b177d0190d785a0925/src/qt/darkstyle.cpp

Let me know when you have some color suggestions.
I can easily compile some test-binaries with modified colors.

**Comment by MichaelFusco** [comment]
Red - r240 g82 b57
Orange - r247 g148 b51
Blue - r56 g65 b130
![logo-wide-sm](https://user-images.githubusercontent.com/79958366/115986581-d997d200-a57e-11eb-8c96-b6730bc0f252.png)

**Comment by jeroz1** [comment]
Is it a lot of work to add a settings window that allows users to pick their own colors for those variables in https://github.com/RavenProject/Ravencoin/blob/2613cf667fe9936295ee8462d5ba8a14dd343a22/src/qt/guiconstants.h ? @fdoving

**Comment by fdoving** [comment]
No.

**Comment by fdoving** [comment]
> Is it a lot of work to add a settings window that allows users to pick their own colors for those variables in https://github.com/RavenProject/Ravencoin/blob/2613cf667fe9936295ee8462d5ba8a14dd343a22/src/qt/guiconstants.h ? @fdoving

No, I don't think so.

**Comment by fdoving** [comment]
My thought after 2min : 
A button named 'Customize colors' - or something along those lines.
Placed around here:
![image](https://user-images.githubusercontent.com/26197922/115988139-9f4b2680-a5b8-11eb-9268-bc0fe0643805.png)

Can bring up a color-picker-window where the user can pick their colors, each with a Reset button, to revert to the default.

**Comment by MichaelFusco** [comment]
Go full custom?
Am looking at the code, converting the RGB to Hex and comparing to current.

**Comment by fdoving** [comment]
We currently have these functions, if we could narrow it down to 4-5-ish and make some the same:
    QColor TextColor() const;
    QColor ToolBarSelectedTextColor() const;
    QColor ToolBarNotSelectedTextColor() const;
    QColor SingleColor() const;
    QColor MainBackGroundColor() const;
    QColor TopWidgetBackGroundColor() const;
    QColor WidgetBackGroundColor() const;
    QColor SendEntriesBackGroundColor() const;
    QColor ShadowColor() const;
    QColor LightBlueColor() const;
    QColor DarkBlueColor() const;
    QColor LightOrangeColor() const;
    QColor DarkOrangeColor() const;
    QColor AssetTxColor() const;

**Comment by MichaelFusco** [comment]
-Logo Blue
Hex - #384182 (current is #475eaa)
RGB - 56,65,130 (current is 71,94,170)
Matches closest but darker than below current code

-Current Code
/* Ravencoin dark blue */
#define COLOR_DARK_BLUE QColor("#475eaa")

-Suggested code
/* Ravencoin dark blue */
#define COLOR_DARK_BLUE QColor("#384182")

-Logo Light Orange
Hex - #F79433
Same as current code for Light Orange

-Logo Dark Orange
Hex - #F05239 (current is #f05339) 
RGB - 247,82,57 (current is 240,83,57)
Very similar to current code, Could be due to update in photoshop or other tool

-Current Code
/* Ravencoin dark orange */
#define COLOR_DARK_ORANGE QColor("#f05339")

-Suggested Code
/* Ravencoin dark orange */
#define COLOR_DARK_ORANGE QColor("#f05239")

**Comment by fdoving** [comment]
Screenshots showing new and old colors.

![image](https://user-images.githubusercontent.com/26197922/116008068-0eedff80-a613-11eb-9416-22bc8331bb99.png)
![image](https://user-images.githubusercontent.com/26197922/116008088-20cfa280-a613-11eb-94a3-24ba1f738897.png)

**Comment by MichaelFusco** [comment]
Semi subtle. But looks much improved in my opinion. Matches the logo at least.

**Comment by HyperPeek** [comment]
Fixed by PR #956
