### ISSUE TITLE
GUI: Add a warning message before opening IPFS links

### ISSUE THREAD

**Issue by jeroz1** [RavenProject/Ravencoin#970]
Related to #432.

Current functionality is imho very dangerous as it instantly opens a browser tab accessing the IPFS link.

**Comment by soullesscomputerboy** [comment]
Glad this is being brought up, as I was considering posting this myself. I think this is absolutely crucial for the success of RVN long term.

**Comment by fdoving** [comment]
I don't like warnings when you click on stuff. But I understand that in some cases it is the right thing to do.

We send people to their browsers for a reason. Security is the reason.
Browsers know how to handle most files. Download and auto-run is probably not that common. But I get the concern.

If we implement this, I want a checkbox in options for 'Advanced Mode/ Don't show extra warnings'.
If enabled, the warnings are not shown.

**Comment by HyperPeek** [comment]
I agree with fdov, but its not only about auto-run, but also a simple re-direct to a webpage which can on its own cause a problem. However, we do want the disable button; either in the dialog itself or some setting.

**Comment by fdoving** [comment]
This is a dead simple implementation, if we drop the setting, and only do it for the left-clicks on the overview-page:
Like 10 lines changed.

![image](https://user-images.githubusercontent.com/26197922/117341663-b506f880-aea2-11eb-88ab-5999d01cbbbe.png)

**Comment by fdoving** [comment]
I am aware of the typo, the text probably need to change.

**Comment by jeroz1** [comment]
Do you want to open the following IPFS content in your default browser?
[Link]
[Yes] [No]

**Comment by fdoving** [comment]
Can be closed. #978 is merged to develop.
