### ISSUE TITLE
raven-qt lags when there are many transactions

### ISSUE THREAD

**Issue by soullesscomputerboy** [RavenProject/Ravencoin#973]
### Describe the issue
Raven-qt lags after sending thousands of transactions, I realize this is probably not a problem for most people and shouldn't be a priority. Over time however I imagine many people will have thousands of transactions.

#### If so, please list the steps to reproduce below:
1.Send/Receive 90k+ transactions

### Expected behaviour
No lagging

### Actual behaviour
Scroll bars lag, switching between overview/send/receive etc lag, this is much worse after sending a single transaction.

### What version of bitcoin-core are you using?
Raven Core version v4.3.2.1-25a2dbf41 (64-bit)

### Machine specs:
- OS: Windows 10
- CPU: Ryzen 2600
- RAM: 64GB
- Disk size: 500GB
- Disk Type (HD/SDD): SSD

**Comment by fdoving** [comment]
Could be related to #1036

**Comment by soullesscomputerboy** [comment]
This is mostly fixed in v4.7.0.0-b5010492c (test build). There is still lagging when sending transactions and initially booting raven core but it is almost a non-issue now. Switching between tabs no longer lags at all and scroll bars are usable.

**Comment by fdoving** [comment]
v4.7.0.0-b5010492c is https://github.com/fdoving/Ravencoin/releases/tag/v4.7.0test3-fdov

**Comment by fdoving** [comment]
Can be closed once a release is made with #1036 included.

**Comment by fdoving** [comment]
#1036 merged.
