### ISSUE TITLE
GUI: Add recover 12 seed words option

### ISSUE THREAD

**Issue by jeroz1** [RavenProject/Ravencoin#975]
Please add an option: Wallet > Get seed words. With optional password requirement when the wallet is encrypted.

**Comment by HyperPeek** [comment]
Without looking into the code -- is this possible? I always assumed this is a one-way just used at startup to generate the keys and reverse (from keys to seed) is not possible. May be wrong though.

**Comment by jeroz1** [comment]
I imaged this to be a GUI wrapper around `getmywords` in the console

**Comment by jeroz1** [comment]
The words are also printed in the `dumpwallet` text file.

**Comment by fdoving** [comment]
I will try to make this.

**Comment by fdoving** [comment]
I have a working implementation.
Needs some polish.

![image](https://user-images.githubusercontent.com/26197922/117209739-0b1e6200-adf7-11eb-9161-61907ce2b282.png)
![image](https://user-images.githubusercontent.com/26197922/117209759-12457000-adf7-11eb-8574-f6d2c45c65e0.png)
