### ISSUE TITLE
Update seeds for testnet.

### ISSUE THREAD

**Issue by fdoving** [RavenProject/Ravencoin#980]
https://github.com/RavenProject/Ravencoin/blob/9def8ed6b5aa6f8d6aa3a53436197233941d7e17/src/chainparamsseeds.h#L194

The two ips listed does not respond to ping or tcp connections on the specified ports.

**Comment by HyperPeek** [comment]
The foundation setup new seed nodes on Digital Ocean, so we should find out their addresses and update the seeds.

**Comment by fdoving** [comment]
#1027 merged to develop, closing.
