### ISSUE TITLE
Testing:  #890 Dockerfile

### ISSUE THREAD

**Issue by fdoving** [RavenProject/Ravencoin#982]
Task:
<html>
<body>

Build image from the file and test-run. Make sure it works.
https://github.com/RavenProject/Ravencoin/commit/e5c4e87e5e58a429de2e4443ca00d0a7848217b5
--

</body>
</html>

Post your test results as comments to this issue.

Please include release version or commit-hash used when testing.

**Comment by fdoving** [comment]
INFO: This file has been moved to contrib/ in the develop branch.

Consider removing the bitcoin ppa, no longer maintaned.
Ref: https://launchpad.net/~bitcoin/+archive/ubuntu/bitcoin

Can use contrib/install_db4.sh to compile and install berkeley db.

**Comment by jeroz1** [comment]
`docker build -t ravencoin:4.7 -f contrib/`

Works for me

**Comment by fdoving** [comment]
I made #1026 with proposed updates.

**Comment by fdoving** [comment]
#1026 merged to develop.

**Comment by Deadheded** [comment]
Installed Test V3 with no issues.  I picked up my existing wallet.dat file.  This .dat file also has a "watched" address and that displayed perfectly.  The resolution of the 4.7 wallet is higher than the current stable qt release.  I like the higher resolution as I have more information showing on one window.   More testing to come

**Comment by fdoving** [comment]
I think the last comment is not Docker related?

**Comment by fdoving** [comment]
Closing this, less important test. It works on amd64.
