### ISSUE TITLE
Testing: #894 Price preview header

### ISSUE THREAD

**Issue by fdoving** [RavenProject/Ravencoin#983]
Task:
Make sure it works. Switch to all the options.

Post your test results as comments to this issue.

Please include release version or commit-hash used when testing.

**Comment by soullesscomputerboy** [comment]
This works on Windows 10 and v4.7.0.0-27dec57fc. Tested all options.

**Comment by lsji07** [comment]
This works on Windows 10 and Raven Core version v4.7.0.0-b5010492c (64-bit). Tested all options.

**Comment by soullesscomputerboy** [comment]
Works on linux mint and core v4.7.0.0-b5010492c (64-bit). Tested all options

**Comment by fdoving** [comment]
2x Confirmed working as expected. Closing as finished.

**Comment by jeroz1** [comment]
v4.7.0test3-fdov
MacOS Big Sur 11.6.1

<img width="95" alt="Screenshot 2021-12-10 at 23 09 54" src="https://user-images.githubusercontent.com/44138303/145647822-dfdfeb46-01f7-48a6-a59c-dd8eac3e519f.png">

check mark is awkwardly close to the drop down options.

**Comment by jeroz1** [comment]
v4.7.0test3-fdov
MacOS Big Sur 11.6.1

Contrast in dark mode makes the value very hard to read.

<img width="361" alt="Screenshot 2021-12-11 at 09 25 33" src="https://user-images.githubusercontent.com/44138303/145669953-f4821061-2138-4588-8f25-6b63532e5c0a.png">
<img width="88" alt="Screenshot 2021-12-11 at 09 25 48" src="https://user-images.githubusercontent.com/44138303/145669955-606cdcec-dcc6-4af6-9939-8bc95b812370.png">
