### ISSUE TITLE
Testing: #901 Configurable IPFS-viewer

### ISSUE THREAD

**Issue by fdoving** [RavenProject/Ravencoin#985]
Post your test results as comments to this issue.

Please include release version or commit-hash used when testing.

**Comment by soullesscomputerboy** [comment]
Seems to work as intended on windows 10 and client v4.7.0.0-27dec57fc.

**Comment by soullesscomputerboy** [comment]
This works on linux mint and core v4.7.0.0-b5010492c (64-bit)

**Comment by m4r1m0** [comment]
Tested and working on Ubuntu 20.04 using raven-4.7.0test3-b5010492c (64 bit)

**Comment by fdoving** [comment]
2x Confirmed working as expected. Closing as finished.
