### ISSUE TITLE
Testing: #917 Configurable out of the box browsers

### ISSUE THREAD

**Issue by fdoving** [RavenProject/Ravencoin#986]
Post your test results as comments to this issue.

Please include release version or commit-hash used when testing.

The browsers will not work on testnet transcations. Testing this is easier if mainnet works. (Currently does not sync).

This url should work:
`https://rvnt.cryptoscope.io/tx/?txid=%s`

**Comment by soullesscomputerboy** [comment]
This works for me on linux mint and core v4.7.0.0-b5010492c (64-bit)

**Comment by Deadheded** [comment]
Raven Core version v4.7.0.0-b5010492c (64-bit)

Added multiple explorers and changed IPFS gateway.

All worked perfectly.

**Comment by fdoving** [comment]
2x confirms. Closing as finished.
