### ISSUE TITLE
Testing: #927 Transfer Assets and Send view

### ISSUE THREAD

**Issue by fdoving** [RavenProject/Ravencoin#988]
Post your test results as comments to this issue.

Please include release version or commit-hash used when testing.

**Comment by soullesscomputerboy** [comment]
Windows 10 and client v4.7.0.0-27dec57fc. Default values look correct, arrows work as intended.

**Comment by soullesscomputerboy** [comment]
Linux mint and v4.7.0.0-b5010492c (64-bit). All looks correct and arrows work as intended.

**Comment by m4r1m0** [comment]
Tested and working on Ubuntu 20.04 using raven-4.7.0test3-b5010492c (64 bit).

Transferred Main Asset, Sub Asset, Restricted Assets, and Unique Asset. All working correctly. Restricted Assets cannot be transferred until the transaction with the appropriate qualifier string has been mined into a block (as intended, there is also a dialogue box to inform the user). All arrows/menus working correctly. 

Assigned and Removed Qualifiers. All functionality/arrows working correctly. Dialogue boxes to inform user of errors assigning/removing qualifiers to ineligible addresses working correctly.

**Comment by fdoving** [comment]
2x Confirmed working as expected. Closing as finished.

**Comment by jeroz1** [comment]
v4.7.0test3-fdov
MacOS Big Sur 11.6.1

Sort of related, Create assets panel:
<img width="1124" alt="Screenshot 2021-12-11 at 09 17 59" src="https://user-images.githubusercontent.com/44138303/145670277-164964d0-255f-4b1e-adfe-13077f086d6f.png">
This drop down menu item needs to be wider in all versions.

**Comment by fdoving** [comment]
@jeroz1 I agree, sort of, but please create a new issue. This one is closed and it does not address the topic.
